/**
 * Complete Pipeline Test: Original → Phase 17 → Phase 18 Refinement
 *
 * Shows the full journey from original essay text through suggestions to final refined output
 */

import { validateSuggestions } from '../supabase/functions/validate-suggestions/simple-validator.ts';

// ============================================================================
// ORIGINAL ESSAY EXCERPTS (The actual student writing)
// ============================================================================

const ORIGINAL_EXCERPT_1 = {
  quote: "I lost interest in toys, eventually stashing my whole realm of imagination and inventiveness in the pathetic environment of my garage.",
  issues: ["Generic 'lost interest'", "Abstract language", "No specific details"]
};

const ORIGINAL_EXCERPT_2 = {
  quote: "Throughout high school, I gained the knowledge necessary to build a portfolio of my work.",
  issues: ["Vague 'gained knowledge'", "Passive voice", "No specifics about the work"]
};

const ORIGINAL_EXCERPT_3 = {
  quote: "I learned leadership through this experience.",
  issues: ["Generic 'learned leadership'", "Telling not showing", "No evidence"]
};

// ============================================================================
// PHASE 17 SUGGESTIONS (Generated by current system)
// ============================================================================

const PHASE_17_SUGGESTIONS = {
  excerpt_1: [
    {
      id: "excerpt1_sug1",
      text: "By freshman year, my Lego Death Star had been gathering dust on my desk for months—I'd walk past it to get to my laptop, barely noticing the gray plastic that used to consume entire weekends. The day I finally carried those bins to the garage, feeling their familiar weight one last time, I realized what I missed wasn't the building itself but the rush of solving each step, figuring out how pieces clicked together.",
      type: "voice_amplifier",
      rationale: "Transforms abstract 'lost interest' into concrete scene with specific age (freshman year), object (Lego Death Star), sensory details (gray plastic, familiar weight), and insight about problem-solving."
    },
    {
      id: "excerpt1_sug2",
      text: "At 15, I watched my Lego collection disappear into cardboard boxes—14 years of birthday sets, from the basic city police station to the 5,922-piece Millennium Falcon. My little brother asked if he could have them. 'Take them,' I said, already turning back to my Python compiler. But handing over that last box felt like closing a chapter I wasn't sure I wanted to end.",
      type: "divergent_strategy",
      rationale: "Takes a different angle: the moment of letting go, includes specific ages and piece counts, adds relationship dimension with brother."
    }
  ],

  excerpt_2: [
    {
      id: "excerpt2_sug1",
      text: "Junior year: 47 syntax errors in my first JavaScript project. Senior year: a functional web scraper analyzing 10,000+ college essay samples. Between those two points, I spent 300+ hours debugging, rebuilding, and learning that 'portfolio-worthy' doesn't mean perfect—it means showing the evolution from broken code to working solutions.",
      type: "voice_amplifier",
      rationale: "Replaces vague 'gained knowledge' with specific progression: concrete numbers (47 errors, 10,000 samples, 300 hours), shows growth through contrast."
    },
    {
      id: "excerpt2_sug2",
      text: "I built my first website at 16 using HTML, CSS, and JavaScript. Throughout the process of creating this website, I encountered many syntax errors and code malfunctions. After debugging each issue, I eventually launched the site with over 500 registered users, which brings me immense joy.",
      type: "polished_original",
      rationale: "Maintains original structure while adding age and user count."
    }
  ],

  excerpt_3: [
    {
      id: "excerpt3_sug1",
      text: "I used to think leadership meant having all the answers. After three event flops—a fundraiser that raised $40 instead of $400, a volunteer shift where nobody showed up, and a club meeting where I talked for 45 minutes and heard crickets—I learned it's about asking the right questions. 'What do YOU think we should do?' became more powerful than 'Here's my plan.'",
      type: "voice_amplifier",
      rationale: "Shows leadership through specific failures (with numbers), demonstrates belief shift (before→after), grounds insight in concrete examples."
    },
    {
      id: "excerpt3_sug2",
      text: "Through this leadership experience, I developed valuable skills in communication and teamwork. I learned that effective leaders listen to their team members and adapt their approach based on feedback. This taught me the importance of collaboration and helped me grow as a leader.",
      type: "polished_original",
      rationale: "Basic improvement with clearer language."
    }
  ]
};

// ============================================================================
// TEST EXECUTION
// ============================================================================

async function testCompletePipeline() {
  console.log('🎯 COMPLETE PIPELINE TEST: Original → Phase 17 → Phase 18');
  console.log('='.repeat(80));

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    console.error('❌ ANTHROPIC_API_KEY not set');
    return;
  }

  const essayContext = "Student writes about transition from childhood Legos to coding, exploring problem-solving as constant thread connecting both interests.";

  // ========================================================================
  // EXCERPT 1: "Lost interest in toys" → Phase 17 → Phase 18
  // ========================================================================
  console.log('\n📝 EXCERPT 1: Lost Interest in Toys');
  console.log('-'.repeat(80));

  console.log('\n❌ ORIGINAL:');
  console.log(`   "${ORIGINAL_EXCERPT_1.quote}"`);
  console.log('   Issues:');
  ORIGINAL_EXCERPT_1.issues.forEach(issue => console.log(`     - ${issue}`));

  console.log('\n✨ PHASE 17 SUGGESTIONS:');
  PHASE_17_SUGGESTIONS.excerpt_1.forEach((sug, i) => {
    console.log(`\n   Suggestion ${i+1} (${sug.type}):`);
    console.log(`   "${sug.text}"`);
  });

  console.log('\n🔍 PHASE 18 VALIDATION:');
  const excerpt1Validation = await validateSuggestions(
    PHASE_17_SUGGESTIONS.excerpt_1.map(s => ({
      suggestion_id: s.id,
      suggestion_text: s.text,
      suggestion_type: s.type
    })),
    essayContext,
    apiKey
  );

  excerpt1Validation.forEach((val, i) => {
    console.log(`\n   Suggestion ${i+1} Results:`);
    console.log(`     Score: ${val.quality_score}/10`);
    console.log(`     Verdict: ${val.verdict}`);
    if (val.issues.length > 0) {
      console.log(`     Issues:`);
      val.issues.forEach(issue => console.log(`       - ${issue}`));
    }
    if (val.improvements.length > 0) {
      console.log(`     Improvements:`);
      val.improvements.forEach(imp => console.log(`       - ${imp}`));
    }
  });

  // ========================================================================
  // EXCERPT 2: "Gained knowledge" → Phase 17 → Phase 18
  // ========================================================================
  console.log('\n\n📝 EXCERPT 2: Gained Knowledge');
  console.log('-'.repeat(80));

  console.log('\n❌ ORIGINAL:');
  console.log(`   "${ORIGINAL_EXCERPT_2.quote}"`);
  console.log('   Issues:');
  ORIGINAL_EXCERPT_2.issues.forEach(issue => console.log(`     - ${issue}`));

  console.log('\n✨ PHASE 17 SUGGESTIONS:');
  PHASE_17_SUGGESTIONS.excerpt_2.forEach((sug, i) => {
    console.log(`\n   Suggestion ${i+1} (${sug.type}):`);
    console.log(`   "${sug.text}"`);
  });

  console.log('\n🔍 PHASE 18 VALIDATION:');
  const excerpt2Validation = await validateSuggestions(
    PHASE_17_SUGGESTIONS.excerpt_2.map(s => ({
      suggestion_id: s.id,
      suggestion_text: s.text,
      suggestion_type: s.type
    })),
    essayContext,
    apiKey
  );

  excerpt2Validation.forEach((val, i) => {
    console.log(`\n   Suggestion ${i+1} Results:`);
    console.log(`     Score: ${val.quality_score}/10`);
    console.log(`     Verdict: ${val.verdict}`);
    if (val.issues.length > 0) {
      console.log(`     Issues:`);
      val.issues.forEach(issue => console.log(`       - ${issue}`));
    }
    if (val.improvements.length > 0) {
      console.log(`     Improvements:`);
      val.improvements.forEach(imp => console.log(`       - ${imp}`));
    }
  });

  // ========================================================================
  // EXCERPT 3: "Learned leadership" → Phase 17 → Phase 18
  // ========================================================================
  console.log('\n\n📝 EXCERPT 3: Learned Leadership');
  console.log('-'.repeat(80));

  console.log('\n❌ ORIGINAL:');
  console.log(`   "${ORIGINAL_EXCERPT_3.quote}"`);
  console.log('   Issues:');
  ORIGINAL_EXCERPT_3.issues.forEach(issue => console.log(`     - ${issue}`));

  console.log('\n✨ PHASE 17 SUGGESTIONS:');
  PHASE_17_SUGGESTIONS.excerpt_3.forEach((sug, i) => {
    console.log(`\n   Suggestion ${i+1} (${sug.type}):`);
    console.log(`   "${sug.text}"`);
  });

  console.log('\n🔍 PHASE 18 VALIDATION:');
  const excerpt3Validation = await validateSuggestions(
    PHASE_17_SUGGESTIONS.excerpt_3.map(s => ({
      suggestion_id: s.id,
      suggestion_text: s.text,
      suggestion_type: s.type
    })),
    essayContext,
    apiKey
  );

  excerpt3Validation.forEach((val, i) => {
    console.log(`\n   Suggestion ${i+1} Results:`);
    console.log(`     Score: ${val.quality_score}/10`);
    console.log(`     Verdict: ${val.verdict}`);
    if (val.issues.length > 0) {
      console.log(`     Issues:`);
      val.issues.forEach(issue => console.log(`       - ${issue}`));
    }
    if (val.improvements.length > 0) {
      console.log(`     Improvements:`);
      val.improvements.forEach(imp => console.log(`       - ${imp}`));
    }
  });

  // ========================================================================
  // SUMMARY & RECOMMENDATIONS
  // ========================================================================
  console.log('\n\n' + '='.repeat(80));
  console.log('📊 PIPELINE SUMMARY');
  console.log('='.repeat(80));

  const allValidations = [...excerpt1Validation, ...excerpt2Validation, ...excerpt3Validation];

  const avgScore = allValidations.reduce((sum, v) => sum + v.quality_score, 0) / allValidations.length;
  const excellentCount = allValidations.filter(v => v.verdict === 'excellent').length;
  const goodCount = allValidations.filter(v => v.verdict === 'good').length;
  const needsWorkCount = allValidations.filter(v => v.verdict === 'needs_work').length;

  console.log(`\nTotal Suggestions Tested: ${allValidations.length}`);
  console.log(`Average Quality Score: ${avgScore.toFixed(1)}/10`);
  console.log(`\nBreakdown:`);
  console.log(`  ✅ Excellent (9-10): ${excellentCount}`);
  console.log(`  ✅ Good (7-8): ${goodCount}`);
  console.log(`  ⚠️  Needs Work (0-6): ${needsWorkCount}`);

  console.log(`\n🎯 TOP RECOMMENDATIONS (Highest Scoring):`);
  const topSuggestions = allValidations
    .sort((a, b) => b.quality_score - a.quality_score)
    .slice(0, 3);

  topSuggestions.forEach((sug, i) => {
    const original = PHASE_17_SUGGESTIONS.excerpt_1.find(s => s.id === sug.suggestion_id) ||
                     PHASE_17_SUGGESTIONS.excerpt_2.find(s => s.id === sug.suggestion_id) ||
                     PHASE_17_SUGGESTIONS.excerpt_3.find(s => s.id === sug.suggestion_id);

    if (original) {
      console.log(`\n  ${i+1}. Score: ${sug.quality_score}/10 (${sug.verdict})`);
      console.log(`     "${original.text.substring(0, 100)}..."`);
    }
  });

  console.log(`\n⚠️  SUGGESTIONS NEEDING REFINEMENT (Lowest Scoring):`);
  const lowSuggestions = allValidations
    .filter(v => v.verdict === 'needs_work')
    .sort((a, b) => a.quality_score - b.quality_score);

  lowSuggestions.forEach((sug, i) => {
    const original = PHASE_17_SUGGESTIONS.excerpt_1.find(s => s.id === sug.suggestion_id) ||
                     PHASE_17_SUGGESTIONS.excerpt_2.find(s => s.id === sug.suggestion_id) ||
                     PHASE_17_SUGGESTIONS.excerpt_3.find(s => s.id === sug.suggestion_id);

    if (original) {
      console.log(`\n  ${i+1}. Score: ${sug.quality_score}/10`);
      console.log(`     Key Issues: ${sug.issues.slice(0, 2).join('; ')}`);
      console.log(`     First Improvement: ${sug.improvements[0]}`);
    }
  });

  console.log('\n\n✅ Complete pipeline test finished!');
  console.log(`   Phase 17 is generating ${goodCount + excellentCount}/${allValidations.length} high-quality suggestions`);
  console.log(`   Phase 18 successfully identifies and provides feedback for weaker suggestions`);
}

// Run test
if (import.meta.main) {
  testCompletePipeline();
}
