// ============================================================================
// ITERATION LEDGER APPEND-ONLY INVARIANT — property test (D-1.14)
// ============================================================================
// Spec: docs/pipeline-evolution/04-pipeline-architecture/L5/L5_IMPLEMENTATION_PLAN.md
//   §D-1.14 — "Property test asserting that across any sequence of iteration
//   commits, no entry in iterationLedger.iterations[] or
//   iterationLedger.taughtMoves[] is ever overwritten or removed (only
//   appended). Mutation of an existing entry via the public API throws."
//
// ─── Foundation invariant being protected ──────────────────────────────
//
// `iterationLedger.iterations[]` and `iterationLedger.taughtMoves[]` are the
// audit-trail spine of the iteration loop. Every entry, once committed, is
// the durable record of what the system did — taughtMoves carry the
// non-repetition contract (D-1.6 priorAnnotations builder reads them);
// iterations[] carries the historical iteration-commit shape (D-1.8
// priorEssayText resolution reads iterations[currentIteration - 2].snapshotText).
//
// Both arrays are committed at exactly one site: analysisOrchestrator.ts's
// `commitIterationRecord` (search for `iterations.push(record)` and
// `taughtMoves.push(...flushedMoves)`). The public mutators in
// essayProfileManager.ts (incrementIteration, appendCarryForwardDecision,
// pruneRecentDecisions) MUST NOT touch these arrays — pruning happens on
// recentDecisions[] only, by spec.
//
// ─── What this test asserts ────────────────────────────────────────────
//
// Property 1: across 100 random iteration commits, every prior entry in
// both arrays is byte-identical to its pre-commit snapshot.
//
// Property 2: length monotonicity — both arrays grow, never shrink.
//
// Property 3: public-API immutability — calling every public ledger
// mutator on a seeded ledger leaves iterations[] and taughtMoves[] entries
// byte-identical (negative-space proof that no public API touches them).
//
// Property 4: D-1.13 wire-up gap closure — for every committed TaughtMove,
// the id generated by generateTaughtMoveId(sourceAnnotation, iteration)
// equals the id appended to iterationLedger.taughtMoves[]. Proves the
// pure-function id contract survives the buffer→flush→ledger pipeline,
// which D-1.13's pure-function property test alone cannot prove.
//
// ─── Future-maintainer guard ───────────────────────────────────────────
//
// If you add a new public API in essayProfileManager.ts that touches
// `iterations[]` or `taughtMoves[]` (e.g., a hypothetical setSnapshotText
// or replaceTaughtMove), Property 3 below MUST be extended with a call
// site exercising the new mutator. Failure to do so means the new API
// could violate the append-only invariant and this test wouldn't catch
// it. The dead-wire pattern this property is designed to prevent.
//
// ─── Out of scope (deliberately, per "complex but not overengineered") ─
//
// - Concurrency / multi-process append safety: no concurrent committers
//   exist by design (single orchestrator instance per essay session).
// - Persistence-layer append-only (checkpoint store immutability): that's
//   the checkpoint store's contract, tested separately.
// - Symbol-keyed caches / time-independence: the SUT is a synchronous
//   array.push; no internal state.
//
// ─── Known future-deliberate divergence (round-3 audit Finding 6) ─────
//
// The spec contains an internal tension this test will surface when D-1.6
// (landing detector) lands:
//   - L5_IMPLEMENTATION_PLAN.md §D-1.14 line 743: "Mutation of an existing
//     entry via the public API throws."
//   - L5_ITERATION_LOOP_DESIGN.md §7.2 line 499: "The `landing` field is
//     null at delivery, populated by the landing detector on the *next*
//     iteration."
//   - L5_ITERATION_LOOP_DESIGN.md §7.5 step 3b: "Persist back to
//     taughtMoves[move].landing."
//
// Property 1 will FAIL when D-1.6 mutates `taughtMoves[i].landing` post-
// commit. That failure is INTENTIONAL — the test is forcing the
// inevitable spec-amendment conversation. Resolution options for that
// future commit:
//   (a) Carve out `landing` field as the one allowed mutation; amend
//       D-1.14 spec to say "no mutation EXCEPT taughtMoves[i].landing"
//       and update Property 1's deep-equal to mask the landing field.
//   (b) Restructure landing as a parallel `landingHistory[]` array
//       indexed by move id; keep taughtMoves[] strictly append-only.
// Either path requires Tue's ratification BEFORE D-1.6 lands. Today the
// invariant holds because no producer mutates landing yet.
//
// Seed convention: deterministic LCG seeded with 0xD1140002 (constant; no
// semantic meaning beyond reproducibility on CI). Same convention as D-1.13.

import { describe, it, expect } from 'vitest';

import {
  EssayProfileCoordinator,
  incrementIteration,
  appendCarryForwardDecision,
  pruneRecentDecisions,
} from '../../src/services/essayIntelligence/profileManager/essayProfileManager';
import { InMemoryCheckpointStore } from '../../src/services/essayIntelligence/profileManager/checkpointStore';
import {
  generateTaughtMoveId,
  l5AnnotationToTaughtMove,
} from '../../src/services/essayIntelligence/analysis/taughtMoveBuilder';
import type { L5Annotation } from '../../src/services/essayIntelligence/analysis/deepAnnotationService';
import type {
  EssayProfile,
  IterationRecord,
  TaughtMove,
  CarryForwardDecision,
} from '../../src/services/essayIntelligence/profileTypes';

// ─── Deterministic RNG (LCG, Numerical Recipes constants) ─────────────

const SEED_CONSTANT = 0xd1140002;

function makeLcg(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}

const rand = makeLcg(SEED_CONSTANT);

function randInt(min: number, max: number): number {
  // Inclusive min, exclusive max.
  return Math.floor(rand() * (max - min)) + min;
}

function randString(prefix: string): string {
  const tailLen = randInt(3, 10);
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let tail = '';
  for (let i = 0; i < tailLen; i++) {
    tail += alphabet[Math.floor(rand() * alphabet.length)];
  }
  return `${prefix}-${tail}`;
}

// ─── Fixture builders ─────────────────────────────────────────────────

function makeCoordinator(): EssayProfileCoordinator {
  const essayText = 'P0 first paragraph.\n\nP1 second paragraph.';
  const paragraphs = essayText.split(/\n\s*\n/).filter((p) => p.trim().length > 0);
  return EssayProfileCoordinator.createNew({
    essayId: 'd114-test-essay',
    essayText,
    paragraphTexts: paragraphs,
    sentenceTexts: paragraphs.map((p) => [p]),
    metadata: { essayType: 'common_app', wordCount: essayText.split(/\s+/).length },
    checkpointStore: new InMemoryCheckpointStore(),
  });
}

function makeRecord(iteration: number): IterationRecord {
  return {
    iteration,
    triggeredBy: iteration === 1 ? 'first_pass' : 'edit',
    carryForwardSummary: { carried: [], rederived: [], refreshed: [] },
    costBreakdown: {},
    comprehensiveBaselineCost: 0,
    carryForwardSavings: 0,
    escalationLevel: 0,
    rationale: `iter ${iteration} ${randString('rationale')}`,
    startedAt: '2026-04-29T00:00:00.000Z',
    finishedAt: '2026-04-29T00:00:01.000Z',
    snapshotText: `iter ${iteration} snapshot ${randString('text')}`,
  };
}

function makeRandomAnnotation(idOverride?: string): L5Annotation {
  return {
    id: idOverride ?? randString('A'),
    location: {
      paragraphIndex: randInt(0, 12),
      sentenceIndex: rand() > 0.5 ? randInt(0, 6) : null,
      spanText: rand() > 0.5 ? randString('span') : null,
    },
    type: 'growth',
    teachingIntent: randString('intent'),
    teachingMode: (['awareness', 'consequence', 'connection', 'action'] as const)[randInt(0, 4)],
    content: randString('content'),
    teachingRationale: randString('rationale'),
    northStarConnection: randString('northstar'),
    stakes: rand() > 0.3 ? randString('stakes') : null,
    priority: randInt(1, 6),
    phase: 'craft',
    rewriteExample: null,
    wordEconomyCut: null,
    antiPatternExample: null,
    transferablePrinciple: null,
    confidence: rand(),
    crossParagraphRefs: [],
    capacityBuildingNote: null,
  };
}

// Mirrors commitIterationRecord's mutation pattern at analysisOrchestrator.ts:2110-2112.
// We test the invariant on the EXACT mutation shape the orchestrator uses;
// the orchestrator's wider context (telemetry buffer drain, checkpoint
// persistence, prune step) is out of scope for the append-only invariant.
function commitIterationDirectly(
  profile: EssayProfile,
  record: IterationRecord,
  movesToAppend: TaughtMove[],
): void {
  profile.iterationLedger.iterations.push(record);
  if (movesToAppend.length > 0) {
    profile.iterationLedger.taughtMoves.push(...movesToAppend);
  }
}

const N_ITERATIONS = 100;

// ─── Properties ────────────────────────────────────────────────────────

describe('D-1.14 — IterationLedger append-only invariant (100 iteration commits)', () => {
  it('Property 1: prefix invariance — every prior entry is byte-identical after each commit', () => {
    const coord = makeCoordinator();
    const profile = coord.getProfile() as EssayProfile;

    for (let i = 1; i <= N_ITERATIONS; i++) {
      // Snapshot pre-commit state via JSON deep clone (catches reference-
      // identity gotchas; subsequent mutations on the live arrays cannot
      // affect the snapshot).
      const priorIterationsSnapshot = JSON.parse(
        JSON.stringify(profile.iterationLedger.iterations),
      ) as IterationRecord[];
      const priorTaughtMovesSnapshot = JSON.parse(
        JSON.stringify(profile.iterationLedger.taughtMoves),
      ) as TaughtMove[];

      // Commit a new iteration with 0..5 random taughtMoves.
      incrementIteration(profile, i === 1 ? 'first_pass' : 'edit');
      const movesThisIter: TaughtMove[] = [];
      const moveCount = randInt(0, 6);
      for (let m = 0; m < moveCount; m++) {
        movesThisIter.push(l5AnnotationToTaughtMove(makeRandomAnnotation(), i));
      }
      commitIterationDirectly(profile, makeRecord(i), movesThisIter);

      // Prefix invariance: the first priorIterationsSnapshot.length entries
      // of the post-commit array must equal the pre-commit snapshot,
      // entry-by-entry.
      const postIterations = profile.iterationLedger.iterations;
      expect(
        postIterations.slice(0, priorIterationsSnapshot.length),
        `iter ${i}: iterations[] prefix must equal pre-commit snapshot`,
      ).toEqual(priorIterationsSnapshot);

      const postMoves = profile.iterationLedger.taughtMoves;
      expect(
        postMoves.slice(0, priorTaughtMovesSnapshot.length),
        `iter ${i}: taughtMoves[] prefix must equal pre-commit snapshot`,
      ).toEqual(priorTaughtMovesSnapshot);

      // Length grew by exactly 1 (iterations) and exactly moveCount (taughtMoves).
      expect(postIterations.length).toBe(priorIterationsSnapshot.length + 1);
      expect(postMoves.length).toBe(priorTaughtMovesSnapshot.length + moveCount);
    }
  });

  it('Property 2: length monotonicity — both arrays grow, never shrink, across the 100-commit sequence', () => {
    const coord = makeCoordinator();
    const profile = coord.getProfile() as EssayProfile;

    let prevIterationsLen = profile.iterationLedger.iterations.length;
    let prevMovesLen = profile.iterationLedger.taughtMoves.length;

    for (let i = 1; i <= N_ITERATIONS; i++) {
      incrementIteration(profile, i === 1 ? 'first_pass' : 'edit');
      const moveCount = randInt(0, 6);
      const moves: TaughtMove[] = [];
      for (let m = 0; m < moveCount; m++) {
        moves.push(l5AnnotationToTaughtMove(makeRandomAnnotation(), i));
      }
      commitIterationDirectly(profile, makeRecord(i), moves);

      const newIterationsLen = profile.iterationLedger.iterations.length;
      const newMovesLen = profile.iterationLedger.taughtMoves.length;

      expect(newIterationsLen, `iter ${i}: iterations.length must not shrink`).toBeGreaterThanOrEqual(prevIterationsLen);
      expect(newMovesLen, `iter ${i}: taughtMoves.length must not shrink`).toBeGreaterThanOrEqual(prevMovesLen);

      prevIterationsLen = newIterationsLen;
      prevMovesLen = newMovesLen;
    }
  });

  it('Property 3: public-API immutability — incrementIteration, appendCarryForwardDecision, pruneRecentDecisions do not mutate iterations[] or taughtMoves[] entries', () => {
    // Build a seeded ledger with K=10 prior iterations + M=20 prior taughtMoves.
    const coord = makeCoordinator();
    const profile = coord.getProfile() as EssayProfile;
    for (let i = 1; i <= 10; i++) {
      incrementIteration(profile, i === 1 ? 'first_pass' : 'edit');
      const moves: TaughtMove[] = [];
      for (let m = 0; m < 2; m++) {
        moves.push(l5AnnotationToTaughtMove(makeRandomAnnotation(), i));
      }
      commitIterationDirectly(profile, makeRecord(i), moves);
    }
    expect(profile.iterationLedger.iterations.length).toBe(10);
    expect(profile.iterationLedger.taughtMoves.length).toBe(20);

    // Snapshot the seeded ledger entries.
    const seededIterations = JSON.parse(
      JSON.stringify(profile.iterationLedger.iterations),
    ) as IterationRecord[];
    const seededMoves = JSON.parse(
      JSON.stringify(profile.iterationLedger.taughtMoves),
    ) as TaughtMove[];

    // Call each public mutator. After each, assert iterations[] and
    // taughtMoves[] entries are byte-identical to the seeded snapshot.

    // (a) incrementIteration: mutates currentIteration only.
    incrementIteration(profile, 'edit');
    expect(profile.iterationLedger.iterations).toEqual(seededIterations);
    expect(profile.iterationLedger.taughtMoves).toEqual(seededMoves);

    // (b) appendCarryForwardDecision: mutates recentDecisions[] only.
    const decision: CarryForwardDecision = {
      iteration: profile.iterationLedger.currentIteration,
      itemKey: 'test-item-key',
      decision: 'carry',
      rationale: 'public-API immutability test',
      arbitrationMechanism: 'validity_test',
      costSavedIfCarry: 0,
      costSpentIfRederive: 0,
    };
    appendCarryForwardDecision(profile, decision);
    expect(profile.iterationLedger.iterations).toEqual(seededIterations);
    expect(profile.iterationLedger.taughtMoves).toEqual(seededMoves);

    // (c) pruneRecentDecisions: mutates recentDecisions[] only (specifically removes from it).
    pruneRecentDecisions(profile, 5);
    expect(profile.iterationLedger.iterations).toEqual(seededIterations);
    expect(profile.iterationLedger.taughtMoves).toEqual(seededMoves);
  });

  // Property 4 closes the D-1.13 deferred wire-up gap. D-1.13's pure-function
  // property test proves generateTaughtMoveId is deterministic, but it does
  // NOT prove that a TaughtMove built via l5AnnotationToTaughtMove(ann, iter)
  // and then committed through the buffer→flush→ledger pipeline lands in
  // iterationLedger.taughtMoves[] with its id intact. This property closes
  // that gap by tracking source annotations through the full commit and
  // asserting the id round-trip.
  it('Property 4: D-1.13 wire-up — every committed TaughtMove.id equals generateTaughtMoveId(sourceAnnotation, iteration)', () => {
    const coord = makeCoordinator();
    const profile = coord.getProfile() as EssayProfile;

    // Track source annotations + iteration at commit time so we can
    // re-derive the expected id post-commit.
    const sourceMap: Array<{ annotation: L5Annotation; iteration: number; expectedId: string }> = [];

    for (let i = 1; i <= N_ITERATIONS; i++) {
      incrementIteration(profile, i === 1 ? 'first_pass' : 'edit');
      const moveCount = randInt(0, 4);
      const moves: TaughtMove[] = [];
      for (let m = 0; m < moveCount; m++) {
        const annotation = makeRandomAnnotation();
        const move = l5AnnotationToTaughtMove(annotation, i);
        moves.push(move);
        sourceMap.push({ annotation, iteration: i, expectedId: move.id });
      }
      commitIterationDirectly(profile, makeRecord(i), moves);
    }

    // For every committed TaughtMove, verify its id matches the
    // re-derived id from the source annotation. This catches:
    //   - id mutation between l5AnnotationToTaughtMove and ledger commit
    //   - re-id'ing logic accidentally introduced into the buffer/flush path
    //   - any future regression where the appended move's id diverges
    //     from what the pure function would produce.
    expect(profile.iterationLedger.taughtMoves.length).toBe(sourceMap.length);
    for (let i = 0; i < sourceMap.length; i++) {
      const { annotation, iteration, expectedId } = sourceMap[i];
      const committedMove = profile.iterationLedger.taughtMoves[i];

      // Re-derive expected id from source — proves the pure function is
      // still the producer.
      const rederivedId = generateTaughtMoveId(annotation, iteration);
      expect(rederivedId).toBe(expectedId);

      // Committed id matches the pure-function output — proves the wire
      // doesn't mutate the id.
      expect(
        committedMove.id,
        `move ${i}: committed id must match generateTaughtMoveId(annotation, ${iteration})`,
      ).toBe(rederivedId);
    }
  });
});
