// ============================================================================
// ITERATION LEDGER APPEND-ONLY INVARIANT — property test (D-1.14)
// ============================================================================
// Spec: docs/pipeline-evolution/04-pipeline-architecture/L5/L5_IMPLEMENTATION_PLAN.md
//   §D-1.14 — "Property test asserting that across any sequence of iteration
//   commits, no entry in iterationLedger.iterations[] or
//   iterationLedger.taughtMoves[] is ever overwritten or removed (only
//   appended). Mutation of an existing entry via the public API throws."
//
// ─── Foundation invariant being protected ──────────────────────────────
//
// `iterationLedger.iterations[]` and `iterationLedger.taughtMoves[]` are the
// audit-trail spine of the iteration loop. Every entry, once committed, is
// the durable record of what the system did — taughtMoves carry the
// non-repetition contract (D-1.6 priorAnnotations builder reads them);
// iterations[] carries the historical iteration-commit shape (D-1.8
// priorEssayText resolution reads iterations[currentIteration - 2].snapshotText).
//
// Both arrays are committed at exactly one site: analysisOrchestrator.ts's
// `commitIterationRecord` (search for `iterations.push(record)` and
// `taughtMoves.push(...flushedMoves)`). The public mutators in
// essayProfileManager.ts (incrementIteration, appendCarryForwardDecision,
// pruneRecentDecisions) MUST NOT touch these arrays — pruning happens on
// recentDecisions[] only, by spec.
//
// ─── What this test asserts ────────────────────────────────────────────
//
// Property 1: across 100 random iteration commits, every prior entry in
// both arrays is byte-identical to its pre-commit snapshot.
//
// Property 2: length monotonicity — both arrays grow, never shrink.
//
// Property 3: public-API immutability — calling every public ledger
// mutator on a seeded ledger leaves iterations[] and taughtMoves[] entries
// byte-identical (negative-space proof that no public API touches them).
//
// Property 4: D-1.13 wire-up gap closure — for every committed TaughtMove,
// the id generated by generateTaughtMoveId(sourceAnnotation, iteration)
// equals the id appended to iterationLedger.taughtMoves[]. Proves the
// pure-function id contract survives the buffer→flush→ledger pipeline,
// which D-1.13's pure-function property test alone cannot prove.
//
// ─── Future-maintainer guard ───────────────────────────────────────────
//
// If you add a new public API in essayProfileManager.ts that touches
// `iterations[]` or `taughtMoves[]` (e.g., a hypothetical setSnapshotText
// or replaceTaughtMove), Property 3 below MUST be extended with a call
// site exercising the new mutator. Failure to do so means the new API
// could violate the append-only invariant and this test wouldn't catch
// it. The dead-wire pattern this property is designed to prevent.
//
// ─── Out of scope (deliberately, per "complex but not overengineered") ─
//
// - Concurrency / multi-process append safety: no concurrent committers
//   exist by design (single orchestrator instance per essay session).
// - Persistence-layer append-only (checkpoint store immutability): that's
//   the checkpoint store's contract, tested separately.
// - Symbol-keyed caches / time-independence: the SUT is a synchronous
//   array.push; no internal state.
//
// ─── Spec-amendment ratification — D-1.15.0 (2026-04-29) ──────────────
//
// The spec contained an internal tension this test was originally written
// to surface:
//   - L5_IMPLEMENTATION_PLAN.md §D-1.14: "Mutation of an existing entry
//     via the public API throws."
//   - L5_ITERATION_LOOP_DESIGN.md §7.2: "The `landing` field is null at
//     delivery, populated by the landing detector on the *next* iteration."
//   - L5_ITERATION_LOOP_DESIGN.md §7.5 step 3b: "Persist back to
//     taughtMoves[move].landing."
//
// Resolution (option (a), ratified by Tue 2026-04-29 before D-1.15 lands):
//   The `landing` field is carved out of the append-only invariant as the
//   ONE permitted post-commit mutation, narrowly defined as:
//
//     - Allowed: a single transition `landing: undefined → populated`
//       performed by the landing detector on the iteration after teaching.
//     - Disallowed: any subsequent rewrite of an already-populated landing
//       (no `populated → mutated`, no `populated → undefined`).
//     - Disallowed: any other field mutation on a committed TaughtMove
//       (`id`, `annotationId`, `location`, `taughtAtIteration`,
//       `teachingMode`, `contentSummary`, `stakesSnapshot`, `findingId`,
//       `deepenedBy`, `supersededBy` all stay byte-identical post-commit).
//
//   IterationRecord remains FULLY append-only — no field carve-outs.
//
//   Rationale: landing IS observed asynchronously, after teaching. A
//   sibling `taughtMoveLandings: Record<TaughtMoveId, Landing>` structure
//   (option (b)) would have been architecturally cleaner but cascades
//   into D-1.6/D-1.8/D-1.10/D-1.12 consumer changes. The carve-out keeps
//   the schema honest about what already happens semantically: a one-shot
//   write from undefined to populated, never re-mutated.
//
// Property 1 below uses `assertTaughtMoveAppendOnlyWithLandingCarveOut`
// which encodes this exception precisely. The test was extended (not
// loosened) — `populated → mutated` and `populated → undefined` are now
// active assertions.
//
// If you ever consider widening the carve-out (e.g., "let `deepenedBy`
// also be post-commit-mutable"), STOP and surface to product/spec
// review. Each new carve-out is precedent that makes the next one easier
// — that's the slippery slope this comment block is designed to halt.
//
// Seed convention: deterministic LCG seeded with 0xD1140002 (constant; no
// semantic meaning beyond reproducibility on CI). Same convention as D-1.13.

import { describe, it, expect } from 'vitest';

import {
  EssayProfileCoordinator,
  incrementIteration,
  appendCarryForwardDecision,
  pruneRecentDecisions,
} from '../../src/services/essayIntelligence/profileManager/essayProfileManager';
import { InMemoryCheckpointStore } from '../../src/services/essayIntelligence/profileManager/checkpointStore';
import {
  generateTaughtMoveId,
  l5AnnotationToTaughtMove,
} from '../../src/services/essayIntelligence/analysis/taughtMoveBuilder';
import type { L5Annotation } from '../../src/services/essayIntelligence/analysis/deepAnnotationService';
import type {
  EssayProfile,
  IterationRecord,
  TaughtMove,
  CarryForwardDecision,
} from '../../src/services/essayIntelligence/profileTypes';

// ─── Deterministic RNG (LCG, Numerical Recipes constants) ─────────────

const SEED_CONSTANT = 0xd1140002;

function makeLcg(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}

const rand = makeLcg(SEED_CONSTANT);

function randInt(min: number, max: number): number {
  // Inclusive min, exclusive max.
  return Math.floor(rand() * (max - min)) + min;
}

function randString(prefix: string): string {
  const tailLen = randInt(3, 10);
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let tail = '';
  for (let i = 0; i < tailLen; i++) {
    tail += alphabet[Math.floor(rand() * alphabet.length)];
  }
  return `${prefix}-${tail}`;
}

// ─── Fixture builders ─────────────────────────────────────────────────

function makeCoordinator(): EssayProfileCoordinator {
  const essayText = 'P0 first paragraph.\n\nP1 second paragraph.';
  const paragraphs = essayText.split(/\n\s*\n/).filter((p) => p.trim().length > 0);
  return EssayProfileCoordinator.createNew({
    essayId: 'd114-test-essay',
    essayText,
    paragraphTexts: paragraphs,
    sentenceTexts: paragraphs.map((p) => [p]),
    metadata: { essayType: 'common_app', wordCount: essayText.split(/\s+/).length },
    checkpointStore: new InMemoryCheckpointStore(),
  });
}

function makeRecord(iteration: number): IterationRecord {
  return {
    iteration,
    triggeredBy: iteration === 1 ? 'first_pass' : 'edit',
    carryForwardSummary: { carried: [], rederived: [], refreshed: [] },
    costBreakdown: {},
    comprehensiveBaselineCost: 0,
    carryForwardSavings: 0,
    escalationLevel: 0,
    rationale: `iter ${iteration} ${randString('rationale')}`,
    startedAt: '2026-04-29T00:00:00.000Z',
    finishedAt: '2026-04-29T00:00:01.000Z',
    snapshotText: `iter ${iteration} snapshot ${randString('text')}`,
  };
}

function makeRandomAnnotation(idOverride?: string): L5Annotation {
  return {
    id: idOverride ?? randString('A'),
    location: {
      paragraphIndex: randInt(0, 12),
      sentenceIndex: rand() > 0.5 ? randInt(0, 6) : null,
      spanText: rand() > 0.5 ? randString('span') : null,
    },
    type: 'growth',
    teachingIntent: randString('intent'),
    teachingMode: (['awareness', 'consequence', 'connection', 'action'] as const)[randInt(0, 4)],
    content: randString('content'),
    teachingRationale: randString('rationale'),
    northStarConnection: randString('northstar'),
    stakes: rand() > 0.3 ? randString('stakes') : null,
    priority: randInt(1, 6),
    phase: 'craft',
    rewriteExample: null,
    wordEconomyCut: null,
    antiPatternExample: null,
    transferablePrinciple: null,
    confidence: rand(),
    crossParagraphRefs: [],
    capacityBuildingNote: null,
  };
}

// Mirrors commitIterationRecord's mutation pattern at analysisOrchestrator.ts:2110-2112.
// We test the invariant on the EXACT mutation shape the orchestrator uses;
// the orchestrator's wider context (telemetry buffer drain, checkpoint
// persistence, prune step) is out of scope for the append-only invariant.
function commitIterationDirectly(
  profile: EssayProfile,
  record: IterationRecord,
  movesToAppend: TaughtMove[],
): void {
  profile.iterationLedger.iterations.push(record);
  if (movesToAppend.length > 0) {
    profile.iterationLedger.taughtMoves.push(...movesToAppend);
  }
}

// Encodes the D-1.15.0 landing carve-out (see comment block at the top of
// this file for ratification context). All non-landing fields must be
// byte-identical between prior and post snapshots. Landing has a narrow,
// one-shot allowed transition: `undefined → populated`. Any other landing
// mutation (populated → mutated, populated → undefined) FAILS the assertion.
//
// Why a custom helper instead of a Vitest matcher: the carve-out is a
// LOCAL, NAMED exception to the broader append-only invariant. A custom
// matcher would be reusable but would also be tempting to apply to the
// IterationRecord array (which has NO carve-outs). Keeping this helper
// scoped to taughtMoves preserves the asymmetry on purpose.
function assertTaughtMoveAppendOnlyWithLandingCarveOut(
  prior: TaughtMove[],
  post: TaughtMove[],
  context: string,
): void {
  expect(
    post.length,
    `${context}: post.length must be ≥ prior.length (append-only)`,
  ).toBeGreaterThanOrEqual(prior.length);

  for (let i = 0; i < prior.length; i++) {
    const p = prior[i];
    const q = post[i];

    // All non-landing fields must be byte-identical.
    const { landing: priorLanding, ...priorRest } = p;
    const { landing: postLanding, ...postRest } = q;
    expect(
      postRest,
      `${context}: move[${i}] non-landing fields must be byte-identical (id=${p.id})`,
    ).toEqual(priorRest);

    // Landing carve-out enforcement.
    if (priorLanding === undefined) {
      // Permitted: undefined → undefined (still no detection) OR
      //            undefined → populated (the one-shot detection write).
      // Either is legal; no further assertion needed.
    } else {
      // Once populated, landing must remain byte-identical. Catches:
      //   - re-detection rewriting an existing landing
      //   - landing being un-populated back to undefined
      //   - any field within landing being mutated
      expect(
        postLanding,
        `${context}: move[${i}] landing was populated (status=${priorLanding.status}); ` +
          `subsequent mutation forbidden — only undefined → populated is permitted exactly once.`,
      ).toEqual(priorLanding);
    }
  }
}

const N_ITERATIONS = 100;

// ─── Properties ────────────────────────────────────────────────────────

describe('D-1.14 — IterationLedger append-only invariant (100 iteration commits)', () => {
  it('Property 1: prefix invariance — every prior entry is byte-identical after each commit', () => {
    const coord = makeCoordinator();
    const profile = coord.getProfile() as EssayProfile;

    for (let i = 1; i <= N_ITERATIONS; i++) {
      // Snapshot pre-commit state via JSON deep clone (catches reference-
      // identity gotchas; subsequent mutations on the live arrays cannot
      // affect the snapshot).
      const priorIterationsSnapshot = JSON.parse(
        JSON.stringify(profile.iterationLedger.iterations),
      ) as IterationRecord[];
      const priorTaughtMovesSnapshot = JSON.parse(
        JSON.stringify(profile.iterationLedger.taughtMoves),
      ) as TaughtMove[];

      // Commit a new iteration with 0..5 random taughtMoves.
      incrementIteration(profile, i === 1 ? 'first_pass' : 'edit');
      const movesThisIter: TaughtMove[] = [];
      const moveCount = randInt(0, 6);
      for (let m = 0; m < moveCount; m++) {
        movesThisIter.push(l5AnnotationToTaughtMove(makeRandomAnnotation(), i));
      }
      commitIterationDirectly(profile, makeRecord(i), movesThisIter);

      // Prefix invariance: the first priorIterationsSnapshot.length entries
      // of the post-commit array must equal the pre-commit snapshot,
      // entry-by-entry.
      //
      // IterationRecord array uses strict toEqual — no carve-outs.
      // TaughtMove array uses the D-1.15.0 landing carve-out helper, which
      // permits exactly one transition (undefined → populated) and forbids
      // every other mutation. See the spec-amendment block at the top of
      // this file for ratification context.
      const postIterations = profile.iterationLedger.iterations;
      expect(
        postIterations.slice(0, priorIterationsSnapshot.length),
        `iter ${i}: iterations[] prefix must equal pre-commit snapshot`,
      ).toEqual(priorIterationsSnapshot);

      const postMoves = profile.iterationLedger.taughtMoves;
      // Pass the full post array — the helper iterates only the first
      // priorTaughtMovesSnapshot.length entries (the prefix invariant
      // window) and asserts length monotonicity for the rest.
      assertTaughtMoveAppendOnlyWithLandingCarveOut(
        priorTaughtMovesSnapshot,
        postMoves,
        `iter ${i}: taughtMoves[] prefix`,
      );

      // Length grew by exactly 1 (iterations) and exactly moveCount (taughtMoves).
      expect(postIterations.length).toBe(priorIterationsSnapshot.length + 1);
      expect(postMoves.length).toBe(priorTaughtMovesSnapshot.length + moveCount);
    }
  });

  it('Property 2: length monotonicity — both arrays grow, never shrink, across the 100-commit sequence', () => {
    const coord = makeCoordinator();
    const profile = coord.getProfile() as EssayProfile;

    let prevIterationsLen = profile.iterationLedger.iterations.length;
    let prevMovesLen = profile.iterationLedger.taughtMoves.length;

    for (let i = 1; i <= N_ITERATIONS; i++) {
      incrementIteration(profile, i === 1 ? 'first_pass' : 'edit');
      const moveCount = randInt(0, 6);
      const moves: TaughtMove[] = [];
      for (let m = 0; m < moveCount; m++) {
        moves.push(l5AnnotationToTaughtMove(makeRandomAnnotation(), i));
      }
      commitIterationDirectly(profile, makeRecord(i), moves);

      const newIterationsLen = profile.iterationLedger.iterations.length;
      const newMovesLen = profile.iterationLedger.taughtMoves.length;

      expect(newIterationsLen, `iter ${i}: iterations.length must not shrink`).toBeGreaterThanOrEqual(prevIterationsLen);
      expect(newMovesLen, `iter ${i}: taughtMoves.length must not shrink`).toBeGreaterThanOrEqual(prevMovesLen);

      prevIterationsLen = newIterationsLen;
      prevMovesLen = newMovesLen;
    }
  });

  it('Property 3: public-API immutability — incrementIteration, appendCarryForwardDecision, pruneRecentDecisions do not mutate iterations[] or taughtMoves[] entries', () => {
    // Build a seeded ledger with K=10 prior iterations + M=20 prior taughtMoves.
    const coord = makeCoordinator();
    const profile = coord.getProfile() as EssayProfile;
    for (let i = 1; i <= 10; i++) {
      incrementIteration(profile, i === 1 ? 'first_pass' : 'edit');
      const moves: TaughtMove[] = [];
      for (let m = 0; m < 2; m++) {
        moves.push(l5AnnotationToTaughtMove(makeRandomAnnotation(), i));
      }
      commitIterationDirectly(profile, makeRecord(i), moves);
    }
    expect(profile.iterationLedger.iterations.length).toBe(10);
    expect(profile.iterationLedger.taughtMoves.length).toBe(20);

    // Snapshot the seeded ledger entries.
    const seededIterations = JSON.parse(
      JSON.stringify(profile.iterationLedger.iterations),
    ) as IterationRecord[];
    const seededMoves = JSON.parse(
      JSON.stringify(profile.iterationLedger.taughtMoves),
    ) as TaughtMove[];

    // Call each public mutator. After each, assert iterations[] and
    // taughtMoves[] entries are byte-identical to the seeded snapshot.

    // Property 3 uses STRICT toEqual on taughtMoves (not the carve-out
    // helper) on purpose: the public-API mutators tested here are NOT the
    // landing detector. They have no business touching the landing field
    // even within the carve-out's narrow allowance. If incrementIteration
    // or appendCarryForwardDecision ever populated landing, that would be
    // a real bug, and this test must fail on it.

    // (a) incrementIteration: mutates currentIteration only.
    incrementIteration(profile, 'edit');
    expect(profile.iterationLedger.iterations).toEqual(seededIterations);
    expect(profile.iterationLedger.taughtMoves).toEqual(seededMoves);

    // (b) appendCarryForwardDecision: mutates recentDecisions[] only.
    const decision: CarryForwardDecision = {
      iteration: profile.iterationLedger.currentIteration,
      itemKey: 'test-item-key',
      decision: 'carry',
      rationale: 'public-API immutability test',
      arbitrationMechanism: 'validity_test',
      costSavedIfCarry: 0,
      costSpentIfRederive: 0,
    };
    appendCarryForwardDecision(profile, decision);
    expect(profile.iterationLedger.iterations).toEqual(seededIterations);
    expect(profile.iterationLedger.taughtMoves).toEqual(seededMoves);

    // (c) pruneRecentDecisions: mutates recentDecisions[] only (specifically removes from it).
    pruneRecentDecisions(profile, 5);
    expect(profile.iterationLedger.iterations).toEqual(seededIterations);
    expect(profile.iterationLedger.taughtMoves).toEqual(seededMoves);
  });

  // Property 4 closes the D-1.13 deferred wire-up gap. D-1.13's pure-function
  // property test proves generateTaughtMoveId is deterministic, but it does
  // NOT prove that a TaughtMove built via l5AnnotationToTaughtMove(ann, iter)
  // and then committed through the buffer→flush→ledger pipeline lands in
  // iterationLedger.taughtMoves[] with its id intact. This property closes
  // that gap by tracking source annotations through the full commit and
  // asserting the id round-trip.
  it('Property 4: D-1.13 wire-up — every committed TaughtMove.id equals generateTaughtMoveId(sourceAnnotation, iteration)', () => {
    const coord = makeCoordinator();
    const profile = coord.getProfile() as EssayProfile;

    // Track source annotations + iteration at commit time so we can
    // re-derive the expected id post-commit.
    const sourceMap: Array<{ annotation: L5Annotation; iteration: number; expectedId: string }> = [];

    for (let i = 1; i <= N_ITERATIONS; i++) {
      incrementIteration(profile, i === 1 ? 'first_pass' : 'edit');
      const moveCount = randInt(0, 4);
      const moves: TaughtMove[] = [];
      for (let m = 0; m < moveCount; m++) {
        const annotation = makeRandomAnnotation();
        const move = l5AnnotationToTaughtMove(annotation, i);
        moves.push(move);
        sourceMap.push({ annotation, iteration: i, expectedId: move.id });
      }
      commitIterationDirectly(profile, makeRecord(i), moves);
    }

    // For every committed TaughtMove, verify its id matches the
    // re-derived id from the source annotation. This catches:
    //   - id mutation between l5AnnotationToTaughtMove and ledger commit
    //   - re-id'ing logic accidentally introduced into the buffer/flush path
    //   - any future regression where the appended move's id diverges
    //     from what the pure function would produce.
    expect(profile.iterationLedger.taughtMoves.length).toBe(sourceMap.length);
    for (let i = 0; i < sourceMap.length; i++) {
      const { annotation, iteration, expectedId } = sourceMap[i];
      const committedMove = profile.iterationLedger.taughtMoves[i];

      // Re-derive expected id from source — proves the pure function is
      // still the producer.
      const rederivedId = generateTaughtMoveId(annotation, iteration);
      expect(rederivedId).toBe(expectedId);

      // Committed id matches the pure-function output — proves the wire
      // doesn't mutate the id.
      expect(
        committedMove.id,
        `move ${i}: committed id must match generateTaughtMoveId(annotation, ${iteration})`,
      ).toBe(rederivedId);
    }
  });

  // Property 5 directly exercises the D-1.15.0 landing carve-out helper.
  // Property 1 uses the helper but only sees the "no detector running yet"
  // path (so the carve-out is dormant). Property 5 hand-crafts before/after
  // snapshots that force each branch:
  //   (a) undefined → undefined: legal (still no detection)
  //   (b) undefined → populated: legal (one-shot detection write)
  //   (c) populated → byte-identical: legal (no re-detection)
  //   (d) populated → mutated: ILLEGAL (helper throws)
  //   (e) populated → undefined: ILLEGAL (helper throws)
  //   (f) non-landing field mutated: ILLEGAL (helper throws)
  //
  // Why this property exists: D-1.15 (about to land) WILL exercise the
  // carve-out's permitted transition (b). If a future change ever
  // accidentally widens the carve-out (e.g., allows re-detection rewrites),
  // Property 1 alone won't catch it because random fixture data rarely
  // hits the populated-landing path. This property is the targeted
  // safety net.
  it('Property 5: D-1.15.0 carve-out helper enforces narrow landing semantics (allowed: undefined→populated; forbidden: anything else)', () => {
    const baseAnnotation = makeRandomAnnotation('A-property5-anchor');
    const moveNoLanding: TaughtMove = l5AnnotationToTaughtMove(baseAnnotation, 1);
    const populatedLanding: NonNullable<TaughtMove['landing']> = {
      status: 'addressed',
      detectedAtIteration: 2,
      confidence: 0.85,
      reasoning: 'student edit substantively addressed the move',
      signalsUsed: ['edit_vs_critique'],
    };
    const moveWithLanding: TaughtMove = { ...moveNoLanding, landing: populatedLanding };

    // (a) undefined → undefined: legal.
    expect(() =>
      assertTaughtMoveAppendOnlyWithLandingCarveOut([moveNoLanding], [moveNoLanding], 'case-a'),
    ).not.toThrow();

    // (b) undefined → populated: legal (the one permitted transition).
    expect(() =>
      assertTaughtMoveAppendOnlyWithLandingCarveOut([moveNoLanding], [moveWithLanding], 'case-b'),
    ).not.toThrow();

    // (c) populated → byte-identical: legal.
    expect(() =>
      assertTaughtMoveAppendOnlyWithLandingCarveOut([moveWithLanding], [moveWithLanding], 'case-c'),
    ).not.toThrow();

    // (d) populated → mutated: ILLEGAL.
    const mutatedLanding: TaughtMove = {
      ...moveWithLanding,
      landing: { ...populatedLanding, confidence: 0.95 },
    };
    expect(() =>
      assertTaughtMoveAppendOnlyWithLandingCarveOut([moveWithLanding], [mutatedLanding], 'case-d'),
    ).toThrow();

    // (e) populated → undefined: ILLEGAL.
    expect(() =>
      assertTaughtMoveAppendOnlyWithLandingCarveOut([moveWithLanding], [moveNoLanding], 'case-e'),
    ).toThrow();

    // (f) non-landing field mutated: ILLEGAL (e.g., contentSummary rewritten).
    const contentMutated: TaughtMove = { ...moveNoLanding, contentSummary: 'rewritten content' };
    expect(() =>
      assertTaughtMoveAppendOnlyWithLandingCarveOut([moveNoLanding], [contentMutated], 'case-f'),
    ).toThrow();

    // (g) length monotonicity within helper: post.length < prior.length is ILLEGAL.
    expect(() =>
      assertTaughtMoveAppendOnlyWithLandingCarveOut([moveNoLanding, moveNoLanding], [moveNoLanding], 'case-g'),
    ).toThrow();

    // (h) interaction: length growth + populated-prefix preservation.
    // Closes the R-3 review finding — Property 5 cases (a)-(g) test branches
    // in isolation but none exercise "post is LONGER than prior AND the
    // populated-landing prefix invariant holds". A bug where the helper
    // accidentally short-circuits the prefix loop when `post.length > prior.length`
    // (or skips landing comparison on a populated prefix when growth is detected)
    // would slip past (a)-(g). This case nails the interaction:
    //   - prior = [moveWithLanding] (one entry, populated landing)
    //   - post = [moveWithLanding, moveNoLanding] (two entries, prefix preserved)
    // Legal: prefix is byte-identical, length grew honestly.
    const additionalMove: TaughtMove = l5AnnotationToTaughtMove(
      makeRandomAnnotation('A-property5-h-additional'),
      2,
    );
    expect(() =>
      assertTaughtMoveAppendOnlyWithLandingCarveOut(
        [moveWithLanding],
        [moveWithLanding, additionalMove],
        'case-h-legal',
      ),
    ).not.toThrow();

    // (h-fail) sibling failing variant: prefix's populated landing is mutated
    // WHILE post grows. Helper must still throw — growth in the suffix does
    // not excuse mutation in the prefix.
    const mutatedPrefix: TaughtMove = {
      ...moveWithLanding,
      landing: { ...populatedLanding, status: 'partially_addressed' },
    };
    expect(() =>
      assertTaughtMoveAppendOnlyWithLandingCarveOut(
        [moveWithLanding],
        [mutatedPrefix, additionalMove],
        'case-h-illegal',
      ),
    ).toThrow();
  });
});
