import React from 'react';
import { HoverCard, HoverCardTrigger, HoverCardContent } from '@/components/ui/hover-card';
import { LucideIcon, Rocket, Target, Heart, Sparkles, AlertTriangle } from 'lucide-react';

// Types
export interface KeyTakeaway {
  label: string;
  description: string;
  icon: LucideIcon;
  colorClass: string;
}

export type EvidenceProps = { text: string; details: string[] };
export type RichSegment = string | EvidenceProps;

export interface OverarchingInsight {
  verdict: { spike: RichSegment[]; spine: RichSegment[]; lift: RichSegment[] };
  readinessInContext: RichSegment[];
  storyCoherencePercent: number;
  storyCoherenceLine: RichSegment[];
  impactFootprint: RichSegment[];
  recognitionMix: RichSegment[];
  trajectoryDurability: RichSegment[];
  contextContribution: RichSegment[];
  committeeSoundBite: RichSegment[];
  concludingNarrative: RichSegment[];
}

export interface HolisticSummary {
  overallScore: number;
  tierName: string;
  tierPercentile: string;
  profileSummary: string;
  coreIdentity: KeyTakeaway;
  competitivePosition: KeyTakeaway;
  narrativeTheme: KeyTakeaway;
  biggestDifferentiator: KeyTakeaway;
  criticalGap: KeyTakeaway;
  overarchingInsight?: OverarchingInsight;
}

// Helper Components
const InlineEvidence: React.FC<EvidenceProps> = ({ text, details }) => (
  <HoverCard>
    <HoverCardTrigger asChild>
      <span className="underline decoration-dotted underline-offset-4 cursor-help text-primary/90 hover:text-primary">
        {text}
      </span>
    </HoverCardTrigger>
    <HoverCardContent align="start" className="w-80">
      <div className="text-sm font-semibold mb-1">Evidence</div>
      <ul className="list-disc pl-5 space-y-1 text-sm leading-6">
        {details.map((d, i) => (
          <li key={i} className="text-foreground/90">{d}</li>
        ))}
      </ul>
    </HoverCardContent>
  </HoverCard>
);

export const renderRich = (segments: RichSegment[]) =>
  segments.map((seg, i) =>
    typeof seg === 'string' ? <span key={i}>{seg}</span> : <InlineEvidence key={i} text={seg.text} details={seg.details} />
  );

// IMPORTANT: Hard-coded mock data representing a holistic portfolio analysis
// In production, this would be generated by AI analyzing the user's complete portfolio
// and synthesizing patterns across all dimensions, activities, and achievements
export const MOCK_HOLISTIC_SUMMARY: HolisticSummary = {
  overallScore: 8.2,
  tierName: 'Diamond Achiever',
  tierPercentile: 'Top 15%',
  profileSummary: 'You present as a community-focused STEM leader with demonstrated technical expertise, sustained volunteer commitment, and emerging research capabilities. Your portfolio shows cross-domain versatility, positioning you competitively for Top 20 schools with reach potential for Top 10.',
  coreIdentity: {
    label: 'STEM Leader & Community Catalyst',
    description: 'You consistently combine technical projects with community service, showing you can lead in both contexts.',
    icon: Rocket,
    colorClass: 'border-primary',
  },
  competitivePosition: {
    label: 'Strong T20, Reach for T10',
    description: 'Your profile aligns well with schools ranked 11-20. Stanford/MIT are reaches; schools like Duke/Northwestern are targets.',
    icon: Target,
    colorClass: 'border-purple-500',
  },
  narrativeTheme: {
    label: 'Using Technology to Democratize Access',
    description: 'Your story centers on leveraging technical skills to create opportunities for underserved communities.',
    icon: Heart,
    colorClass: 'border-green-500',
  },
  biggestDifferentiator: {
    label: 'Cross-Domain Leadership (Tech + Community)',
    description: 'Unlike most STEM students focused purely on research, you balance technical depth with genuine community impact.',
    icon: Sparkles,
    colorClass: 'border-orange-500',
  },
  criticalGap: {
    label: 'Need Quantifiable Impact Metrics',
    description: 'Your community activities lack specific numbers (people served, hours, outcomes), making impact hard to assess.',
    icon: AlertTriangle,
    colorClass: 'border-destructive',
  },
  overarchingInsight: {
    verdict: {
      spike: [
        'A distinctive spike in engineering-for-access with real adoption - your ',
        { text: 'tutoring platform', details: ['118 weekly active students last month', 'MOUs with two partner schools', 'Tutor roster grew 6 to 19'] },
        ' consistently serves local schools, and the ',
        { text: 'adaptive controller kits', details: ['18 robotics members using kits', 'Open-source repo: 42 stars, 9 forks'] },
        ' lowered barriers for new participants.'
      ],
      spine: [
        'Your spine is clear: using technology to democratize access - from ',
        { text: 'Title I workshops', details: ['Free cycles for two Title I partners', 'Avg 24 students/session'] },
        ' to mentoring first-time coders via the ',
        { text: 'library program', details: ['Monthly beginner cohorts since Jan 2024', 'Consistent waitlist demand'] },
        '.'
      ],
      lift: [
        'Biggest lift: convert effort into public outcomes. Instead of logging hours, surface a compact metrics layer - a single ',
        { text: 'impact hub', details: ['One page consolidating beneficiaries, before/after, artifacts, testimonials'] },
        ' that quantifies who benefited and how across programs.'
      ]
    },
    readinessInContext: [
      'Readiness is strong relative to availability: you maximized rigor and show an upward trend. With ',
      { text: 'limited AP availability', details: ['School profile lists 6 AP vs district 12'] },
      ' you still hit the ceiling; the transcript climbs from 10th grade, and dual-enrolling in ',
      { text: 'Multivariable', details: ['College Multivariable completed with A-', 'Linear Algebra in progress'] },
      ' validates preparation for upper-division work.'
    ],
    storyCoherencePercent: 78,
    storyCoherenceLine: [
      'Coherence sits at 78%: 7 of 9 activities and your main essays reinforce the access theme. The personal statement focuses on ',
      { text: 'assistive tech for access', details: ['Draft PS references accessibility outcomes and user testing notes'] },
      ', which is echoed by recommenders who highlight your teaching-and-buildership pattern.'
    ],
    impactFootprint: [
      'Impact concentrates in education access. The ',
      { text: 'tutoring platform', details: ['118 weekly active students; two partner schools; retention improving 12 pts'] },
      ' reduces friction for students and coordinators, while ',
      { text: 'workshop series', details: ['Three cycles delivered; avg 24 students/session; pre/post quiz gains 18%'] },
      ' expands reach beyond your school.'
    ],
    recognitionMix: [
      'Credibility is supported by external reads: ',
      { text: 'national finalist', details: ['Civic Tech Challenge - finalist (top 10/1,200)'] },
      ', ',
      { text: 'two state-level awards', details: ['State CS Olympiad - 2nd place', 'State Service Innovation Award - winner'] },
      ', and multiple school honors. This ladder validates both craft and contribution.'
    ],
    trajectoryDurability: [
      'Trajectory points up and the work outlives you. You progressed from tutor to program ',
      { text: 'director', details: ['Tutor to coordinator to director; scope expanded to two schools'] },
      ', built written playbooks, and trained successors for two orgs. Durability is visible in maintained schedules and ',
      { text: 'handoff docs', details: ['Shared drive: onboarding checklist, weekly runbook, escalation contacts'] },
      ' that keep services running.'
    ],
    contextContribution: [
      'Context reframes choices: despite ',
      { text: 'limited AP availability', details: ['School offers 6 AP vs district 12'] },
      ', you expanded rigor via college math and contributed to an ',
      { text: 'open-source repo', details: ['Regular issues/PRs across 6 months; 42 stars; 9 forks'] },
      ', signaling initiative and community orientation.'
    ],
    committeeSoundBite: [
      '"Admit as the ',
      { text: 'civic-tech builder', details: ['Budget PDF to dashboard prototype; partner quotes; public changelog'] },
      ' who turns messy policy data into tools people actually use."'
    ],
    concludingNarrative: [
      'Taken together, your narrative is a builder-teacher translating technical skill into access at scale. Lead with the ',
      { text: 'tutoring platform', details: ['118 weekly active students; two schools; retention improving'] },
      ' as living proof, braid in the research and outreach that sharpened the tools, and anchor credibility with the ',
      { text: 'national finalist', details: ['Civic Tech Challenge finalist (top 10/1,200)'] },
      ' read. Over the next 60-90 days, publish a monthly update with before/after metrics and a brief note from a beneficiary. With quantified outcomes and documented handoffs, your profile reads not as "busy" but as a systems builder whose work keeps running without you.'
    ]
  }
};
