import React, { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { InsightCard, InsightCardProps } from './InsightCard';
import { InsightHero } from './InsightHero';
import { InsightSection } from './InsightSection';
import { TimelineVisualization } from './insights/TimelineVisualization';
import { ComparisonVisualization } from './insights/ComparisonVisualization';
import { NetworkVisualization } from './insights/NetworkVisualization';
import { cn } from '@/lib/utils';
import { 
  BookOpen,
  Users,
  Trophy,
  GraduationCap,
  Code,
  Lightbulb,
  AlertTriangle
} from 'lucide-react';

// MOCK DATA - Hard-coded insight examples demonstrating the types of valuable analysis
// the system can provide. In production, these would be generated by AI analysis of the user's
// actual portfolio data, identifying non-obvious patterns, gaps, and opportunities.
const MOCK_INSIGHTS: InsightCardProps[] = [
  {
    type: 'pattern',
    headline: 'Consistent Leadership Through Technology',
    insight: 'Your portfolio shows a recurring pattern: you consistently take leadership roles in technical contexts, but rarely in non-technical settings. This suggests your confidence as a leader is domain-specific.',
    significance: 'Admissions officers look for versatile leadership. While your tech leadership is strong, diversifying into non-technical leadership roles (student government, community organizing, arts) would demonstrate broader capability.',
    evidence: [
      { label: '3 Technical Team Lead roles', icon: Code },
      { label: '5 Hackathon organizing roles', icon: Trophy },
      { label: '0 Non-technical leadership positions', icon: Users },
    ],
    visualization: (
      <NetworkVisualization
        centerNodeId="tech-lead"
        nodes={[
          { id: 'tech-lead', label: 'Tech Leadership', type: 'primary', connections: ['robotics', 'coding', 'hackathon'] },
          { id: 'robotics', label: 'Robotics Captain', type: 'secondary', connections: [] },
          { id: 'coding', label: 'CS Club President', type: 'secondary', connections: [] },
          { id: 'hackathon', label: 'Hackathon Organizer', type: 'secondary', connections: [] },
        ]}
      />
    ),
    action: {
      label: 'Explore Non-Technical Leadership Opportunities',
      onClick: () => ,
    },
    priority: 'critical',
    impactScore: 9,
  },
  {
    type: 'trajectory',
    headline: 'Accelerating Research Sophistication',
    insight: 'Your research projects show rapid progression from basic literature reviews (Grade 9) to original experimental design (Grade 11). The pace of growth is significantly faster than typical student researchers.',
    significance: 'This trajectory demonstrates genuine intellectual curiosity and self-directed learning. It\'s a stronger signal than any single prestigious program, because it shows intrinsic motivation rather than just access to resources.',
    evidence: [
      { label: 'Grade 9: School science fair', icon: Trophy },
      { label: 'Grade 10: University lab internship', icon: GraduationCap },
      { label: 'Grade 11: Independent research publication', icon: BookOpen },
    ],
    visualization: (
      <TimelineVisualization
        events={[
          { date: 'Fall 2022', label: 'Science Fair Project', status: 'completed', description: 'Basic experimental design on plant growth' },
          { date: 'Summer 2023', label: 'University Lab Internship', status: 'completed', description: 'Assisted PhD student with data collection' },
          { date: 'Fall 2023', label: 'Independent Research', status: 'completed', description: 'Designed novel experiment on microplastics' },
          { date: 'Spring 2024', label: 'Research Publication', status: 'current', description: 'Paper under review at peer-reviewed journal' },
          { date: 'Summer 2024', label: 'Research Conference', status: 'upcoming', description: 'Invited to present at regional symposium' },
        ]}
      />
    ),
    priority: 'high',
    impactScore: 8,
  },
  {
    type: 'gap',
    headline: 'Missing Quantitative Impact Metrics',
    insight: 'You list 6 community service activities, but only 2 include specific numbers (hours, people served, funds raised). This makes it difficult to assess the true scale and significance of your community work.',
    significance: 'Without metrics, admissions officers may undervalue your community impact. Adding concrete numbers transforms "volunteered at food bank" into "served 200+ families weekly for 18 months" – a much stronger claim.',
    evidence: [
      { label: '6 Community activities listed', icon: Users },
      { label: 'Only 2 have quantitative metrics', icon: Trophy },
      { label: '4 activities lack measurable impact', icon: Users },
    ],
    action: {
      label: 'Add Metrics to Community Activities',
      onClick: () => ,
    },
    priority: 'high',
    impactScore: 7,
  },
  {
    type: 'strength',
    headline: 'Rare Cross-Disciplinary Connector',
    insight: 'You\'re one of the few students who combines STEM research with creative writing awards. This intersection is unusual and memorable – only ~3% of applicants show genuine depth in both technical and creative fields.',
    significance: 'Cross-disciplinary students are highly valued because they bring diverse perspectives to campus discussions. Your combination of scientific rigor and creative expression suggests you can bridge different academic communities.',
    evidence: [
      { label: '2 Science research projects', icon: BookOpen },
      { label: '3 Writing competition awards', icon: Trophy },
      { label: 'Published in literary magazine', icon: Lightbulb },
    ],
    priority: 'high',
    impactScore: 9,
  },
  {
    type: 'comparison',
    headline: 'Above-Average Activity Depth, Below-Average Breadth',
    insight: 'Compared to admitted students, you show exceptional depth (3+ years commitment) but limited breadth (only 4 activity categories vs. typical 6-7). You\'re highly focused, but perhaps too narrow.',
    significance: 'Selective colleges want both depth AND breadth. Your depth is excellent and shouldn\'t be sacrificed, but adding 1-2 activities in unexplored areas (arts, athletics, etc.) would round out your profile without diluting focus.',
    evidence: [
      { label: 'Average commitment: 3.2 years', icon: Trophy },
      { label: 'Activity categories: 4 vs typical 6-7', icon: Users },
    ],
    visualization: (
      <ComparisonVisualization
        items={[
          { label: 'Activity Depth', yourValue: 8, averageValue: 6, unit: '/10', max: 10 },
          { label: 'Activity Breadth', yourValue: 4, averageValue: 6, unit: ' categories', max: 10 },
          { label: 'Time Commitment', yourValue: 18, averageValue: 12, unit: ' hrs/week', max: 25 },
        ]}
      />
    ),
    priority: 'medium',
    impactScore: 6,
  },
  {
    type: 'opportunity',
    headline: 'Untapped Research Publication Potential',
    insight: 'Your independent research on microplastics filtration has the sophistication and novelty to be submitted to peer-reviewed journals. Currently, you\'re underselling it by only listing it as a "project."',
    significance: 'A publication, even if not in a top-tier journal, dramatically increases credibility. It shows you\'ve engaged with the scientific review process and your work meets professional standards. This separates you from students who do "research" that\'s never externally validated.',
    evidence: [
      { label: 'Original experimental design', icon: Lightbulb },
      { label: 'Novel findings on filtration efficiency', icon: BookOpen },
      { label: 'Mentor willing to co-author', icon: Users },
    ],
    action: {
      label: 'Research Journal Submission Guide',
      onClick: () => ,
    },
    priority: 'medium',
    impactScore: 8,
  },
  {
    type: 'correlation',
    headline: 'Teaching Experience Amplifies Leadership Claims',
    insight: 'There\'s a strong correlation in your portfolio: activities where you taught others (tutoring, workshop leading) are also where you showed the most measurable impact. This suggests teaching is a core strength you should emphasize.',
    significance: 'Teaching requires clarity of thought, empathy, and patience – all highly valued traits. By explicitly framing yourself as an "educator" in your personal statement, you can create a coherent narrative that ties together seemingly disparate activities.',
    evidence: [
      { label: 'Tutored 15 students in math', icon: Users },
      { label: 'Led 3 coding workshops', icon: Code },
      { label: 'Trained new robotics team members', icon: GraduationCap },
    ],
    priority: 'medium',
    impactScore: 7,
  },
  {
    type: 'risk',
    headline: 'GPA Dip in Junior Year Needs Context',
    insight: 'Your GPA dropped from 3.95 to 3.7 in junior year fall semester, coinciding with increased extracurricular commitments. Without explanation, this looks like poor time management. But the timing suggests you prioritized meaningful activities.',
    significance: 'Admissions officers will notice this dip. Proactively addressing it in the Additional Information section – explaining you took on leadership roles that required significant time – reframes it as a deliberate choice rather than academic struggle.',
    evidence: [
      { label: 'GPA: 3.95 → 3.70', icon: Trophy },
      { label: 'Same semester: 3 new leadership roles', icon: Users },
    ],
    action: {
      label: 'Draft Explanation for Additional Info',
      onClick: () => ,
    },
    priority: 'critical',
    impactScore: 9,
  },
];

export const PortfolioOverview = () => {
  const [activeTab, setActiveTab] = useState<'critical' | 'high' | 'all'>('critical');

  // Organize insights by priority
  const criticalInsights = MOCK_INSIGHTS.filter(i => i.priority === 'critical');
  const highInsights = MOCK_INSIGHTS.filter(i => i.priority === 'high');
  const mediumLowInsights = MOCK_INSIGHTS.filter(i => i.priority === 'medium' || i.priority === 'low');

  // Get insights for current tab
  const getVisibleInsights = () => {
    if (activeTab === 'critical') return criticalInsights;
    if (activeTab === 'high') return [...criticalInsights, ...highInsights];
    return MOCK_INSIGHTS;
  };

  const visibleInsights = getVisibleInsights();
  const heroInsight = criticalInsights[0];

  return (
    <div className="space-y-12">
      {/* Header */}
      <div className="space-y-2">
        <h1 className="text-4xl md:text-5xl font-extrabold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">Portfolio Insights</h1>
        <p className="text-muted-foreground text-xl md:text-2xl">
          AI-discovered patterns and opportunities you wouldn't notice on your own
        </p>
      </div>

      {/* Tab Navigation */}
      <div className="flex items-center gap-2 border-b border-border">
        <button
          onClick={() => setActiveTab('critical')}
          className={cn(
            'px-7 py-4 text-lg font-semibold border-b-2 transition-colors',
            activeTab === 'critical'
              ? 'border-destructive text-destructive'
              : 'border-transparent text-muted-foreground hover:text-foreground'
          )}
        >
          Critical
          <Badge variant="destructive" className="ml-2">
            {criticalInsights.length}
          </Badge>
        </button>
        <button
          onClick={() => setActiveTab('high')}
          className={cn(
            'px-7 py-4 text-lg font-semibold border-b-2 transition-colors',
            activeTab === 'high'
              ? 'border-primary text-primary'
              : 'border-transparent text-muted-foreground hover:text-foreground'
          )}
        >
          High Priority
          <Badge variant="default" className="ml-2">
            {highInsights.length}
          </Badge>
        </button>
        <button
          onClick={() => setActiveTab('all')}
          className={cn(
            'px-7 py-4 text-lg font-semibold border-b-2 transition-colors',
            activeTab === 'all'
              ? 'border-primary text-primary'
              : 'border-transparent text-muted-foreground hover:text-foreground'
          )}
        >
          All Insights
          <Badge variant="outline" className="ml-2">
            {MOCK_INSIGHTS.length}
          </Badge>
        </button>
      </div>

      {/* Hero Insight - Only shown on critical tab */}
      {activeTab === 'critical' && heroInsight && (
        <InsightHero
          icon={AlertTriangle}
          headline={heroInsight.headline}
          insight={heroInsight.insight}
          action={heroInsight.action || { label: 'Take Action', onClick: () => {} }}
          colorClass="text-destructive"
          bgClass="bg-destructive/10"
        />
      )}

      {/* Critical Insights Section */}
      {(activeTab === 'critical' || activeTab === 'high' || activeTab === 'all') && (
        <div className="space-y-6">
          {activeTab !== 'critical' && (
            <h2 className="text-3xl md:text-4xl font-extrabold bg-gradient-to-r from-rose-600 to-red-500 bg-clip-text text-transparent">Critical Actions</h2>
          )}
          <div className="space-y-6">
            {criticalInsights.slice(activeTab === 'critical' ? 1 : 0).map((insight, index) => (
              <InsightCard key={`critical-${index}`} {...insight} />
            ))}
          </div>
        </div>
      )}

      {/* High Priority Section - Collapsible */}
      {(activeTab === 'high' || activeTab === 'all') && highInsights.length > 0 && (
        <InsightSection
          title="High Priority Insights"
          count={highInsights.length}
          defaultExpanded={activeTab === 'high'}
          variant="high"
        >
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {highInsights.map((insight, index) => (
              <InsightCard 
                key={`high-${index}`} 
                {...insight}
                collapsed={activeTab === 'all'}
              />
            ))}
          </div>
        </InsightSection>
      )}

      {/* Additional Insights Section - Collapsible */}
      {activeTab === 'all' && mediumLowInsights.length > 0 && (
        <InsightSection
          title="Additional Insights"
          count={mediumLowInsights.length}
          defaultExpanded={false}
          variant="medium"
        >
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {mediumLowInsights.map((insight, index) => (
              <InsightCard 
                key={`other-${index}`} 
                {...insight}
                collapsed={true}
              />
            ))}
          </div>
        </InsightSection>
      )}

      {/* Progress Indicator */}
      <div className="text-center text-sm text-muted-foreground pt-4">
        Viewing {visibleInsights.length} of {MOCK_INSIGHTS.length} insights
      </div>
    </div>
  );
};
