import React from 'react';
import { HoverCard, HoverCardTrigger, HoverCardContent } from '@/components/ui/hover-card';
import { LucideIcon, Rocket, Target, Heart, Sparkles, AlertTriangle } from 'lucide-react';
import { KPI } from '@/components/portfolio/impact/KPIDashboard';
import { CredibilitySource } from '@/components/portfolio/impact/CredibilityRollup';
import { ImpactFrame } from '@/components/portfolio/impact/ImpactFramePicker';
import { Artifact } from '@/components/portfolio/impact/ProofStrip';
import { Initiative } from '@/components/portfolio/impact/ImpactLedger';
import { RecognitionItem } from '@/components/portfolio/impact/RecognitionMap';
import { TrajectoryPoint } from '@/components/portfolio/impact/TrajectoryView';
import { DurabilityEvidence } from '@/components/portfolio/impact/DurabilityReplication';
import { ContextData } from '@/components/portfolio/impact/ContextAttribution';

// Types
export interface KeyTakeaway {
  label: string;
  description: string;
  icon: LucideIcon;
  colorClass: string;
}

export type EvidenceProps = { text: string; details: string[] };
export type RichSegment = string | EvidenceProps;

export interface VerdictOption {
  id: string;
  text: RichSegment[];
  score: number;
  reasoning: string;
}

export interface StoryTellingOption {
  id: string;
  positioning: string;
  narrative: RichSegment[];
  score: number;
  reasoning: string;
}

export interface ImpactData {
  primaryMetric: {
    value: number;
    label: string;
    unit: string;
  };
  secondaryMetrics: Array<{
    value: number | string;
    label: string;
  }>;
  description: string;
  proofLinks: Array<{
    label: string;
    url: string;
    type: 'internal' | 'external';
  }>;
  timeline: Array<{
    date: string;
    initiative: string;
    metric: string;
    status: 'ongoing' | 'completed' | 'planned';
  }>;
}

export interface RecognitionData {
  summary: string;
  tiers: Array<{
    tier: 'national' | 'state' | 'regional' | 'school';
    count: number;
    awards: Array<{
      name: string;
      date: string;
      issuer: string;
      link?: string;
    }>;
  }>;
  tierDefinitions: Array<{
    tier: string;
    description: string;
    percentile: string;
    colorClass: string;
  }>;
}

export interface OverarchingInsight {
  verdictOptions: {
    spine: VerdictOption[];
    spike: VerdictOption[];
    lift: VerdictOption[];
  };
  storyTellingOptions: StoryTellingOption[];
  readinessInContext: RichSegment[];
  storyCoherencePercent: number;
  storyCoherenceLine: RichSegment[];
  impactFootprint: RichSegment[];
  recognitionMix: RichSegment[];
  trajectoryDurability: RichSegment[];
  contextContribution: RichSegment[];
  committeeSoundBite: RichSegment[];
  impactData: ImpactData;
  recognitionData: RecognitionData;
  // Extended data for comprehensive results board
  kpis?: KPI[];
  credibilityRollup?: {
    overallScore: number;
    breakdown: CredibilitySource[];
    explanation: string;
  };
  impactFrames?: ImpactFrame[];
  artifacts?: Artifact[];
  initiatives?: Initiative[];
  recognitions?: RecognitionItem[];
  trajectory?: TrajectoryPoint[];
  durabilityEvidence?: DurabilityEvidence[];
  contextData?: ContextData;
}

export interface HolisticSummary {
  overallScore: number;
  tierName: string;
  tierPercentile: string;
  profileSummary: string;
  coreIdentity: KeyTakeaway;
  competitivePosition: KeyTakeaway;
  narrativeTheme: KeyTakeaway;
  biggestDifferentiator: KeyTakeaway;
  criticalGap: KeyTakeaway;
  overarchingInsight?: OverarchingInsight;
}

// Helper Components
const InlineEvidence: React.FC<EvidenceProps> = ({ text, details }) => (
  <HoverCard>
    <HoverCardTrigger asChild>
      <span className="underline decoration-dotted underline-offset-4 cursor-help text-sky-600 hover:text-sky-700">
        {text}
      </span>
    </HoverCardTrigger>
    <HoverCardContent align="start" className="w-80">
      <div className="text-sm font-semibold mb-1">Evidence</div>
      <ul className="list-disc pl-5 space-y-1 text-sm leading-6">
        {details.map((d, i) => (
          <li key={i} className="text-foreground/90">{d}</li>
        ))}
      </ul>
    </HoverCardContent>
  </HoverCard>
);

export const renderRich = (segments: RichSegment[]) =>
  segments.map((seg, i) =>
    typeof seg === 'string' ? <span key={i}>{seg}</span> : <InlineEvidence key={i} text={seg.text} details={seg.details} />
  );

// IMPORTANT: Hard-coded mock data representing a holistic portfolio analysis
// In production, this would be generated by AI analyzing the user's complete portfolio
// and synthesizing patterns across all dimensions, activities, and achievements
export const MOCK_HOLISTIC_SUMMARY: HolisticSummary = {
  overallScore: 8.2,
  tierName: 'Diamond Achiever',
  tierPercentile: 'Top 15%',
  profileSummary: 'You present as a community-focused STEM leader with demonstrated technical expertise, sustained volunteer commitment, and emerging research capabilities. Your portfolio shows cross-domain versatility, positioning you competitively for Top 20 schools with reach potential for Top 10.',
  coreIdentity: {
    label: 'STEM Leader & Community Catalyst',
    description: 'You consistently combine technical projects with community service, showing you can lead in both contexts.',
    icon: Rocket,
    colorClass: 'border-primary',
  },
  competitivePosition: {
    label: 'Strong T20, Reach for T10',
    description: 'Your profile aligns well with schools ranked 11-20. Stanford/MIT are reaches; schools like Duke/Northwestern are targets.',
    icon: Target,
    colorClass: 'border-purple-500',
  },
  narrativeTheme: {
    label: 'Using Technology to Democratize Access',
    description: 'Your story centers on leveraging technical skills to create opportunities for underserved communities.',
    icon: Heart,
    colorClass: 'border-green-500',
  },
  biggestDifferentiator: {
    label: 'Cross-Domain Leadership (Tech + Community)',
    description: 'Unlike most STEM students focused purely on research, you balance technical depth with genuine community impact.',
    icon: Sparkles,
    colorClass: 'border-orange-500',
  },
  criticalGap: {
    label: 'Need Quantifiable Impact Metrics',
    description: 'Your community activities lack specific numbers (people served, hours, outcomes), making impact hard to assess.',
    icon: AlertTriangle,
    colorClass: 'border-destructive',
  },
  overarchingInsight: {
    verdictOptions: {
      spine: [
        {
          id: 'civic-tech-democratizer',
          text: [
            'Your spine is clear: using technology to democratize access - from ',
            { text: 'Title I workshops', details: ['Free cycles for two Title I partners', 'Avg 24 students/session'] },
            ' to mentoring first-time coders via the ',
            { text: 'library program', details: ['Monthly beginner cohorts since Jan 2024', 'Consistent waitlist demand'] },
            '.'
          ],
          score: 9.2,
          reasoning: 'Strongest narrative thread - unifies technical skills, community impact, and leadership across all activities'
        },
        {
          id: 'education-equity-champion',
          text: [
            'You are an education equity champion who leverages ',
            { text: 'technical expertise', details: ['Full-stack platform, 118 weekly users', 'Adaptive controller kits for inclusion'] },
            ' to expand opportunity for underserved students, with a track record of ',
            { text: 'sustained mentorship', details: ['18 months tutoring program', '24 mentees across two cohorts'] },
            ' that demonstrates genuine investment beyond building.'
          ],
          score: 8.7,
          reasoning: 'Emphasizes social justice angle - highly valued but slightly narrower than democratization theme'
        },
        {
          id: 'systems-builder',
          text: [
            'You are a systems thinker who identifies inefficiencies and builds ',
            { text: 'scalable solutions', details: ['Platform architecture serves 2 schools', 'Open-source controller repo: 42 stars'] },
            ' that outlive your direct involvement, as evidenced by ',
            { text: 'handoff documentation', details: ['Onboarding checklist, weekly runbook', 'Successor training materials'] },
            ' ensuring continuity.'
          ],
          score: 8.3,
          reasoning: 'Highlights analytical and architectural abilities, but less emotionally resonant than access narrative'
        },
        {
          id: 'cross-disciplinary-connector',
          text: [
            'You bridge policy, data science, and community organizing - translating ',
            { text: 'budget PDFs into dashboards', details: ['Civic Tech Challenge finalist', 'Public changelog, partner quotes'] },
            ' while simultaneously running ',
            { text: 'hands-on programs', details: ['Weekly tutoring sessions', 'Monthly beginner workshops'] },
            ' that connect technical work to human outcomes.'
          ],
          score: 7.9,
          reasoning: 'Unique positioning but may seem unfocused without careful framing - requires precise essay execution'
        }
      ],
      spike: [
        {
          id: 'quantifiable-impact',
          text: [
            'Your ',
            { text: 'quantifiable community impact', details: ['118 students weekly through tutoring platform', 'MOUs with two partner schools', 'Tutor roster grew 6 to 19', 'Retention improving 12 pts'] },
            ' is exceptional - concrete adoption metrics and institutional partnerships that separate you from peers who claim "impact" without evidence.'
          ],
          score: 9.5,
          reasoning: 'Most distinctive spike - hard numbers validate claims and demonstrate scale rarely seen in high school portfolios'
        },
        {
          id: 'technical-leadership',
          text: [
            'A distinctive spike in engineering-for-access with real adoption - your ',
            { text: 'tutoring platform', details: ['118 weekly active students last month', 'MOUs with two partner schools', 'Tutor roster grew 6 to 19'] },
            ' consistently serves local schools, and the ',
            { text: 'adaptive controller kits', details: ['18 robotics members using kits', 'Open-source repo: 42 stars, 9 forks'] },
            ' lowered barriers for new participants.'
          ],
          score: 8.8,
          reasoning: 'Demonstrates technical maturity and sustained operation - shows you can shepherd projects from idea to adoption'
        },
        {
          id: 'external-validation',
          text: [
            'Your spike is in externally validated impact: ',
            { text: 'national finalist recognition', details: ['Civic Tech Challenge - finalist (top 10/1,200)'] },
            ' for civic technology combined with ',
            { text: 'state-level awards', details: ['State CS Olympiad - 2nd place', 'State Service Innovation Award - winner'] },
            ' that validate both technical craft and community contribution.'
          ],
          score: 8.4,
          reasoning: 'Third-party validation carries weight, but slightly weaker than direct adoption metrics'
        }
      ],
      lift: [
        {
          id: 'recognition-pursuit',
          text: [
            'Biggest lift: convert effort into public outcomes. Instead of logging hours, surface a compact metrics layer - a single ',
            { text: 'impact hub', details: ['One page consolidating beneficiaries, before/after, artifacts, testimonials'] },
            ' that quantifies who benefited and how across programs.'
          ],
          score: 9.0,
          reasoning: 'Most critical gap - you have strong work that lacks third-party validation. National competitions would dramatically strengthen credibility'
        },
        {
          id: 'leadership-breadth',
          text: [
            'You should ',
            { text: 'expand leadership beyond tech', details: ['Consider student government role', 'Arts/culture leadership opportunity', 'Cross-domain club presidency'] },
            ' to demonstrate versatility. Your technical leadership is clear, but schools want to see you can lead in contexts where you\'re not the expert.'
          ],
          score: 7.5,
          reasoning: 'Would strengthen well-roundedness, but lower priority than recognition - your tech leadership is already strong'
        }
      ]
    },
    storyTellingOptions: [
      {
        id: 'civic-tech-narrative',
        positioning: 'Civic-Tech Builder',
        narrative: [
          'Frame your application around: building technology for civic good. Lead with the ',
          { text: 'tutoring platform', details: ['118 weekly active students', 'Two schools', 'Retention improving'] },
          ' as living proof of impact at scale. In your personal statement, focus on the moment you realized code could ',
          { text: 'democratize access', details: ['Title I workshops expanding reach', 'Library program removing barriers'] },
          ' to education. Position supplements around how each project serves underserved communities. This narrative aligns perfectly with top-tier college values (innovation + equity).'
        ],
        score: 9.1,
        reasoning: 'Best aligns with top-tier college values - innovation paired with social impact. Most compelling for T10 schools'
      },
      {
        id: 'equity-advocate-narrative',
        positioning: 'Education Equity Advocate',
        narrative: [
          'Position yourself as someone who uses tech to expand opportunity. Center your ',
          { text: 'sustained mentorship', details: ['18 months tutoring program', '24 mentees across cohorts', 'Documented skill progression'] },
          ' and frame the platform as a tool that emerged from seeing tutors struggle with coordination. Personal statement should explore your ',
          { text: 'identity connection', details: ['First-gen college aspirant', 'Resource constraints shaped perspective'] },
          ' to access issues. This narrative is powerful but requires authentic personal connection to avoid seeming performative.'
        ],
        score: 8.6,
        reasoning: 'Strong social justice angle - highly valued but competitive. Requires authentic personal connection to resonate'
      },
      {
        id: 'systems-thinker-narrative',
        positioning: 'Technical Systems Architect',
        narrative: [
          'Tell the story of someone who sees inefficient systems and builds ',
          { text: 'scalable solutions', details: ['Platform architecture', 'Open-source contributions', 'Handoff documentation'] },
          '. Your narrative centers on sustainability - projects that ',
          { text: 'outlive your involvement', details: ['Documented handoffs', 'Successor training', 'Maintained operations'] },
          '. This positions you as mature and systems-oriented, ideal for engineering programs that value architectural thinking.'
        ],
        score: 8.2,
        reasoning: 'Appeals to technical programs but less emotionally compelling - best for pure CS/engineering applications'
      },
      {
        id: 'policy-to-action-narrative',
        positioning: 'Policy-to-Action Translator',
        narrative: [
          'Frame yourself as bridging the gap between policy and implementation. Start with ',
          { text: 'civic tech work', details: ['Budget visualization dashboard', 'Policy data made accessible'] },
          ' and show how this connects to hands-on programs. Position your technical skills as a means to ',
          { text: 'translate complex systems', details: ['Data visualization for accessibility', 'Platform reducing coordination friction'] },
          ' into actionable tools. This narrative works well for schools with strong public policy + CS intersections (Stanford, Harvard, Princeton).'
        ],
        score: 7.8,
        reasoning: 'Unique angle but requires careful execution - risk of seeming scattered across too many domains'
      }
    ],
    readinessInContext: [
      'Readiness is strong relative to availability: you maximized rigor and show an upward trend. With ',
      { text: 'limited AP availability', details: ['School profile lists 6 AP vs district 12'] },
      ' you still hit the ceiling; the transcript climbs from 10th grade, and dual-enrolling in ',
      { text: 'Multivariable', details: ['College Multivariable completed with A-', 'Linear Algebra in progress'] },
      ' validates preparation for upper-division work.'
    ],
    storyCoherencePercent: 78,
    storyCoherenceLine: [
      'Coherence sits at 78%: 7 of 9 activities and your main essays reinforce the access theme. The personal statement focuses on ',
      { text: 'assistive tech for access', details: ['Draft PS references accessibility outcomes and user testing notes'] },
      ', which is echoed by recommenders who highlight your teaching-and-buildership pattern.'
    ],
    impactFootprint: [
      'Impact concentrates in education access. The ',
      { text: 'tutoring platform', details: ['118 weekly active students; two partner schools; retention improving 12 pts'] },
      ' reduces friction for students and coordinators, while ',
      { text: 'workshop series', details: ['Three cycles delivered; avg 24 students/session; pre/post quiz gains 18%'] },
      ' expands reach beyond your school.'
    ],
    recognitionMix: [
      'Credibility is supported by external reads: ',
      { text: 'national finalist', details: ['Civic Tech Challenge - finalist (top 10/1,200)'] },
      ', ',
      { text: 'two state-level awards', details: ['State CS Olympiad - 2nd place', 'State Service Innovation Award - winner'] },
      ', and multiple school honors. This ladder validates both craft and contribution.'
    ],
    trajectoryDurability: [
      'Trajectory points up and the work outlives you. You progressed from tutor to program ',
      { text: 'director', details: ['Tutor to coordinator to director; scope expanded to two schools'] },
      ', built written playbooks, and trained successors for two orgs. Durability is visible in maintained schedules and ',
      { text: 'handoff docs', details: ['Shared drive: onboarding checklist, weekly runbook, escalation contacts'] },
      ' that keep services running.'
    ],
    contextContribution: [
      'Context reframes choices: despite ',
      { text: 'limited AP availability', details: ['School offers 6 AP vs district 12'] },
      ', you expanded rigor via college math and contributed to an ',
      { text: 'open-source repo', details: ['Regular issues/PRs across 6 months; 42 stars; 9 forks'] },
      ', signaling initiative and community orientation.'
    ],
    committeeSoundBite: [
      '"Admit as the ',
      { text: 'civic-tech builder', details: ['Budget PDF to dashboard prototype; partner quotes; public changelog'] },
      ' who turns messy policy data into tools people actually use."'
    ],
    // HARD-CODED DATA: Comprehensive impact and recognition data for results board
    kpis: [
      {
        id: 'reach',
        value: 118,
        label: 'Weekly Active Students',
        context: 'Across 2 Title I schools over 18 months of sustained programming',
        trend: { direction: 'up' as const, change: '+94 from Sept 2023 baseline (24 students)' },
        significance: 'Direct service delivery, not one-time event. Demonstrates sustained engagement and operational capacity to manage multi-site programs.'
      },
      {
        id: 'retention',
        value: '+12pts',
        label: 'Retention Improvement',
        context: 'Spring 2024 vs. Fall 2023 cohort completion rates',
        trend: { direction: 'up' as const, change: 'From 64% completion to 76% completion' },
        significance: 'Indicates quality and stickiness, not just signup. Behavioral change signal—students found sustained value beyond initial curiosity.'
      },
      {
        id: 'depth',
        value: '24 avg',
        label: 'Students Per Workshop',
        context: '3 cycles delivered, 9 sessions total across Spring 2024',
        significance: 'Consistent engagement across multiple delivery formats. Shows ability to attract and retain audience beyond platform.'
      },
      {
        id: 'durability',
        value: '2/2',
        label: 'Programs Still Running',
        context: 'After leadership handoff and transition planning',
        significance: 'Built to last beyond founder involvement. Evidence of institutional buy-in and sustainable design, not just personal charisma.'
      }
    ],
    credibilityRollup: {
      overallScore: 82,
      breakdown: [
        {
          category: 'awards' as const,
          weight: 40,
          items: [
            { 
              name: 'Civic Tech Challenge Finalist', 
              selectivity: 'Top 10 of 1,200 applicants nationwide',
              date: 'March 2024',
              link: 'https://example.com/civic-tech-finalist'
            },
            { 
              name: 'State CS Olympiad - 2nd Place', 
              selectivity: 'Top 3 of 180 competing teams',
              date: 'February 2024'
            },
            { 
              name: 'State Service Innovation Award', 
              selectivity: 'Winner among 40 nominees',
              date: 'April 2024'
            }
          ]
        },
        {
          category: 'partners' as const,
          weight: 30,
          items: [
            { 
              name: 'Metro School District Partnership MOU',
              selectivity: '1 of 5 approved student-led district programs',
              date: 'January 2024'
            },
            {
              name: 'State Education Dept Pilot Program',
              selectivity: 'Selected from 40 applications statewide',
              date: 'September 2023'
            }
          ]
        },
        {
          category: 'press' as const,
          weight: 15,
          items: [
            { 
              name: 'City Chronicle Feature: "Student Builds Bridge"',
              date: 'May 2024',
              link: 'https://news.example.com/student-bridge'
            }
          ]
        },
        {
          category: 'institutional' as const,
          weight: 10,
          items: [
            { 
              name: 'School Board Official Commendation',
              date: 'April 2024'
            },
            {
              name: 'CS Department Excellence Award',
              date: 'May 2024'
            }
          ]
        },
        {
          category: 'peer' as const,
          weight: 5,
          items: [
            { 
              name: 'Open Source Project - 42 Stars, 9 Forks',
              date: 'Ongoing since October 2023'
            }
          ]
        }
      ],
      explanation: 'Score combines competitive selection success (40%), institutional partnership validation (30%), media third-party coverage (15%), official recognition (10%), and peer technical adoption (5%). Higher weight on competitive awards reflects their objectivity and selectivity data.'
    },
    impactFrames: [
      {
        id: 'scale' as const,
        label: 'Scale & Reach',
        description: 'Emphasize breadth of impact and number of beneficiaries',
        narrative: [
          'Your work reaches ',
          { text: '118 students weekly', evidence: 'Platform analytics: avg 118 weekly active users Jan-May 2024, verified by partner coordinators' },
          ' across ',
          { text: '2 Title I schools', evidence: 'Partnership MOUs with Lincoln HS (83% free/reduced lunch) and Jefferson MS (76% free/reduced lunch)' },
          ', delivering ',
          { text: 'sustained programming', evidence: '18 consecutive months of operation (Sept 2023 - Present), no service gaps' },
          ' rather than one-off events. The workshop series expanded reach to ',
          { text: '72 additional students', evidence: '3 cycles × 24 avg attendance = 72 cumulative students, verified by sign-in sheets' },
          ' beyond the platform, demonstrating multi-channel delivery capability and audience diversity.'
        ],
        supportingMetrics: [
          { metric: 'Total Beneficiaries', value: 190, context: '118 platform + 72 workshops' },
          { metric: 'Service Hours', value: '2,400+', context: '118 students × 2 hrs/week × 18 months' },
          { metric: 'Geographic Spread', value: '2 districts', context: 'Metro and Riverside districts' }
        ],
        strengthScore: 9.2
      },
      {
        id: 'depth' as const,
        label: 'Depth & Quality',
        description: 'Emphasize transformation and meaningful change for individuals',
        narrative: [
          'Impact shows in behavioral change, not just participation. ',
          { text: 'Retention improved 12 percentage points', evidence: 'Fall 2023: 64% completion → Spring 2024: 76% completion, tracked via platform analytics' },
          ', indicating students found sustained value beyond initial curiosity. Pre/post workshop assessments showed ',
          { text: '18% knowledge gains', evidence: 'Avg pre-quiz: 62%, post-quiz: 80% (n=72 students across 3 cycles)' },
          '. Qualitative feedback reveals ',
          { text: 'confidence shifts', evidence: 'Partner coordinator: "Students now volunteer to present their work publicly, which they wouldn\'t before"' },
          ' beyond test scores—students gained agency in academic contexts, requesting advanced topics and peer teaching opportunities.'
        ],
        supportingMetrics: [
          { metric: 'Retention Rate', value: '76%', context: '+12pts from 64% baseline' },
          { metric: 'Learning Gains', value: '+18%', context: 'Pre/post quiz delta (62%→80%)' },
          { metric: 'Testimonials', value: 4, context: 'Unprompted student + partner quotes' }
        ],
        strengthScore: 8.7
      },
      {
        id: 'catalyst' as const,
        label: 'Catalyst & Systems Change',
        description: 'Emphasize how your work enabled others or changed institutional practices',
        narrative: [
          "Your platform didn't just serve students—it ",
          { text: 'reduced coordinator burden', evidence: 'Partner feedback: "Cuts admin time from 4hrs to 30min/week for session scheduling and tracking"' },
          ' and ',
          { text: 'enabled peer tutors', evidence: '19 student tutors recruited and trained across two schools, up from 6 initial tutors' },
          ' to lead. The district adopted your ',
          { text: 'scheduling framework', evidence: 'MOU references "scheduling protocol developed by [student]" as model for other programs' },
          ' for other student-led programs. By building ',
          { text: 'replicable infrastructure', evidence: 'Handoff docs successfully used by successor program at 3rd school (Riverside HS)' },
          ', you multiplied impact beyond direct service—creating conditions for others to lead without requiring your presence.'
        ],
        supportingMetrics: [
          { metric: 'Staff Time Saved', value: '3.5 hrs/week', context: 'Per coordinator × 2 sites = 7 hrs/week total' },
          { metric: 'Peer Leaders Activated', value: 19, context: 'Student tutors recruited and trained' },
          { metric: 'Institutional Adoption', value: 1, context: 'District protocol based on your model' }
        ],
        strengthScore: 8.4
      },
      {
        id: 'policy' as const,
        label: 'Policy & Data Translation',
        description: 'Emphasize how you made complex information actionable',
        narrative: [
          'You translated ',
          { text: 'opaque budget PDFs', evidence: 'Screenshot: 200-page district budget PDF with no search or comparison features' },
          ' into an ',
          { text: 'interactive dashboard', evidence: 'GitHub repo: civic-budget-viz with filters, search, year-over-year comparison' },
          ' that community members actually used for ',
          { text: 'public comment', evidence: 'School board meeting video (April 2024): 3 residents reference dashboard data in public comment' },
          '. This bridged the gap between policy data and civic participation, demonstrating ',
          { text: 'information design skills', evidence: 'Dashboard features: budget line item search, year-over-year visualization, department filtering' },
          ' that lower barriers to civic engagement and enable informed participation in local governance.'
        ],
        supportingMetrics: [
          { metric: 'Dashboard Users', value: 340, context: 'Unique visitors in first 3 months' },
          { metric: 'Public Comments', value: 3, context: 'School board attendees citing dashboard' },
          { metric: 'Data Points', value: '2,400+', context: 'Budget line items × 3 years visualized' }
        ],
        strengthScore: 7.9
      },
      {
        id: 'research' as const,
        label: 'Research & Documentation',
        description: 'Emphasize systematic inquiry and knowledge contribution',
        narrative: [
          'You approached tutoring not as service alone but as ',
          { text: 'design research', evidence: 'User interviews: 12 students, 3 coordinators conducted with documented notes' },
          '. Pre/post assessments, ',
          { text: 'structured feedback loops', evidence: 'Bi-weekly student surveys via Google Forms, coordinator debriefs with meeting notes' },
          ', and documented ',
          { text: 'iteration logs', evidence: 'GitHub changelog: 47 issues closed with rationale documented for each change' },
          ' create a knowledge base others can build on. Your ',
          { text: 'handoff documentation', evidence: 'Shared drive: onboarding checklist, weekly runbook, FAQ, escalation contacts' },
          ' transforms tacit knowledge into institutional memory, enabling successors to maintain quality without direct mentorship.'
        ],
        supportingMetrics: [
          { metric: 'User Research', value: 15, context: '12 students + 3 coordinators interviewed' },
          { metric: 'Documentation', value: 8, context: 'Handoff materials (pages)' },
          { metric: 'Iterations', value: 47, context: 'Documented improvement cycles' }
        ],
        strengthScore: 7.6
      }
    ],
    artifacts: [
      {
        id: 'analytics',
        type: 'screenshot' as const,
        thumbnail: '/artifacts/platform-analytics.png',
        title: 'Platform Analytics Dashboard',
        description: '118 weekly active users, 76% retention rate (Spring 2024)',
        link: '/evidence/tutoring',
        date: 'May 2024'
      },
      {
        id: 'workshop-report',
        type: 'document' as const,
        title: 'Workshop Impact Report',
        description: 'Pre/post assessments showing 18% knowledge gains (n=72)',
        link: '/evidence/workshops.pdf',
        date: 'April 2024'
      },
      {
        id: 'partner-quote',
        type: 'quote' as const,
        title: 'Partner Coordinator Testimonial',
        description: '"Reduced my admin time from 4 hours to 30 minutes weekly"',
        date: 'March 2024'
      },
      {
        id: 'finalist-badge',
        type: 'screenshot' as const,
        thumbnail: '/artifacts/civic-tech-finalist.png',
        title: 'Civic Tech Challenge Finalist',
        description: 'Top 10 of 1,200 national applicants',
        link: 'https://example.com/civic-tech-finalist',
        date: 'March 2024'
      },
      {
        id: 'handoff-docs',
        type: 'document' as const,
        title: 'Program Handoff Documentation',
        description: 'Onboarding checklist, weekly runbook, escalation contacts',
        link: '/evidence/handoff',
        date: 'May 2024'
      },
      {
        id: 'news-feature',
        type: 'video' as const,
        thumbnail: '/artifacts/news-thumbnail.png',
        title: 'City Chronicle News Feature',
        description: '"Student Builds Bridge to Community Through Tech"',
        link: 'https://news.example.com/student-bridge-video',
        date: 'May 2024'
      },
      {
        id: 'mou-document',
        type: 'document' as const,
        title: 'School District Partnership MOU',
        description: 'Official partnership agreement with Metro School District',
        link: '/evidence/district-mou.pdf',
        date: 'January 2024'
      },
      {
        id: 'student-testimonials',
        type: 'quote' as const,
        title: 'Student Feedback Collection',
        description: '"I actually understand algebra now" and 3 other quotes',
        link: '/evidence/student-quotes',
        date: 'April 2024'
      }
    ],
    initiatives: [
      {
        id: 'tutoring-platform',
        name: 'Peer Tutoring Platform',
        beneficiary: {
          who: '118 high school students (weekly active)',
          demographics: '83% free/reduced lunch eligible, 62% first-generation college-bound, majority students of color (74% at Lincoln, 68% at Jefferson)'
        },
        timeSpan: {
          start: 'September 2023',
          duration: '18 months (ongoing)'
        },
        outcome: {
          primary: '76% retention rate (+12pts from 64% baseline)',
          secondary: [
            '19 peer tutors recruited and trained (up from 6 initial)',
            'Reduced coordinator admin time by 3.5 hrs/week per site',
            'Platform framework adopted by district for other programs'
          ],
          evidence: [
            '/evidence/platform-analytics',
            '/evidence/coordinator-testimonial',
            '/evidence/district-mou.pdf'
          ]
        },
        resources: {
          funding: 'District mini-grant ($500), no ongoing funding required',
          partners: ['Lincoln HS', 'Jefferson MS', 'State Education Dept'],
          volunteers: 19
        },
        durability: {
          status: 'ongoing' as const,
          successor: 'Junior coordinator trained with documented handoff. Platform continues serving 100+ students weekly after transition.'
        }
      },
      {
        id: 'workshop-series',
        name: 'CS Fundamentals Workshop Series',
        beneficiary: {
          who: '72 students cumulative across 3 cycles',
          demographics: 'Students from schools without CS in curriculum, 68% underrepresented in tech'
        },
        timeSpan: {
          start: 'January 2024',
          end: 'April 2024',
          duration: '4 months'
        },
        outcome: {
          primary: '18% average learning gains on pre/post assessments',
          secondary: [
            '24 avg students per session (9 sessions total)',
            '4 unprompted student testimonials collected',
            'CS teacher adopted curriculum materials for elective course'
          ],
          evidence: [
            '/evidence/workshop-report.pdf',
            '/evidence/student-quotes',
            '/evidence/curriculum-adoption'
          ]
        },
        resources: {
          partners: ['School CS Department', 'City Public Library'],
          volunteers: 3
        },
        durability: {
          status: 'completed' as const,
          successor: 'CS teacher integrated materials into CS1 elective course starting Fall 2024'
        }
      },
      {
        id: 'civic-budget-viz',
        name: 'Civic Budget Dashboard',
        beneficiary: {
          who: '340 community members (unique users)',
          demographics: 'School board meeting attendees and local civic engagement group members'
        },
        timeSpan: {
          start: 'October 2023',
          end: 'February 2024',
          duration: '5 months'
        },
        outcome: {
          primary: 'Dashboard cited in 3 public comments at April school board meeting',
          secondary: [
            '2,400+ budget line items visualized across 3 years',
            'District adopted transparency framework based on project',
            'Open source repo maintained by local civic group (12 contributors)'
          ],
          evidence: [
            'https://github.com/username/civic-budget-viz',
            '/evidence/board-meeting-video',
            '/evidence/district-transparency-initiative'
          ]
        },
        resources: {
          partners: ['Civic Tech Challenge', 'Local Advocacy Organization']
        },
        durability: {
          status: 'handed-off' as const,
          successor: 'Open source repo maintained by local civic group. Neighboring district adapted code for their transparency initiative.'
        }
      }
    ],
    recognitions: [
      {
        id: 'civic-tech-finalist',
        type: 'award' as const,
        tier: 'national' as const,
        name: 'Civic Tech Challenge Finalist',
        issuer: 'National Civic Tech Foundation',
        selectivity: {
          accepted: 10,
          applicants: 1200,
          description: 'Top 10 of 1,200 applicants nationwide'
        },
        date: 'March 2024',
        significance: 'Validates technical execution and civic impact at national scale. Finalist selected based on code quality, adoption metrics, and community benefit demonstration.',
        link: 'https://example.com/civic-tech-finalist'
      },
      {
        id: 'state-olympiad',
        type: 'award' as const,
        tier: 'state' as const,
        name: 'State CS Olympiad - 2nd Place',
        issuer: 'State Education Department',
        selectivity: {
          accepted: 3,
          applicants: 180,
          description: 'Top 3 of 180 competing teams'
        },
        date: 'February 2024',
        significance: 'Demonstrates CS fundamentals, algorithmic problem-solving, and performance under competition pressure. Validated by judged technical challenges.'
      },
      {
        id: 'state-service-award',
        type: 'award' as const,
        tier: 'state' as const,
        name: 'State Service Innovation Award',
        issuer: 'Governor Office - Youth Service Initiative',
        selectivity: {
          accepted: 1,
          applicants: 40,
          description: 'Winner among 40 nominees statewide'
        },
        date: 'April 2024',
        significance: 'Recognition for innovative approach to community service. Evaluated on scale, sustainability, and replicability of impact.'
      },
      {
        id: 'district-partnership',
        type: 'partnership' as const,
        tier: 'local' as const,
        name: 'Metro School District Partnership MOU',
        issuer: 'District Superintendent Office',
        selectivity: {
          accepted: 1,
          applicants: 5,
          description: '1 of 5 approved student-led district programs'
        },
        date: 'January 2024',
        significance: 'Institutional trust to run multi-school program. Required board approval and vetting process for student-led initiatives.'
      },
      {
        id: 'state-pilot',
        type: 'partnership' as const,
        tier: 'state' as const,
        name: 'State Education Dept Pilot Program',
        issuer: 'State Department of Education',
        selectivity: {
          accepted: 3,
          applicants: 40,
          description: 'Selected from 40 applications statewide'
        },
        date: 'September 2023',
        significance: 'State-level validation for educational program design. Includes access to education consultants and evaluation resources.'
      },
      {
        id: 'news-feature',
        type: 'media' as const,
        tier: 'local' as const,
        name: 'City Chronicle Feature: "Student Builds Bridge"',
        issuer: 'City Chronicle (daily newspaper)',
        date: 'May 2024',
        significance: 'Third-party validation of community impact. Feature story with interviews of beneficiaries and partners.',
        link: 'https://news.example.com/student-bridge'
      },
      {
        id: 'board-commendation',
        type: 'institutional' as const,
        tier: 'local' as const,
        name: 'School Board Official Commendation',
        issuer: 'Metro School Board',
        date: 'April 2024',
        significance: 'Official recognition by governing body at public board meeting. Recognized for "exceptional service and innovation in education."'
      },
      {
        id: 'cs-dept-award',
        type: 'institutional' as const,
        tier: 'local' as const,
        name: 'CS Department Excellence Award',
        issuer: 'High School CS Department',
        date: 'May 2024',
        significance: 'Departmental recognition for technical leadership and mentorship of junior students.'
      },
      {
        id: 'open-source',
        type: 'peer' as const,
        name: 'Budget Viz Open Source Project',
        issuer: 'GitHub Community',
        date: 'Ongoing since October 2023',
        significance: '42 stars, 9 forks on GitHub. Peer adoption and technical credibility signal. Active contributor community with 12 external contributors.'
      }
    ],
    trajectory: [
      {
        date: 'Sept 2023',
        milestone: 'Launch: Single-school pilot',
        metric: { label: 'Students', value: 24 },
        description: '6 tutors, 24 students at Lincoln HS. Initial platform MVP with basic scheduling features.'
      },
      {
        date: 'Jan 2024',
        milestone: 'Scale: Second school partnership',
        metric: { label: 'Students', value: 118 },
        inflectionPoint: true,
        description: 'Expanded to Jefferson MS after successful pilot. 19 tutors, 118 students total. District partnership MOU signed.'
      },
      {
        date: 'March 2024',
        milestone: 'Recognition: National finalist selection',
        description: 'Civic Tech Challenge top 10 of 1,200 nationwide. Third-party validation of technical execution and impact.'
      },
      {
        date: 'April 2024',
        milestone: 'Replication: Curriculum institutional adoption',
        description: 'Workshop curriculum integrated into CS elective course. Scheduling framework adopted as district model for student-led programs.'
      },
      {
        date: 'May 2024',
        milestone: 'Handoff: Successful leadership transition',
        metric: { label: 'Retention', value: '76%' },
        inflectionPoint: true,
        description: 'Successor trained with complete documentation. Platform maintains 100+ weekly users. Retention improved to 76% (+12pts from baseline).'
      }
    ],
    durabilityEvidence: [
      {
        initiative: 'Tutoring Platform',
        persistence: {
          status: 'still-running' as const,
          since: 'September 2023',
          evidence: 'Successor coordinator continues weekly sessions. Platform analytics show sustained 100+ weekly active users post-handoff. No service interruptions during transition.'
        },
        replication: {
          adopted: true,
          sites: 3,
          description: 'Scheduling framework adopted by Riverside HS using handoff documentation. District references model in MOU template for other student-led programs.'
        }
      },
      {
        initiative: 'Workshop Curriculum',
        persistence: {
          status: 'adopted-by-institution' as const,
          since: 'May 2024',
          evidence: 'CS teacher integrated all workshop materials into CS1 elective course syllabus for Fall 2024. Materials listed in official course description.'
        }
      },
      {
        initiative: 'Budget Dashboard',
        persistence: {
          status: 'still-running' as const,
          since: 'February 2024',
          evidence: 'Open source repo maintained by local civic engagement group. 12 active contributors. Used in 3 subsequent school board meetings per meeting video records.'
        },
        replication: {
          adopted: true,
          sites: 1,
          description: 'Neighboring district (Riverside Unified) adapted codebase for their budget transparency initiative. Forked repo with attribution.'
        }
      }
    ],
    contextData: {
      beneficiaries: {
        primary: '118 students across 2 Title I schools (weekly active)',
        demographics: [
          '83% free/reduced lunch eligible at Lincoln HS',
          '76% free/reduced lunch eligible at Jefferson MS',
          '62% first-generation college-bound students',
          'Majority students of color (74% at Lincoln, 68% at Jefferson)'
        ],
        quotes: [
          '"I actually understand algebra now. Before tutoring I was completely lost." - 10th grade student',
          '"Platform cuts my admin time from 4 hours to 30 minutes weekly. Game changer." - Coordinator, Lincoln HS',
          '"Students now volunteer to present their work publicly, which they wouldn\'t before." - Partner coordinator',
          '"My daughter looks forward to tutoring every week. First time she\'s excited about math." - Parent'
        ]
      },
      counterfactual: {
        description: 'Lincoln HS had no structured peer tutoring system before platform launch. Jefferson MS operated volunteer-based system with 40% tutor no-show rate and no attendance tracking. Coordinators managed scheduling via spreadsheets and GroupMe with frequent miscommunication.',
        evidence: 'Partner coordinator interview (Jan 2024): "We tried spreadsheets and GroupMe but couldn\'t track attendance effectively or match students with right tutors. It was chaos honestly."'
      },
      resources: {
        funding: [
          'District mini-grant: $500 (one-time)',
          'No ongoing operational costs (hosting donated)',
          'No external funding required for sustainability'
        ],
        partners: [
          'Lincoln HS Administration (site host)',
          'Jefferson MS Administration (site host)',
          'State Education Department (MOU and evaluation support)',
          'City Public Library (workshop space)',
          'CS Department (technical mentorship)'
        ],
        volunteers: 19,
        timeCommitment: '12 hrs/week average (10 development + 2 coordination)'
      },
      attribution: {
        yourRole: 'Sole developer and program director. Designed platform architecture, wrote all code, recruited tutors, trained coordinators, built curriculum, managed partnerships.',
        collaborators: [
          'CS teacher advisor (technical feedback on architecture, not code contribution)',
          '2 peer coordinators (day-to-day scheduling and student matching, trained by you)'
        ],
        clarity: 'You designed platform, wrote all code (verified via GitHub commits), recruited tutors through school presentations, trained coordinators with documented materials. Coordinators handle operational scheduling using platform you built. CS teacher provided technical mentorship (code reviews, architecture feedback) but zero code contribution. Partnership negotiations conducted by you with admin support for contract review.'
      }
    },
    impactData: {
      primaryMetric: {
        value: 118,
        label: 'Students Reached Weekly',
        unit: 'students'
      },
      secondaryMetrics: [
        { value: 2, label: 'Partner Schools' },
        { value: '+12pts', label: 'Retention Improvement' },
        { value: '18mo', label: 'Program Duration' }
      ],
      description: 'Your tutoring platform directly serves students across two Title I schools, with measurable improvements in participant retention and engagement.',
      proofLinks: [
        { label: 'Platform Analytics Dashboard', url: '/evidence/tutoring', type: 'internal' },
        { label: 'Workshop Impact Report (PDF)', url: '/evidence/workshops', type: 'internal' },
        { label: 'Civic Tech Challenge Finalist Page', url: 'https://example.com/finalist', type: 'external' }
      ],
      timeline: [
        { date: 'Sept 2023', initiative: 'Tutoring Platform Launch', metric: '6 tutors, 24 students', status: 'completed' },
        { date: 'Jan 2024', initiative: 'Second School Partnership', metric: '19 tutors, 118 students', status: 'ongoing' },
        { date: 'Apr 2024', initiative: 'Workshop Series (3 cycles)', metric: '24 avg students/session', status: 'completed' },
        { date: 'May 2024', initiative: 'Handoff Documentation', metric: 'Successor training complete', status: 'completed' },
        { date: 'Fall 2024', initiative: 'Platform V2 (Planned)', metric: 'Mobile app expansion', status: 'planned' }
      ]
    },
    recognitionData: {
      summary: '1 National Finalist • 2 State Awards • 3 School Honors',
      tiers: [
        {
          tier: 'national' as const,
          count: 1,
          awards: [
            { name: 'Civic Tech Challenge Finalist', date: 'March 2024', issuer: 'National Civic Tech Foundation', link: 'https://example.com' }
          ]
        },
        {
          tier: 'state' as const,
          count: 2,
          awards: [
            { name: 'State CS Olympiad - 2nd Place', date: 'Feb 2024', issuer: 'State Education Dept' },
            { name: 'State Service Innovation Award', date: 'April 2024', issuer: 'Governor\'s Office' }
          ]
        },
        {
          tier: 'school' as const,
          count: 3,
          awards: [
            { name: 'Outstanding Community Service', date: 'May 2024', issuer: 'High School' },
            { name: 'CS Department Award', date: 'May 2024', issuer: 'High School' },
            { name: 'Humanitarian Leadership', date: 'May 2023', issuer: 'High School' }
          ]
        }
      ],
      tierDefinitions: [
        { tier: 'National', description: 'Recognized among 10,000+ applicants nationwide', percentile: 'Top 1%', colorClass: 'from-amber-500 to-yellow-400' },
        { tier: 'State', description: 'Distinguished among state-level competitors', percentile: 'Top 5%', colorClass: 'from-blue-500 to-cyan-400' },
        { tier: 'Regional', description: 'Notable recognition within regional network', percentile: 'Top 15%', colorClass: 'from-orange-500 to-amber-400' },
        { tier: 'School', description: 'Honored by institution for exceptional contribution', percentile: 'Top 25%', colorClass: 'from-green-500 to-emerald-400' }
      ]
    }
  }
};
