/**
 * Workstream H demo — Phase 10 navigation harness.
 *
 * Route: /annotation-v2-demo/nav
 *
 * Exercises:
 *   - useSmartOrder (17 annotations on sampleProfile → ordered queue)
 *   - next / prev / jumpTo wiring
 *   - ProgressBar in PanelShell.progressBarSlot
 *   - NavButtons below the insight card stub
 *   - keyboard shortcuts (Tab / ↑↓ / ESC / L)
 *   - viewed-state persistence (sessionStorage-backed)
 *   - end-of-review → EndOfReview panel morph (simulated toggle)
 *   - reducedMotion collapse
 *
 * No TipTap, no bloom, no real InsightCard — those are owned by
 * Workstreams B / D / F. This page renders a dummy editor column on the
 * left and stubs an insight-card body on the right so that the panel's
 * progress-bar slot and the NavButtons row both render over realistic
 * chrome.
 */

import { useCallback, useEffect, useMemo, useState } from 'react';

import {
  PanelShell,
  usePanelMode,
  useNavStack,
  type PanelMode,
} from '@/components/annotation-v2-engine/panel';
import { sampleProfile } from '@/components/annotation-v2-engine/fixtures/sampleProfile';
import {
  useSmartOrder,
  useViewedState,
  useNavigation,
  useKeyboardShortcuts,
  ProgressBar,
  NavButtons,
  EndOfReview,
} from '@/components/annotation-v2-engine/nav';
import { TIER_META, TYPOGRAPHY } from '@/components/annotation-v2-engine';
import '@/components/annotation-v2/workshop.css';

export default function AnnotationV2NavDemo() {
  const [reducedMotion, setReducedMotion] = useState<boolean>(false);
  const [simulateEndOfReview, setSimulateEndOfReview] =
    useState<boolean>(false);

  const smartOrder = useSmartOrder({ profile: sampleProfile });
  const panel = usePanelMode({ initial: { kind: 'overview' } });
  const navStack = useNavStack();
  const viewedState = useViewedState({
    essayId: sampleProfile.essayId,
    totalCount: smartOrder.order.length,
  });

  const navigation = useNavigation({
    profile: sampleProfile,
    panel,
    navStack,
    viewedState,
    smartOrder,
  });

  // ----- panel→viewedState integration -----
  //
  // usePanelMode.insightsRead is the Set of sentence IDs that have been
  // "read" at the dwell threshold. We subscribe to it and forward every
  // newly-seen sentence into viewedState.markViewed. This is the
  // documented integration pattern for H ← F signal routing.
  useEffect(() => {
    for (const sentenceId of panel.insightsRead) {
      if (viewedState.isViewed(sentenceId)) continue;
      const sentence = sampleProfile.sentences.find(
        (s) => s.id === sentenceId,
      );
      if (!sentence) continue;
      viewedState.markViewed(sentenceId, sentence.annotationIds, {
        closeReason: 'advance',
      });
    }
    // We deliberately do not include viewedState in the dep array —
    // `isViewed` and `markViewed` are stable callbacks; including the
    // Map would re-fire on every write. This is correct behavior.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [panel.insightsRead]);

  // Demo hack: mark sentences as read when an insight opens. In production
  // F's dwell pipeline owns this signal. For the demo we auto-call
  // markInsightRead after a short delay so clicking Next actually moves
  // the progress bar.
  useEffect(() => {
    if (panel.mode.kind !== 'insight') return;
    const id = panel.mode.sentenceId;
    const timer = window.setTimeout(() => panel.markInsightRead(id), 400);
    return () => window.clearTimeout(timer);
  }, [panel.mode, panel]);

  // ----- keyboard shortcuts -----
  useKeyboardShortcuts({
    enabled: true,
    onNext: navigation.next,
    onPrev: navigation.prev,
    onEscape: () => {
      if (navStack.canPop) {
        // Stack has ancestors → pop one (Phase 8 §2.9 semantics).
        const popped = navStack.pop();
        if (popped) panel.setSentence(popped.sentenceId);
      } else if (panel.mode.kind !== 'overview') {
        panel.toOverview();
      }
    },
    onToggleList: () => {
      if (panel.mode.kind === 'list') panel.toOverview();
      else
        panel.toList();
    },
  });

  const selectedSentenceId = useMemo<string | null>(() => {
    if (panel.mode.kind === 'insight') return panel.mode.sentenceId;
    return null;
  }, [panel.mode]);

  const reset = useCallback(() => {
    viewedState.reset();
    navStack.clear();
    panel.toOverview();
  }, [navStack, panel, viewedState]);

  const endOfReviewActive =
    simulateEndOfReview || navigation.endOfReviewReached;

  const summaryProse = useMemo(() => {
    // Derive a short warm summary from the holisticSynthesis lenses. In
    // production this is generated by an end-of-review LLM call (§2.8);
    // for the demo we assemble two sentences deterministically.
    const h = sampleProfile.holisticSynthesis;
    return `${h.craftAssessment} ${h.admissionsPositioning}`;
  }, []);

  const topPrioritySentenceId = smartOrder.order[0] ?? null;

  return (
    <div
      className="min-h-screen flex flex-col"
      style={{ background: 'hsl(220 15% 97%)' }}
    >
      <Toolbar
        reducedMotion={reducedMotion}
        onReducedMotionChange={setReducedMotion}
        simulateEndOfReview={simulateEndOfReview}
        onSimulateEndOfReviewChange={setSimulateEndOfReview}
        onReset={reset}
        onStart={() => {
          const first = smartOrder.order[0];
          if (first) navigation.jumpTo(first, 'click');
        }}
      />

      <div className="flex-1 flex">
        {/* Editor column stub + debug panel */}
        <div
          className="flex-1 p-8"
          style={{
            fontFamily: TYPOGRAPHY.families.sans,
            color: 'hsl(220 15% 35%)',
            overflow: 'auto',
          }}
        >
          <div style={{ maxWidth: 680, margin: '0 auto' }}>
            <DebugPanel
              smartOrder={smartOrder.order}
              selectedSentenceId={selectedSentenceId}
              position={navigation.position}
              reviewedCount={viewedState.reviewedCount}
              totalCount={viewedState.totalCount}
              navStackDepth={navStack.stack.length}
              canNext={navigation.canNext}
              canPrev={navigation.canPrev}
              endOfReviewReached={navigation.endOfReviewReached}
              lastAnnouncement={navigation.lastAnnouncement}
            />
            <OrderList
              order={smartOrder.order}
              selectedSentenceId={selectedSentenceId}
              onJump={(id) => navigation.jumpTo(id, 'click')}
              isViewed={viewedState.isViewed}
              priorityScores={smartOrder.priorityScores}
            />
          </div>
        </div>

        <PanelShell
          mode={panel.mode}
          selectedSentenceId={selectedSentenceId}
          profile={sampleProfile}
          visible={true}
          reducedMotion={reducedMotion}
          insightsReadCount={panel.insightsReadCount}
          onTabChange={(tab) => panel.setInsightTab(tab)}
          onModeChange={(next: PanelMode) => panel.setMode(next)}
          onSelectSentence={(sentenceId) =>
            navigation.jumpTo(sentenceId, 'click')
          }
          insightSlot={
            endOfReviewActive ? (
              <EndOfReview
                profile={sampleProfile}
                topPrioritySentenceId={topPrioritySentenceId}
                summaryProse={summaryProse}
                onJumpToTop={() => {
                  if (topPrioritySentenceId) {
                    navigation.jumpTo(topPrioritySentenceId, 'click');
                    setSimulateEndOfReview(false);
                  }
                }}
                onReturnToOverview={() => {
                  setSimulateEndOfReview(false);
                  panel.toOverview();
                }}
                reducedMotion={reducedMotion}
              />
            ) : (
              <InsightSlotStub
                sentenceId={selectedSentenceId}
                navigation={navigation}
                reducedMotion={reducedMotion}
                shortcutHintVisible={panel.insightsReadCount > 0}
              />
            )
          }
          profileSlot={<SlotPlaceholder label="Profile (F wires)" />}
          listSlot={<SlotPlaceholder label="List (I wires)" />}
          progressBarSlot={
            <ProgressBar
              viewedCount={viewedState.reviewedCount}
              totalCount={viewedState.totalCount}
              reducedMotion={reducedMotion}
            />
          }
          breadcrumbSlot={
            navStack.breadcrumb.length > 0 ? (
              <BreadcrumbStub
                trail={navStack.breadcrumb.map((e) => e.sentenceId)}
              />
            ) : null
          }
        />
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Toolbar
// ---------------------------------------------------------------------------

interface ToolbarProps {
  readonly reducedMotion: boolean;
  readonly onReducedMotionChange: (v: boolean) => void;
  readonly simulateEndOfReview: boolean;
  readonly onSimulateEndOfReviewChange: (v: boolean) => void;
  readonly onReset: () => void;
  readonly onStart: () => void;
}

function Toolbar(props: ToolbarProps) {
  const {
    reducedMotion,
    onReducedMotionChange,
    simulateEndOfReview,
    onSimulateEndOfReviewChange,
    onReset,
    onStart,
  } = props;
  return (
    <div
      className="flex flex-wrap items-center gap-3 border-b p-3"
      style={{
        background: 'rgba(255,255,255,0.85)',
        borderColor: 'hsl(220 15% 90%)',
        fontFamily: TYPOGRAPHY.families.sans,
        fontSize: TYPOGRAPHY.size.panelHeader,
      }}
    >
      <strong style={{ fontWeight: TYPOGRAPHY.weight.semibold }}>
        Phase 10 · navigation
      </strong>
      <SmallButton onClick={onStart}>Start at top</SmallButton>
      <SmallButton onClick={onReset}>Reset viewed state</SmallButton>
      <label className="flex items-center gap-1">
        <input
          type="checkbox"
          checked={reducedMotion}
          onChange={(e) => onReducedMotionChange(e.currentTarget.checked)}
        />
        <span>reducedMotion</span>
      </label>
      <label className="flex items-center gap-1">
        <input
          type="checkbox"
          checked={simulateEndOfReview}
          onChange={(e) =>
            onSimulateEndOfReviewChange(e.currentTarget.checked)
          }
        />
        <span>simulate end-of-review</span>
      </label>
      <span
        style={{
          marginLeft: 'auto',
          color: 'hsl(220 10% 55%)',
          fontSize: TYPOGRAPHY.size.meta,
          letterSpacing: TYPOGRAPHY.tracking.meta,
        }}
      >
        Tab · Shift+Tab · ↑↓ · ESC · L
      </span>
    </div>
  );
}

function SmallButton({
  onClick,
  children,
}: {
  readonly onClick: () => void;
  readonly children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      style={{
        padding: '4px 10px',
        borderRadius: 6,
        border: '1px solid hsl(220 15% 85%)',
        background: 'white',
        color: 'hsl(220 15% 25%)',
        fontSize: TYPOGRAPHY.size.meta,
        cursor: 'pointer',
      }}
    >
      {children}
    </button>
  );
}

// ---------------------------------------------------------------------------
// Insight-card stub (swaps for F's InsightCard in the integrated build)
// ---------------------------------------------------------------------------

interface InsightSlotStubProps {
  readonly sentenceId: string | null;
  readonly navigation: ReturnType<typeof useNavigation>;
  readonly reducedMotion: boolean;
  readonly shortcutHintVisible: boolean;
}

function InsightSlotStub(props: InsightSlotStubProps) {
  const { sentenceId, navigation, reducedMotion, shortcutHintVisible } =
    props;
  const sentence = sentenceId
    ? sampleProfile.sentences.find((s) => s.id === sentenceId)
    : undefined;

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100%',
        padding: `${TYPOGRAPHY.panelPaddingTop} ${TYPOGRAPHY.panelPaddingX}`,
        fontFamily: TYPOGRAPHY.families.sans,
        color: 'hsl(220 15% 25%)',
      }}
    >
      <div
        style={{
          fontSize: TYPOGRAPHY.size.meta,
          letterSpacing: TYPOGRAPHY.tracking.meta,
          color: 'hsl(220 10% 55%)',
          marginBottom: 8,
          textTransform: 'uppercase',
        }}
      >
        {sentence
          ? `¶${sentence.paragraphIndex + 1} · s${sentence.indexWithinParagraph + 1} · ${TIER_META[sentence.tier].label}`
          : 'Pick a sentence to start'}
      </div>
      {sentence ? (
        <blockquote
          style={{
            fontFamily: TYPOGRAPHY.families.serif,
            fontSize: TYPOGRAPHY.size.critique,
            lineHeight: TYPOGRAPHY.lineHeight.serifProse,
            color: 'hsl(220 20% 20%)',
            borderLeft: '2px solid hsl(220 15% 85%)',
            paddingLeft: 12,
            margin: 0,
          }}
        >
          “{sentence.text}”
        </blockquote>
      ) : (
        <p
          style={{
            fontFamily: TYPOGRAPHY.families.serif,
            fontSize: TYPOGRAPHY.size.critique,
            color: 'hsl(220 15% 45%)',
            margin: 0,
          }}
        >
          Press Tab, click Next, or jump to a sentence in the list below to
          open an insight.
        </p>
      )}

      <div style={{ flex: 1 }} />

      <NavButtons
        onPrev={navigation.prev}
        onNext={navigation.next}
        canPrev={navigation.canPrev}
        canNext={navigation.canNext}
        position={navigation.position}
        shortcutHintVisible={shortcutHintVisible}
        reducedMotion={reducedMotion}
      />
    </div>
  );
}

function SlotPlaceholder({ label }: { readonly label: string }) {
  return (
    <div
      style={{
        padding: `${TYPOGRAPHY.panelPaddingTop} ${TYPOGRAPHY.panelPaddingX}`,
        fontSize: TYPOGRAPHY.size.meta,
        letterSpacing: TYPOGRAPHY.tracking.meta,
        color: 'hsl(220 10% 55%)',
        fontFamily: TYPOGRAPHY.families.sans,
      }}
    >
      {label}
    </div>
  );
}

function BreadcrumbStub({ trail }: { readonly trail: readonly string[] }) {
  return (
    <div
      style={{
        fontFamily: TYPOGRAPHY.families.sans,
        fontSize: TYPOGRAPHY.size.breadcrumb,
        color: 'hsl(220 10% 45%)',
        letterSpacing: TYPOGRAPHY.tracking.meta,
      }}
    >
      ← {trail.join(' · ')}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Debug panel — shows the state every reviewer cares about.
// ---------------------------------------------------------------------------

interface DebugPanelProps {
  readonly smartOrder: readonly string[];
  readonly selectedSentenceId: string | null;
  readonly position: { readonly index: number; readonly total: number };
  readonly reviewedCount: number;
  readonly totalCount: number;
  readonly navStackDepth: number;
  readonly canNext: boolean;
  readonly canPrev: boolean;
  readonly endOfReviewReached: boolean;
  readonly lastAnnouncement: string | null;
}

function DebugPanel(props: DebugPanelProps) {
  return (
    <section
      style={{
        border: '1px solid hsl(220 15% 85%)',
        background: 'white',
        borderRadius: 8,
        padding: 16,
        marginBottom: 20,
        fontFamily: TYPOGRAPHY.families.sans,
        fontSize: TYPOGRAPHY.size.panelHeader,
        lineHeight: 1.6,
        color: 'hsl(220 15% 25%)',
      }}
    >
      <h3
        style={{
          margin: '0 0 8px 0',
          fontSize: TYPOGRAPHY.size.overviewLabel,
          fontWeight: TYPOGRAPHY.weight.semibold,
          color: 'hsl(220 20% 20%)',
        }}
      >
        Debug
      </h3>
      <Row label="selected" value={props.selectedSentenceId ?? '(none)'} />
      <Row
        label="position"
        value={`${props.position.index + 1} of ${props.position.total}`}
      />
      <Row
        label="reviewed"
        value={`${props.reviewedCount} / ${props.totalCount}`}
      />
      <Row label="navStack depth" value={String(props.navStackDepth)} />
      <Row
        label="canPrev / canNext"
        value={`${props.canPrev} / ${props.canNext}`}
      />
      <Row
        label="endOfReview"
        value={props.endOfReviewReached ? 'reached' : 'not yet'}
      />
      <Row
        label="last announce"
        value={props.lastAnnouncement ?? '(none)'}
      />
      <Row label="order length" value={String(props.smartOrder.length)} />
    </section>
  );
}

function Row({
  label,
  value,
}: {
  readonly label: string;
  readonly value: string;
}) {
  return (
    <div style={{ display: 'flex', gap: 8, alignItems: 'baseline' }}>
      <span
        style={{
          color: 'hsl(220 10% 55%)',
          fontSize: TYPOGRAPHY.size.meta,
          letterSpacing: TYPOGRAPHY.tracking.meta,
          minWidth: 140,
        }}
      >
        {label}
      </span>
      <code
        style={{
          fontFamily: 'ui-monospace, SFMono-Regular, monospace',
          fontSize: TYPOGRAPHY.size.meta,
        }}
      >
        {value}
      </code>
    </div>
  );
}

interface OrderListProps {
  readonly order: readonly string[];
  readonly selectedSentenceId: string | null;
  readonly onJump: (sentenceId: string) => void;
  readonly isViewed: (sentenceId: string) => boolean;
  readonly priorityScores: ReadonlyMap<string, number>;
}

function OrderList(props: OrderListProps) {
  return (
    <section
      style={{
        border: '1px solid hsl(220 15% 85%)',
        background: 'white',
        borderRadius: 8,
        padding: 16,
        fontFamily: TYPOGRAPHY.families.sans,
      }}
    >
      <h3
        style={{
          margin: '0 0 12px 0',
          fontSize: TYPOGRAPHY.size.overviewLabel,
          fontWeight: TYPOGRAPHY.weight.semibold,
          color: 'hsl(220 20% 20%)',
        }}
      >
        Smart order (click to jump — resets nav stack)
      </h3>
      <ol style={{ listStyle: 'none', margin: 0, padding: 0 }}>
        {props.order.map((id, i) => {
          const sentence = sampleProfile.sentences.find((s) => s.id === id);
          const score = props.priorityScores.get(id) ?? 0;
          const viewed = props.isViewed(id);
          const selected = id === props.selectedSentenceId;
          return (
            <li key={id} style={{ marginBottom: 4 }}>
              <button
                type="button"
                onClick={() => props.onJump(id)}
                style={{
                  width: '100%',
                  textAlign: 'left',
                  padding: '6px 8px',
                  borderRadius: 6,
                  border: `1px solid ${selected ? 'hsl(145 25% 50%)' : 'hsl(220 15% 90%)'}`,
                  background: selected ? 'hsl(145 35% 96%)' : 'white',
                  color: 'hsl(220 15% 25%)',
                  fontSize: TYPOGRAPHY.size.panelHeader,
                  fontFamily: TYPOGRAPHY.families.sans,
                  cursor: 'pointer',
                  opacity: viewed ? 0.55 : 1,
                  display: 'flex',
                  gap: 8,
                  alignItems: 'baseline',
                }}
              >
                <code style={{ minWidth: 32, color: 'hsl(220 10% 50%)' }}>
                  {i + 1}.
                </code>
                <code style={{ minWidth: 48 }}>{id}</code>
                {sentence ? (
                  <span
                    style={{
                      color: 'hsl(220 10% 45%)',
                      fontSize: TYPOGRAPHY.size.meta,
                      letterSpacing: TYPOGRAPHY.tracking.meta,
                    }}
                  >
                    {TIER_META[sentence.tier].label}
                  </span>
                ) : null}
                <span
                  style={{
                    marginLeft: 'auto',
                    color: 'hsl(220 10% 50%)',
                    fontSize: TYPOGRAPHY.size.meta,
                  }}
                >
                  score {score.toFixed(3)}
                </span>
              </button>
            </li>
          );
        })}
      </ol>
    </section>
  );
}
