/**
 * moveDependencies.ts — Tier 1 hard-gate DAG (slim, corpus-attested only).
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * ARCHITECTURE PHILOSOPHY (Architecture C, confirmed 2026-04-20 with Tue)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * This file is INTENTIONALLY SMALL. It contains only relationships where the
 * corpus reviews explicitly attest that the dependent move CANNOT WORK without
 * its prerequisite. These are STRUCTURAL GATES, not pedagogical hints.
 *
 * Soft relationships (moves that "usually" pair, "often" co-occur, "cluster
 * together") live in `derivedCorrelations.json` — generated by
 * `tools/corpus/deriveCorrelations.ts` from move.sourceEssays co-occurrence.
 *
 * Named architectures (the Sarika cluster, the Francisco peak-scene cluster,
 * etc.) are expressed in `essayArchetypes.ts` via `loadBearingMoveIds` and
 * `structuralStages`. They are not duplicated here.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * INCLUSION CRITERIA (strict)
 * ═══════════════════════════════════════════════════════════════════════════
 *
 * A relationship enters this file only if ALL of the following:
 *   1. A v2.1 review explicitly states that X REQUIRES Y (verbatim or near-
 *      verbatim — not paraphrased inference).
 *   2. The dependency is STRUCTURAL (Y's absence causes X to fail), not
 *      AESTHETIC (Y's absence makes X less good).
 *   3. The `corpusJustification` field cites the specific review paragraph.
 *
 * Everything else is a correlation — belongs in derivedCorrelations.json.
 *
 * ═══════════════════════════════════════════════════════════════════════════
 * CURRENT COUNT: 6 hard-requires entries. This file should stay under ~10
 * entries even as the corpus grows. If it grows past 10, the inclusion
 * criteria are being relaxed — audit before adding.
 * ═══════════════════════════════════════════════════════════════════════════
 */

import type { MoveDependency } from './corpusTypes';

export const MOVE_DEPENDENCIES: MoveDependency[] = [
  // ───────────────────────────────────────────────────────────────────────
  // 1. final-possession-assertion REQUIRES sustained preparation
  // ───────────────────────────────────────────────────────────────────────
  {
    moveId: 'final-possession-assertion',
    hardRequires: ['extended-metaphor-priming', 'verb-possession-of-specialized-register'],
    enables: [],
    conflicts: [],
    corpusJustification:
      'Sarika review (05-harvard-2028-i-too-can-dance), Part II Move 36: "The essay\'s final thesis should assert its central metaphor with no hedge. But this move requires that preceding paragraphs have prepared the ground with possession-metaphors, primed imagery, and sustained consistency." ' +
      'Also Part III Cluster 1 ("preparation-and-arrival metaphor architecture") names Move 8 + Move 15 + Move 22 + Move 36 as a REQUIRED four-move sequence — the final possession assertion cannot be deployed without preparation. Failure mode explicitly named: "If the literal assertion comes too early, it feels unearned." ' +
      'This is structural, not aesthetic: the reader rejects the possession-claim without preceding priming.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // 2. motion-verb-mark-shape-coupling REQUIRES the verb-possession it couples
  // ───────────────────────────────────────────────────────────────────────
  {
    moveId: 'motion-verb-mark-shape-coupling',
    hardRequires: ['verb-possession-of-specialized-register'],
    enables: [],
    conflicts: [],
    corpusJustification:
      'Sarika review, Part II Move 23: "When you apply a dance verb to a writing object, make sure the mark produced by the object is compatible with the motion implied by the verb." ' +
      'The move DEFINITIONALLY requires a possession-metaphor already in the sentence to couple to. Without verb-possession, there is no motion-verb to couple with the mark-shape. Structural, not aesthetic.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // 3. refutation-triplet-mirror REQUIRES the triplet it mirrors
  // ───────────────────────────────────────────────────────────────────────
  {
    moveId: 'refutation-triplet-mirror',
    hardRequires: ['triplet-anaphora-of-difference'],
    enables: [],
    conflicts: [],
    corpusJustification:
      'Orlee review (09-harvard-2028-bra-shopping), Part II Move 16 and Pattern Cluster B: "Paragraph 7 repeats paragraph 6\'s structure but with the answer: \'I might [difference], but [capacity].\' ... The form of the refutation mirrors the form of the setup." ' +
      'The refutation-triplet-mirror move IS a mirror of a setup triplet. Without the setup triplet, there is nothing to mirror — the move cannot exist. Structural.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // 4. fear-resolution-triplet-mapping REQUIRES the causal fear-triplet it resolves
  // ───────────────────────────────────────────────────────────────────────
  {
    moveId: 'fear-resolution-triplet-mapping',
    hardRequires: ['causal-chain-triplet'],
    enables: [],
    conflicts: [],
    corpusJustification:
      'Francisco review (06-harvard-2028-three-days-before-a-plane), Part II Move 13 (fear-triplet-to-resolution-triplet direct mapping): "When an essay opens with a three-part anxiety sequence, the resolution can be a three-part relief sequence that maps element-by-element to the anxieties." ' +
      'Pattern Cluster 1 explicitly names Move 11 (causal-chain-triplet) as prerequisite for Move 13. The resolution-triplet MAPS to the fear-triplet element-by-element — without the fear-triplet, there is no mapping target. Structural.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // 5. mirror-but-not-symmetric-closing-commitment REQUIRES the identity distinction
  // ───────────────────────────────────────────────────────────────────────
  {
    moveId: 'mirror-but-not-symmetric-closing-commitment',
    hardRequires: ['one-word-identity-distinction'],
    enables: [],
    conflicts: [],
    corpusJustification:
      'Michael review (12-harvard-2028-three-years-alone), Part III Pattern Cluster C (mirror-gap closing): "The mother\'s framing of Michael (pride and joy) and Michael\'s framing of himself (her hope) are the argument; the essay\'s closing delivers the practical consequence of that argument... The thesis and the commitment are connected." ' +
      'The mirror-gap closing fills the SPECIFIC gap the identity-distinction exposed. Without the one-word identity distinction, there is no identified gap to fill — the closing promise loses its target. Structural.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // 6. labeled-ritual-internal-vocabulary REQUIRES the ritual to exist
  // ───────────────────────────────────────────────────────────────────────
  {
    moveId: 'labeled-ritual-internal-vocabulary',
    hardRequires: ['time-stamped-ritual-structure'],
    enables: [],
    conflicts: [],
    corpusJustification:
      'Michael review, Part II Move 5 (labeled ritual "multi-purpose call"): "Michael and his mother have NAMED the evening call... The act of naming is evidence that the ritual has been created deliberately." ' +
      'The labeled ritual is a LABEL applied to a ritual. Without the time-stamped ritual structure already being present, there is no ritual to label. Structural.',
  },

  // ───────────────────────────────────────────────────────────────────────
  // ENABLES-ONLY ENTRIES (inverse index for fast downstream lookup)
  //
  // These entries exist so coaching can ask "what does Y enable downstream?"
  // without scanning the whole file. They mirror the hardRequires entries.
  // ───────────────────────────────────────────────────────────────────────
  {
    moveId: 'verb-possession-of-specialized-register',
    hardRequires: [],
    enables: ['final-possession-assertion', 'motion-verb-mark-shape-coupling'],
    conflicts: [],
    corpusJustification: 'Sarika Cluster 1 lists this as mid-architecture move enabling the final assertion and the motion-mark coupling. See final-possession-assertion entry above for full citation.',
  },
  {
    moveId: 'extended-metaphor-priming',
    hardRequires: [],
    enables: ['final-possession-assertion'],
    conflicts: [],
    corpusJustification: 'Sarika Cluster 1. Priming is the ground from which possession-assertion grows. See final-possession-assertion entry for full citation.',
  },
  {
    moveId: 'triplet-anaphora-of-difference',
    hardRequires: [],
    enables: ['refutation-triplet-mirror'],
    conflicts: [],
    corpusJustification: 'Orlee Pattern Cluster B. The setup triplet enables the mirror-refutation. See refutation-triplet-mirror entry for full citation.',
  },
  {
    moveId: 'causal-chain-triplet',
    hardRequires: [],
    enables: ['fear-resolution-triplet-mapping'],
    conflicts: [],
    corpusJustification: 'Francisco Pattern Cluster 1. Causal triplet enables mapped resolution. See fear-resolution-triplet-mapping entry.',
  },
  {
    moveId: 'one-word-identity-distinction',
    hardRequires: [],
    enables: ['mirror-but-not-symmetric-closing-commitment'],
    conflicts: [],
    corpusJustification: 'Michael Pattern Cluster C. The identity distinction enables the gap-match closing. See mirror-but-not-symmetric-closing-commitment entry.',
  },
  {
    moveId: 'time-stamped-ritual-structure',
    hardRequires: [],
    enables: ['labeled-ritual-internal-vocabulary'],
    conflicts: [],
    corpusJustification: 'Michael Pattern Cluster B. The ritual structure enables the label. See labeled-ritual-internal-vocabulary entry.',
  },
];

/**
 * Development guard. Adding an entry past MAX_HARD_GATES should fail CI —
 * it means the inclusion criteria are being relaxed. If a relationship is
 * genuinely new and structural, raise this number deliberately.
 */
export const MAX_HARD_GATES = 15;
