import React, { useState } from 'react';
import { BentoMetricCard } from './BentoMetricCard';
import { BentoAchievements } from './BentoAchievements';
import { UnifiedScoreDashboard } from './UnifiedScoreDashboard';
import { CompetitiveSpectrumCard } from './CompetitiveSpectrumCard';
import { TopContributorsCard } from './TopContributorsCard';
import { PriorityActionsCard } from './PriorityActionsCard';
import { TierProgressCard } from './TierProgressCard';
import { Achievement } from '../portfolioInsightsData';
import { motion, AnimatePresence } from 'motion/react';

interface InteractivePortfolioCardBentoProps {
  overallScore: number;
  tierName: string;
  percentile: string;
  metrics: {
    academic: number;
    leadership: number;
    readiness: number;
    community: number;
    extracurricular: number;
    courseRigor: number;
  };
  achievements: Achievement[];
  schoolComparisons?: any[];
  tierProgress: {
    currentTier: string;
    nextTier: string;
    progress: number;
    pointsNeeded: number;
  };
}

// Hard-coded mock data for new components
const MOCK_TOP_CONTRIBUTORS = [
  { name: 'Leadership Impact', dimension: 'Leadership', score: 18, color: 'purple', icon: 'Users' as const },
  { name: 'Community Service', dimension: 'Service', score: 14, color: 'green', icon: 'Heart' as const },
  { name: 'Award Recognition', dimension: 'Awards', score: 12, color: 'amber', icon: 'Award' as const },
];

// Hard-coded mock academic metrics data
// In production, this would come from the user's profile data
const MOCK_ACADEMIC_METRICS = {
  gpa: { 
    weighted: 3.95, 
    unweighted: 3.87 
  },
  sat: 1520,
  act: undefined,
  apScores: { 
    total: 8, 
    average: 4.6, 
    fives: 6 
  },
  classRank: { 
    percentage: 5, 
    outOf: 240,
    rank: 12
  },
  activities: 12,
  hours: 450,
  impactReach: '2.5K',
  awards: 8,
};

// Hard-coded competitive context data for tooltips
// In production, this would be generated by AI based on the user's metrics
const COMPETITIVE_ANALYSIS = {
  gpa: {
    percentile: 'Top 20% Nationally',
    context: 'Your 3.95 weighted GPA is strong for top colleges. Here\'s how it positions you:',
    schoolTiers: [
      { tier: 'Top 50 Schools', status: 'competitive', label: 'Highly competitive' },
      { tier: 'Top 20 Schools', status: 'competitive', label: 'Competitive' },
      { tier: 'Top 10 Schools', status: 'average', label: 'Average (aim for 4.0+)' },
    ],
    tip: 'Focus on maintaining rigor with A\'s in your remaining AP/IB courses'
  },
  sat: {
    percentile: 'Top 5% (98th percentile)',
    context: 'Your 1520 SAT is excellent and meets the middle 50% for most elite schools.',
    schoolExamples: [
      { name: 'MIT', range: '1510-1580', status: 'within' },
      { name: 'Stanford', range: '1470-1570', status: 'strong' },
      { name: 'Berkeley', range: '1330-1530', status: 'above' },
    ],
    tip: 'Your score is strong. Focus efforts on other differentiators like activities'
  },
  apScores: {
    percentile: 'Top 15% Nationally',
    context: 'Taking 8 APs with a 4.6 average and 6 fives demonstrates strong academic rigor.',
    schoolTiers: [
      { tier: 'Top Colleges', status: 'competitive', label: 'Expect 5+ AP courses' },
      { tier: 'Elite Schools', status: 'competitive', label: '8+ APs is ideal' },
    ],
    tip: 'Continue taking challenging APs in your areas of interest to show depth'
  },
  classRank: {
    percentile: 'Top 5% in Class',
    context: 'Being ranked 12 out of 240 students places you in the top 5%, which is excellent.',
    schoolTiers: [
      { tier: 'Top 50 Schools', status: 'competitive', label: 'Well positioned' },
      { tier: 'Top 20 Schools', status: 'competitive', label: 'Competitive' },
      { tier: 'Top 10 Schools', status: 'competitive', label: 'Top 5% is strong' },
    ],
    tip: 'Maintain your rank by staying focused on your most challenging courses'
  },
  activities: {
    percentile: 'Above Average (12 activities)',
    context: 'You have a solid activity count. Quality matters more than quantity:',
    schoolTiers: [
      { tier: '8-15 activities', status: 'competitive', label: 'Ideal range' },
      { tier: 'Focus on depth', status: 'average', label: '2-3 core activities' },
      { tier: 'Leadership', status: 'average', label: 'Look for leadership roles' },
    ],
    tip: 'Admissions prefer "spiky" profiles with deep impact in a few areas over many surface-level involvements'
  },
  hours: {
    percentile: 'Strong Commitment (450 hours)',
    context: 'Your 450 hours of commitment demonstrates sustained dedication.',
    schoolTiers: [
      { tier: 'Most Schools', status: 'competitive', label: 'Expect 200-400 hours' },
      { tier: 'Top Schools', status: 'competitive', label: '400+ hours shows depth' },
    ],
    tip: 'Focus on increasing impact per hour rather than just accumulating more hours'
  },
  impactReach: {
    percentile: 'Substantial Impact',
    context: 'Reaching 2,500 people shows meaningful community engagement.',
    schoolTiers: [
      { tier: 'Breadth', status: 'competitive', label: 'Strong reach' },
      { tier: 'Depth', status: 'average', label: 'Focus on lasting change' },
    ],
    tip: 'Document specific stories of impact with concrete outcomes and testimonials'
  },
  awards: {
    percentile: 'Competitive Recognition',
    context: 'Having 8 awards demonstrates achievement across multiple domains.',
    schoolTiers: [
      { tier: 'Regional Awards', status: 'competitive', label: 'Good foundation' },
      { tier: 'National Awards', status: 'average', label: 'Aim for 1-2 national' },
      { tier: 'International', status: 'average', label: 'Can be differentiator' },
    ],
    tip: 'Focus on winning 1-2 prestigious national awards rather than many local ones'
  },
};

const MOCK_PRIORITY_ACTIONS = [
  {
    title: 'Start Research Project',
    dimension: 'Academic Differentiation',
    priority: 'high' as const,
    impact: 0.5,
    effort: 'high' as const,
  },
  {
    title: 'Enter National Competition',
    dimension: 'Recognition & Awards',
    priority: 'medium' as const,
    impact: 0.4,
    effort: 'medium' as const,
  },
  {
    title: 'Apply for National Programs',
    dimension: 'Recognition',
    priority: 'low' as const,
    impact: 0.3,
    effort: 'low' as const,
  },
];

const MOCK_SCHOOL_TIERS = [
  { name: 'UC Berkeley', score: 7.8, type: 'safety' as const, color: 'green' },
  { name: 'Northwestern', score: 8.2, type: 'target' as const, color: 'amber' },
  { name: 'MIT', score: 8.9, type: 'reach' as const, color: 'red' },
];

export const InteractivePortfolioCardBento: React.FC<InteractivePortfolioCardBentoProps> = ({
  overallScore,
  tierName,
  percentile,
  metrics,
  achievements,
  tierProgress,
}) => {
  const [expandedMetric, setExpandedMetric] = useState<string | null>(null);

  const metricCards = [
    { title: 'Academic', score: metrics.academic, color: 'blue' as const },
    { title: 'Leadership', score: metrics.leadership, color: 'purple' as const },
    { title: 'Readiness', score: metrics.readiness, color: 'cyan' as const },
    { title: 'Extracurricular', score: metrics.extracurricular, color: 'green' as const },
    { title: 'Course Rigor', score: metrics.courseRigor, color: 'indigo' as const },
    { title: 'Community', score: metrics.community, color: 'orange' as const },
  ];

  // Prepare tier progress data with milestones
  const tierProgressData = {
    ...tierProgress,
    milestonesCompleted: 2,
    milestonesTotal: 6,
    milestones: [
      { text: 'Complete 6 AP courses with 5s', completed: true },
      { text: 'Reach 400+ service hours', completed: true },
      { text: 'Start research project or major competition', completed: false },
    ],
  };

  return (
    <div className="relative">
      {/* Modal for Expanded Metric */}
      <AnimatePresence>
        {expandedMetric && (
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.95, opacity: 0 }}
            className="fixed inset-0 z-50 bg-background/95 backdrop-blur-sm flex items-center justify-center p-6"
            onClick={() => setExpandedMetric(null)}
          >
            <motion.div
              className="bg-background rounded-3xl p-8 max-w-4xl w-full max-h-[90vh] overflow-y-auto depth-layer-4"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="text-center">
                <h2 className="text-4xl font-bold mb-4 bg-gradient-to-r from-primary via-cyan-500 to-primary bg-clip-text text-transparent">
                  {expandedMetric} Insights
                </h2>
                <p className="text-muted-foreground mb-8 text-lg">
                  Detailed analysis and recommendations coming soon...
                </p>
                <div className="space-y-6 text-left">
                  <div className="depth-layer-2 rounded-2xl p-6 bg-gradient-to-br from-primary/5 to-cyan-500/5">
                    <h3 className="font-bold text-lg mb-2">Score Breakdown</h3>
                    <p className="text-muted-foreground">
                      How your score is calculated and what factors contribute to it.
                    </p>
                  </div>
                  <div className="depth-layer-2 rounded-2xl p-6 bg-gradient-to-br from-purple-500/5 to-pink-500/5">
                    <h3 className="font-bold text-lg mb-2">Contributing Factors</h3>
                    <p className="text-muted-foreground">
                      Key activities and achievements that influence this metric.
                    </p>
                  </div>
                  <div className="depth-layer-2 rounded-2xl p-6 bg-gradient-to-br from-green-500/5 to-emerald-500/5">
                    <h3 className="font-bold text-lg mb-2">Recommendations</h3>
                    <p className="text-muted-foreground">
                      Specific actions you can take to improve your score.
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => setExpandedMetric(null)}
                  className="mt-8 px-6 py-3 bg-primary text-primary-foreground rounded-xl font-medium hover:scale-105 transition-transform"
                >
                  Close
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Dashboard Layout */}
      <div className="space-y-6 w-full">
        {/* 1. Unified Score & Metrics Dashboard */}
        <UnifiedScoreDashboard
          score={overallScore}
          tier={tierName}
          percentile={percentile}
          metrics={MOCK_ACADEMIC_METRICS}
          competitiveAnalysis={COMPETITIVE_ANALYSIS}
        />

        {/* 2. Competitive Context */}
        <CompetitiveSpectrumCard
          userScore={8.2}
          userPercentile={percentile}
          schoolTiers={MOCK_SCHOOL_TIERS}
        />

        {/* 3. Top Contributors Card */}
        <TopContributorsCard contributors={MOCK_TOP_CONTRIBUTORS} />

        {/* 4. Metrics Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {metricCards.map((metric) => (
            <BentoMetricCard
              key={metric.title}
              title={metric.title}
              score={metric.score}
              color={metric.color}
              onClick={() => setExpandedMetric(metric.title)}
            />
          ))}
        </div>

        {/* 5. Action & Progress Row */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          <PriorityActionsCard actions={MOCK_PRIORITY_ACTIONS} />
          <TierProgressCard progress={tierProgressData} />
        </div>

        {/* 6. Achievements */}
        <div className="flex justify-center">
          <div className="w-full max-w-md">
            <BentoAchievements achievements={achievements} />
          </div>
        </div>
      </div>
    </div>
  );
};
