import React, { useState } from 'react';
import { BentoMetricCard } from './BentoMetricCard';
import { BentoAchievements } from './BentoAchievements';
import { UnifiedScoreDashboard } from './UnifiedScoreDashboard';
import { PortfolioProgressStanding } from './PortfolioProgressStanding';
import { PortfolioProgressData } from './types/portfolioTypes';
import { Achievement } from '../portfolioInsightsData';
import { motion, AnimatePresence } from 'motion/react';

interface InteractivePortfolioCardBentoProps {
  overallScore: number;
  tierName: string;
  percentile: string;
  metrics: {
    academic: number;
    leadership: number;
    readiness: number;
    community: number;
    extracurricular: number;
    courseRigor: number;
  };
  achievements: Achievement[];
  schoolComparisons?: any[];
  tierProgress: {
    currentTier: string;
    nextTier: string;
    progress: number;
    pointsNeeded: number;
  };
}

// Hard-coded mock data for new components
const MOCK_TOP_CONTRIBUTORS = [
  { name: 'Leadership Impact', dimension: 'Leadership', score: 18, color: 'purple', icon: 'Users' as const },
  { name: 'Community Service', dimension: 'Service', score: 14, color: 'green', icon: 'Heart' as const },
  { name: 'Award Recognition', dimension: 'Awards', score: 12, color: 'amber', icon: 'Award' as const },
];

// Hard-coded mock academic metrics data
// In production, this would come from the user's profile data
const MOCK_ACADEMIC_METRICS = {
  gpa: { 
    weighted: 3.95, 
    unweighted: 3.87 
  },
  sat: 1520,
  act: undefined,
  apScores: { 
    total: 8, 
    average: 4.6, 
    fives: 6 
  },
  classRank: { 
    percentage: 5, 
    outOf: 240,
    rank: 12
  },
  activities: 12,
  hours: 450,
  impactReach: '2.5K',
  awards: 8,
};

// Hard-coded competitive context data for tooltips
// In production, this would be generated by AI based on the user's metrics
const COMPETITIVE_ANALYSIS = {
  gpa: {
    percentile: 'Top 20% Nationally',
    context: 'Your 3.95 weighted GPA is strong for top colleges. Here\'s how it positions you:',
    schoolTiers: [
      { tier: 'Top 50 Schools', status: 'competitive', label: 'Highly competitive' },
      { tier: 'Top 20 Schools', status: 'competitive', label: 'Competitive' },
      { tier: 'Top 10 Schools', status: 'average', label: 'Average (aim for 4.0+)' },
    ],
    tip: 'Focus on maintaining rigor with A\'s in your remaining AP/IB courses'
  },
  sat: {
    percentile: 'Top 5% (98th percentile)',
    context: 'Your 1520 SAT is excellent and meets the middle 50% for most elite schools.',
    schoolExamples: [
      { name: 'MIT', range: '1510-1580', status: 'within' },
      { name: 'Stanford', range: '1470-1570', status: 'strong' },
      { name: 'Berkeley', range: '1330-1530', status: 'above' },
    ],
    tip: 'Your score is strong. Focus efforts on other differentiators like activities'
  },
  apScores: {
    percentile: 'Top 15% Nationally',
    context: 'Taking 8 APs with a 4.6 average and 6 fives demonstrates strong academic rigor.',
    schoolTiers: [
      { tier: 'Top Colleges', status: 'competitive', label: 'Expect 5+ AP courses' },
      { tier: 'Elite Schools', status: 'competitive', label: '8+ APs is ideal' },
    ],
    tip: 'Continue taking challenging APs in your areas of interest to show depth'
  },
  classRank: {
    percentile: 'Top 5% in Class',
    context: 'Being ranked 12 out of 240 students places you in the top 5%, which is excellent.',
    schoolTiers: [
      { tier: 'Top 50 Schools', status: 'competitive', label: 'Well positioned' },
      { tier: 'Top 20 Schools', status: 'competitive', label: 'Competitive' },
      { tier: 'Top 10 Schools', status: 'competitive', label: 'Top 5% is strong' },
    ],
    tip: 'Maintain your rank by staying focused on your most challenging courses'
  },
  activities: {
    percentile: 'Above Average (12 activities)',
    context: 'You have a solid activity count. Quality matters more than quantity:',
    schoolTiers: [
      { tier: '8-15 activities', status: 'competitive', label: 'Ideal range' },
      { tier: 'Focus on depth', status: 'average', label: '2-3 core activities' },
      { tier: 'Leadership', status: 'average', label: 'Look for leadership roles' },
    ],
    tip: 'Admissions prefer "spiky" profiles with deep impact in a few areas over many surface-level involvements'
  },
  hours: {
    percentile: 'Strong Commitment (450 hours)',
    context: 'Your 450 hours of commitment demonstrates sustained dedication.',
    schoolTiers: [
      { tier: 'Most Schools', status: 'competitive', label: 'Expect 200-400 hours' },
      { tier: 'Top Schools', status: 'competitive', label: '400+ hours shows depth' },
    ],
    tip: 'Focus on increasing impact per hour rather than just accumulating more hours'
  },
  impactReach: {
    percentile: 'Substantial Impact',
    context: 'Reaching 2,500 people shows meaningful community engagement.',
    schoolTiers: [
      { tier: 'Breadth', status: 'competitive', label: 'Strong reach' },
      { tier: 'Depth', status: 'average', label: 'Focus on lasting change' },
    ],
    tip: 'Document specific stories of impact with concrete outcomes and testimonials'
  },
  awards: {
    percentile: 'Competitive Recognition',
    context: 'Having 8 awards demonstrates achievement across multiple domains.',
    schoolTiers: [
      { tier: 'Regional Awards', status: 'competitive', label: 'Good foundation' },
      { tier: 'National Awards', status: 'average', label: 'Aim for 1-2 national' },
      { tier: 'International', status: 'average', label: 'Can be differentiator' },
    ],
    tip: 'Focus on winning 1-2 prestigious national awards rather than many local ones'
  },
};

const MOCK_PRIORITY_ACTIONS = [
  {
    title: 'Start Research Project',
    dimension: 'Academic Differentiation',
    priority: 'high' as const,
    impact: 0.5,
    effort: 'high' as const,
  },
  {
    title: 'Enter National Competition',
    dimension: 'Recognition & Awards',
    priority: 'medium' as const,
    impact: 0.4,
    effort: 'medium' as const,
  },
  {
    title: 'Apply for National Programs',
    dimension: 'Recognition',
    priority: 'low' as const,
    impact: 0.3,
    effort: 'low' as const,
  },
];

// Hard-coded mock data for the unified Portfolio Progress & Standing component
// This represents the user's progress over time, competitive standing, and school tier analysis
const MOCK_PORTFOLIO_PROGRESS_DATA: PortfolioProgressData = {
  current: {
    score: 85,
    tier: 'Platinum Achiever',
    percentile: 'Top 15%',
    lastUpdated: '2024-11-23',
  },
  
  // Hard-coded milestone history data showing the user's progress over time
  history: [
    {
      date: 'Aug 2024',
      score: 73,
      milestones: [
        { 
          title: 'Started leadership role', 
          impact: 3, 
          icon: 'award',
          competitiveContext: [
            'Leadership roles demonstrate initiative',
            'Shows ability to influence and organize peers',
            'Valued by selective universities as indicator of future campus contribution',
          ],
          profileImpact: 'Added leadership dimension to your profile, moving you from 70th → 73rd percentile',
        },
      ],
    },
    {
      date: 'Sep 2024',
      score: 78,
      milestones: [
        { 
          title: 'National Merit Semifinalist', 
          impact: 5, 
          icon: 'trophy',
          competitiveContext: [
            'Top 1% of 1.5M PSAT test-takers nationally',
            'Signals strong academic foundation to admissions',
            'Valued by all Top 50 schools',
            'Opens $2,500+ in merit scholarship opportunities',
            'Particularly impactful for STEM programs',
          ],
          profileImpact: 'Moved you from 73rd → 78th percentile nationally. Major credibility boost for academic excellence.',
        },
      ],
    },
    {
      date: 'Oct 2024',
      score: 82,
      milestones: [
        { 
          title: 'Launched community service initiative', 
          impact: 4, 
          icon: 'star',
          competitiveContext: [
            'Demonstrates leadership and social impact',
            'Shows ability to identify problems and create solutions',
            'Valued for demonstrating civic engagement',
            'Indicates potential for campus community contribution',
          ],
          profileImpact: 'Advanced you from 78th → 82nd percentile. Strengthened your leadership narrative.',
        },
      ],
    },
    {
      date: 'Nov 2024',
      score: 85,
      milestones: [
        { 
          title: 'Published research paper', 
          impact: 3, 
          icon: 'medal',
          competitiveContext: [
            'Publication demonstrates scholarly research capability',
            'Shows intellectual curiosity beyond classroom',
            'Valued by research universities',
            'Indicates readiness for college-level research',
          ],
          profileImpact: 'Brought you to 85th percentile. Added research depth to your STEM profile.',
        },
      ],
    },
  ],
  
  projection: {
    targetScore: 92,
    targetDate: 'Mar 2025',
    confidence: 'high',
  },
  
  // Hard-coded data values representing user's competitive standing analysis
  trajectory: {
    growthAnalysis: "Your portfolio has accelerated over the past 3 months with two major national-level achievements. The National Merit Semifinalist recognition was particularly impactful (+5 points) because it signals consistent academic excellence over time—admissions officers know this represents years of preparation, not a one-time performance. Your community service initiative launch (+4 points) reinforces your leadership profile and demonstrates ability to create lasting impact. This upward trajectory suggests strong momentum heading into college applications.",
    scenarios: [
      {
        title: "1 National recognition",
        newPercentile: "92nd percentile",
        requirements: "target: national science competition or prestigious summer program",
        points: 6,
      },
      {
        title: "2 State honors",
        newPercentile: "89th percentile",
        requirements: "target: state debate championship + research publication",
        points: 4,
      },
    ],
  },
  
  competitiveStanding: {
    yourScore: 85,
    local: {
      region: 'California',
      percentile: 'Top 8%',
      yourScore: 85,
      avgScore: 78,
      totalStudents: 450000,
      spectrum: { min: 65, max: 95, position: 85 },
      strengths: "You're significantly above the state average (85 vs 78). Your National Merit status is particularly rare in California (only 2,000 students) and gives you an edge for UC Berkeley, UCLA, and USC admissions.",
      schoolComparisons: [
        {
          school: 'UC Berkeley',
          avgScore: 87,
          gap: -2,
          assessment: 'Competitive range, strong chance with solid essays'
        },
        {
          school: 'UCLA',
          avgScore: 84,
          gap: 1,
          assessment: 'Above average, excellent positioning'
        },
        {
          school: 'USC',
          avgScore: 82,
          gap: 3,
          assessment: 'Strong candidate, likely admit with good essays'
        },
      ],
      actionableInsight: "Your profile is strong for most UC schools. To move from 'competitive' to 'likely' for UC Berkeley, consider adding one more STEM-focused state or national recognition. California's competitive environment means demonstrating distinction beyond grades is critical.",
    },
    national: {
      region: 'United States',
      percentile: 'Top 15%',
      yourScore: 85,
      avgScore: 80,
      totalStudents: 3700000,
      spectrum: { min: 60, max: 100, position: 85 },
      strengths: "Your National Merit Semifinalist status (top 1% of test-takers) and published research position you in the competitive range for selective private universities. You demonstrate both academic excellence and specialized achievement.",
      schoolComparisons: [
        {
          school: 'Northwestern',
          avgScore: 88,
          gap: -3,
          assessment: 'Competitive but not guaranteed. Strong essays + interview critical.'
        },
        {
          school: 'Duke',
          avgScore: 89,
          gap: -4,
          assessment: 'Reach range. Need to differentiate in essays or add achievement.'
        },
        {
          school: 'MIT',
          avgScore: 94,
          gap: -9,
          assessment: 'Significant gap. Would need multiple national STEM honors to close.'
        },
      ],
      gapAnalysis: {
        targetPercentile: 10,
        pointsNeeded: 5,
        scenarios: [
          {
            description: "1 additional national-level recognition in STEM (+8-10 pts), OR",
            points: 9,
          },
          {
            description: "2 state-level recognitions in different domains (+4-5 pts each), OR",
            points: 9,
          },
          {
            description: "1 publication in peer-reviewed journal + 1 national competition finalist (+6 pts + 4 pts)",
            points: 10,
          },
        ],
        timeline: "6 months remaining suggests focusing on 1-2 strategic targets rather than spreading thin.",
      },
      strategicRecommendations: "Given your STEM profile and National Merit status, prioritize national STEM competitions (Regeneron STS, ISEF) or research publication. These have highest ROI for your profile and align with your narrative thread.\n\nYour current positioning makes you competitive for schools like Northwestern and Duke, but you need 1-2 more significant achievements to move into the 'likely' category for these schools. Focus on depth over breadth—one major national recognition is more valuable than multiple local awards.",
    },
    spectrum: {
      min: 70,
      max: 100,
      safetyRange: [70, 80],
      targetRange: [80, 90],
      reachRange: [90, 100],
    },
    tiers: {
      safety: {
        name: 'Safety Tier',
        schools: ['UC Berkeley', 'UCLA', 'USC', 'UC San Diego'],
        avgAdmitScore: 78,
        yourScore: 85,
        gap: 7,
        admissionProbability: { min: 70, max: 85 },
        status: 'strong',
      },
      target: {
        name: 'Target Tier',
        schools: ['Northwestern', 'Duke', 'Brown', 'Cornell'],
        avgAdmitScore: 88,
        yourScore: 85,
        gap: -3,
        admissionProbability: { min: 35, max: 55 },
        status: 'competitive',
        actions: [
          'Start independent research project (+3-4 pts)',
          'Win national competition or award (+2-3 pts)',
          'Launch significant community initiative (+2-3 pts)',
        ],
      },
      reach: {
        name: 'Reach Tier',
        schools: ['MIT', 'Stanford', 'Harvard', 'Princeton'],
        avgAdmitScore: 95,
        yourScore: 85,
        gap: -10,
        admissionProbability: { min: 15, max: 25 },
        status: 'challenging',
        actions: [
          'Achieve international recognition (+5-6 pts)',
          'Develop transformative project with major impact (+4-5 pts)',
          'Secure prestigious fellowship or grant (+3-4 pts)',
          'Publish in top-tier journal (+3-4 pts)',
        ],
      },
    },
  },
};

export const InteractivePortfolioCardBento: React.FC<InteractivePortfolioCardBentoProps> = ({
  overallScore,
  tierName,
  percentile,
  metrics,
  achievements,
  tierProgress,
}) => {
  const [expandedMetric, setExpandedMetric] = useState<string | null>(null);

  const metricCards = [
    { title: 'Academic', score: metrics.academic, color: 'blue' as const },
    { title: 'Leadership', score: metrics.leadership, color: 'purple' as const },
    { title: 'Readiness', score: metrics.readiness, color: 'cyan' as const },
    { title: 'Extracurricular', score: metrics.extracurricular, color: 'green' as const },
    { title: 'Course Rigor', score: metrics.courseRigor, color: 'indigo' as const },
    { title: 'Community', score: metrics.community, color: 'orange' as const },
  ];

  // Prepare tier progress data with milestones
  const tierProgressData = {
    ...tierProgress,
    milestonesCompleted: 2,
    milestonesTotal: 6,
    milestones: [
      { text: 'Complete 6 AP courses with 5s', completed: true },
      { text: 'Reach 400+ service hours', completed: true },
      { text: 'Start research project or major competition', completed: false },
    ],
  };

  return (
    <div className="relative">
      {/* Modal for Expanded Metric */}
      <AnimatePresence>
        {expandedMetric && (
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.95, opacity: 0 }}
            className="fixed inset-0 z-50 bg-background/95 backdrop-blur-sm flex items-center justify-center p-6"
            onClick={() => setExpandedMetric(null)}
          >
            <motion.div
              className="bg-background rounded-3xl p-8 max-w-4xl w-full max-h-[90vh] overflow-y-auto depth-layer-4"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="text-center">
                <h2 className="text-4xl font-bold mb-4 bg-gradient-to-r from-primary via-cyan-500 to-primary bg-clip-text text-transparent">
                  {expandedMetric} Insights
                </h2>
                <p className="text-muted-foreground mb-8 text-lg">
                  Detailed analysis and recommendations coming soon...
                </p>
                <div className="space-y-6 text-left">
                  <div className="depth-layer-2 rounded-2xl p-6 bg-gradient-to-br from-primary/5 to-cyan-500/5">
                    <h3 className="font-bold text-lg mb-2">Score Breakdown</h3>
                    <p className="text-muted-foreground">
                      How your score is calculated and what factors contribute to it.
                    </p>
                  </div>
                  <div className="depth-layer-2 rounded-2xl p-6 bg-gradient-to-br from-purple-500/5 to-pink-500/5">
                    <h3 className="font-bold text-lg mb-2">Contributing Factors</h3>
                    <p className="text-muted-foreground">
                      Key activities and achievements that influence this metric.
                    </p>
                  </div>
                  <div className="depth-layer-2 rounded-2xl p-6 bg-gradient-to-br from-green-500/5 to-emerald-500/5">
                    <h3 className="font-bold text-lg mb-2">Recommendations</h3>
                    <p className="text-muted-foreground">
                      Specific actions you can take to improve your score.
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => setExpandedMetric(null)}
                  className="mt-8 px-6 py-3 bg-primary text-primary-foreground rounded-xl font-medium hover:scale-105 transition-transform"
                >
                  Close
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Dashboard Layout */}
      <div className="space-y-6 w-full">
        {/* 1. Unified Score & Metrics Dashboard */}
        <UnifiedScoreDashboard
          score={overallScore}
          tier={tierName}
          percentile={percentile}
          metrics={MOCK_ACADEMIC_METRICS}
          competitiveAnalysis={COMPETITIVE_ANALYSIS}
        />

        {/* 2. Portfolio Progress & Standing (Combined) */}
        <PortfolioProgressStanding data={MOCK_PORTFOLIO_PROGRESS_DATA} />

        {/* 3. Metrics Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {metricCards.map((metric) => (
            <BentoMetricCard
              key={metric.title}
              title={metric.title}
              score={metric.score}
              color={metric.color}
              onClick={() => setExpandedMetric(metric.title)}
            />
          ))}
        </div>

        {/* 4. Achievements */}
        <div className="flex justify-center">
          <div className="w-full max-w-md">
            <BentoAchievements achievements={achievements} />
          </div>
        </div>
      </div>
    </div>
  );
};
