/**
 * Overused Phrase Database
 *
 * ~200 phrases that trigger AO fatigue in college application essays.
 * Curated from admissions officer feedback, essay review services, and
 * analysis of thousands of application essays.
 *
 * Each entry includes frequency (1-10), fatigue level, a better alternative,
 * and context on why AOs notice it.
 */

import type { PhraseCategory } from './types';

export interface OverusedPhraseEntry {
  phrase: string;
  category: PhraseCategory;
  /** Essay types where this is most problematic */
  essayTypes: string[];
  /** How common (1-10) */
  frequency: number;
  /** AO fatigue level */
  aoFatigueLevel: 'low' | 'medium' | 'high' | 'extreme';
  /** Suggested replacement approach */
  betterAlternative: string;
  /** Why this triggers AO fatigue */
  whyAOsNotice: string;
}

/**
 * Master database of overused phrases in college application essays.
 * Organized by category for efficient lookup.
 */
export const OVERUSED_PHRASE_DATABASE: OverusedPhraseEntry[] = [
  // ============================================================================
  // OPENERS (30 entries)
  // ============================================================================
  {
    phrase: 'ever since i was young',
    category: 'opener',
    essayTypes: ['common_app', 'piq', 'why_us'],
    frequency: 9,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Start with a specific moment or scene that shows your interest, rather than claiming lifelong passion.',
    whyAOsNotice: 'AOs read this opener hundreds of times per cycle. It signals a generic narrative arc rather than authentic reflection.',
  },
  {
    phrase: 'i have always been passionate about',
    category: 'opener',
    essayTypes: ['common_app', 'why_us', 'activity'],
    frequency: 9,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Show the passion through a specific anecdote — let the reader conclude you are passionate from the evidence.',
    whyAOsNotice: 'Telling instead of showing. AOs want to see passion demonstrated, not declared.',
  },
  {
    phrase: 'growing up in',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 8,
    aoFatigueLevel: 'high',
    betterAlternative: 'Open with a scene set in that place — let the reader discover where you grew up through vivid detail.',
    whyAOsNotice: 'Geographic autobiography opening is one of the most common templates AOs encounter.',
  },
  {
    phrase: 'from a young age',
    category: 'opener',
    essayTypes: ['common_app', 'piq', 'activity'],
    frequency: 9,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Anchor in a specific age or moment: "At seven, I..." is far more engaging than the vague "from a young age."',
    whyAOsNotice: 'Vague temporal framing that avoids the harder work of specificity.',
  },
  {
    phrase: 'it was a typical day when',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Drop "typical" — open in the middle of the action. Trust the reader to understand the contrast.',
    whyAOsNotice: 'The "ordinary-turned-extraordinary" setup is immediately recognizable as a template.',
  },
  {
    phrase: 'i never thought i would',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Start with what actually happened, then reveal the surprise through narrative.',
    whyAOsNotice: 'Foreshadowing cliche that telegraphs the essay structure before it begins.',
  },
  {
    phrase: 'as i stood on the stage',
    category: 'opener',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'If using a performance scene, focus on a micro-detail (the texture of the curtain, a sound) rather than the generic stage.',
    whyAOsNotice: 'The "big moment" opener is common and often leads to a predictable narrative arc.',
  },
  {
    phrase: 'the moment that changed everything',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the change happening rather than announcing it. Let the reader feel the shift.',
    whyAOsNotice: 'Overpromises — most essays that start this way describe ordinary turning points.',
  },
  {
    phrase: 'i remember the first time',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Drop the meta-framing — just describe the first time directly as a scene.',
    whyAOsNotice: 'Unnecessary distancing layer between the reader and the experience.',
  },
  {
    phrase: 'when i was five years old',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'If childhood is relevant, open with a sensory detail from that age rather than stating the age.',
    whyAOsNotice: 'Starting in early childhood often leads to a chronological essay that lacks depth.',
  },
  {
    phrase: 'picture this',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Paint the picture directly — strong imagery does not need a verbal invitation.',
    whyAOsNotice: 'Instructing the reader what to do breaks immersion.',
  },
  {
    phrase: 'imagine a world where',
    category: 'opener',
    essayTypes: ['common_app', 'why_us'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the real world you inhabit and what you want to change about it.',
    whyAOsNotice: 'Hypothetical openings delay the personal and specific content AOs are looking for.',
  },
  {
    phrase: 'webster\'s dictionary defines',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 4,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'If a word matters to you, show what it means through your experience — not a dictionary.',
    whyAOsNotice: 'The quintessential cliche opener. AOs may stop reading closely after this.',
  },
  {
    phrase: 'according to merriam-webster',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 3,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Define the concept through your own lived experience.',
    whyAOsNotice: 'Same as the dictionary definition opener — just with a specific dictionary named.',
  },
  {
    phrase: 'i have always been fascinated by',
    category: 'opener',
    essayTypes: ['common_app', 'why_us'],
    frequency: 8,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the fascination in action — describe the moment you fell down the rabbit hole.',
    whyAOsNotice: 'Passive declaration instead of active demonstration.',
  },
  {
    phrase: 'my journey began',
    category: 'opener',
    essayTypes: ['common_app', 'activity'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Drop the "journey" metaphor — begin with a concrete scene from the experience.',
    whyAOsNotice: 'The journey metaphor is so overused it has lost all evocative power.',
  },
  {
    phrase: 'if you had told me a year ago',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the contrast between then and now through parallel scenes, not declarative contrast.',
    whyAOsNotice: 'Formulaic setup for a "growth" narrative that feels pre-packaged.',
  },
  {
    phrase: 'the alarm went off at',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'If routine matters, find a less overused entry point than an alarm clock.',
    whyAOsNotice: 'The "day in the life" opener is extremely common and rarely leads somewhere surprising.',
  },
  {
    phrase: 'i was born in',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'high',
    betterAlternative: 'Start with who you are now — weave in origins only where they illuminate the present.',
    whyAOsNotice: 'Chronological life summary opening that wastes precious word count.',
  },
  {
    phrase: 'as the sun set',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'If the setting matters, use a less cliched natural image to ground the reader.',
    whyAOsNotice: 'Atmospheric cliche that signals a literary-workshop-style essay.',
  },
  {
    phrase: 'it all started when',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Open in the middle of the action — chronological storytelling is rarely the most compelling structure.',
    whyAOsNotice: 'Signals a linear narrative that AOs can predict from the first line.',
  },
  {
    phrase: 'i come from a family of',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show family influence through a specific scene or interaction, not a demographic declaration.',
    whyAOsNotice: 'Generic framing that delays getting to the applicant\'s own story.',
  },
  {
    phrase: 'i am not your typical',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show what makes you distinct — the reader will decide you\'re not typical.',
    whyAOsNotice: 'Claiming uniqueness is paradoxically the most common thing applicants do.',
  },
  {
    phrase: 'my name is',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'AOs already know your name — use the opening for something only you can say.',
    whyAOsNotice: 'Wastes the most valuable real estate in the essay on information already in the application.',
  },
  {
    phrase: 'in a world where',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Ground the reader in your specific world, not a grand abstract one.',
    whyAOsNotice: 'Movie-trailer phrasing that feels performative rather than personal.',
  },
  {
    phrase: 'i stood at the crossroads',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the actual decision and context — the crossroads metaphor is worn out.',
    whyAOsNotice: 'Overused metaphor that signals a predictable structure.',
  },
  {
    phrase: 'the question that keeps me up at night',
    category: 'opener',
    essayTypes: ['common_app', 'why_us'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'State the question directly and show why it matters through your experience.',
    whyAOsNotice: 'Overly dramatic framing for what is usually a normal intellectual interest.',
  },
  {
    phrase: 'i\'ve always been the type of person who',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show, don\'t tell. Let your actions reveal what type of person you are.',
    whyAOsNotice: 'Self-characterization that should be earned through narrative, not stated.',
  },
  {
    phrase: 'when people look at me, they see',
    category: 'opener',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Focus on what you see, not on others\' perceptions — your internal world is more interesting.',
    whyAOsNotice: 'The perception-vs-reality setup is formulaic.',
  },
  {
    phrase: 'three words that describe me',
    category: 'opener',
    essayTypes: ['common_app'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Skip the self-summary — 650 words is your chance to show, not to list adjectives.',
    whyAOsNotice: 'Reduces a complex person to a tagline — feels like a job interview, not an essay.',
  },

  // ============================================================================
  // CLOSERS (25 entries)
  // ============================================================================
  {
    phrase: 'this experience taught me',
    category: 'closer',
    essayTypes: ['common_app', 'piq', 'activity'],
    frequency: 9,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'End with a forward-looking action or a scene that embodies the lesson — don\'t state it.',
    whyAOsNotice: 'The most common closing formula. AOs can predict this ending from the first paragraph.',
  },
  {
    phrase: 'looking back, i realize',
    category: 'closer',
    essayTypes: ['common_app', 'piq'],
    frequency: 8,
    aoFatigueLevel: 'high',
    betterAlternative: 'Stay in the present tense — show how the realization lives in your current actions.',
    whyAOsNotice: 'Retrospective framing that distances the essay from immediate emotional impact.',
  },
  {
    phrase: 'i now know that',
    category: 'closer',
    essayTypes: ['common_app', 'piq'],
    frequency: 8,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show what you now do differently because of what you know — action over declaration.',
    whyAOsNotice: 'Generic wisdom statement that could apply to almost any essay.',
  },
  {
    phrase: 'this is why i want to attend',
    category: 'closer',
    essayTypes: ['why_us'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'End with a specific vision of yourself at the school — what you\'ll do, create, or become.',
    whyAOsNotice: 'Lazy connector that wraps up without genuine school-specific insight.',
  },
  {
    phrase: 'in conclusion',
    category: 'closer',
    essayTypes: ['common_app', 'piq', 'why_us'],
    frequency: 6,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'This is an essay, not a five-paragraph theme. End with resonance, not a signpost.',
    whyAOsNotice: 'Immediately signals inexperience with personal writing. AOs cringe at this.',
  },
  {
    phrase: 'i am excited to',
    category: 'closer',
    essayTypes: ['why_us', 'activity'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the excitement through specificity — name the lab, the professor, the tradition you want to join.',
    whyAOsNotice: 'Empty enthusiasm. Every applicant says they\'re excited.',
  },
  {
    phrase: 'i look forward to',
    category: 'closer',
    essayTypes: ['why_us'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Paint a scene of your future self at the school doing something specific.',
    whyAOsNotice: 'Vague forward-looking statement that lacks vision.',
  },
  {
    phrase: 'i know that i will',
    category: 'closer',
    essayTypes: ['common_app', 'why_us'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Replace certainty with intention and specificity — humility resonates more than confidence.',
    whyAOsNotice: 'Overconfident prediction that lacks the nuance AOs value.',
  },
  {
    phrase: 'and that is who i am',
    category: 'closer',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'If the essay was good, the reader already knows who you are. Trust your narrative.',
    whyAOsNotice: 'Heavy-handed self-summary that undercuts the essay\'s subtlety.',
  },
  {
    phrase: 'this is just the beginning',
    category: 'closer',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show what the next step actually looks like — specificity turns a cliche into a vision.',
    whyAOsNotice: 'Vague motivational language that could end any essay about anything.',
  },
  {
    phrase: 'i cannot wait to',
    category: 'closer',
    essayTypes: ['why_us'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe what you will contribute, not just what you will consume.',
    whyAOsNotice: 'Applicant as consumer, not contributor — AOs want to see what you bring.',
  },
  {
    phrase: 'i will never forget',
    category: 'closer',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show how the memory shapes your present actions — that proves it\'s unforgettable.',
    whyAOsNotice: 'Memory declaration that adds no new information.',
  },
  {
    phrase: 'and i wouldn\'t change a thing',
    category: 'closer',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Be honest — most experiences include things worth changing. Nuance is more compelling.',
    whyAOsNotice: 'Unrealistic positivity that undermines the essay\'s authenticity.',
  },
  {
    phrase: 'i am who i am today because of',
    category: 'closer',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show your current identity in action rather than tracing it to a single cause.',
    whyAOsNotice: 'Reductive causal claim that oversimplifies personal development.',
  },
  {
    phrase: 'my passion will continue to',
    category: 'closer',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Name the specific next project, course, or goal — vague passion claims are forgettable.',
    whyAOsNotice: 'Generic future projection that lacks specificity.',
  },
  {
    phrase: 'i am ready for the next chapter',
    category: 'closer',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe what you will do in the next chapter — readiness alone is not compelling.',
    whyAOsNotice: 'Book metaphor that signals a canned ending.',
  },
  {
    phrase: 'and that has made all the difference',
    category: 'closer',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'high',
    betterAlternative: 'If you\'re quoting Frost, know that every AO has seen this. Find your own words.',
    whyAOsNotice: 'Robert Frost echo that AOs have read thousands of times.',
  },
  {
    phrase: 'i truly believe that',
    category: 'closer',
    essayTypes: ['common_app', 'why_us'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'State the belief directly — "truly" weakens rather than strengthens conviction.',
    whyAOsNotice: 'Filler word "truly" signals insecurity about the claim.',
  },
  {
    phrase: 'to conclude',
    category: 'closer',
    essayTypes: ['common_app', 'piq'],
    frequency: 4,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'End with an image, a question, or a forward action — not a structural signpost.',
    whyAOsNotice: 'Academic essay convention that has no place in personal writing.',
  },
  {
    phrase: 'the lessons i learned will stay with me forever',
    category: 'closer',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show one lesson in action today — that proves it stayed, without the cliche.',
    whyAOsNotice: 'Grandiose permanence claim that lacks specificity.',
  },
  {
    phrase: 'with this experience under my belt',
    category: 'closer',
    essayTypes: ['common_app', 'activity'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the specific skill or perspective gained, not the general accumulation of experience.',
    whyAOsNotice: 'Idiom that trivializes the experience into a resume line.',
  },
  {
    phrase: 'i am more determined than ever',
    category: 'closer',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show determination through your next concrete action, not through superlative claims.',
    whyAOsNotice: 'Escalation language that AOs recognize as formulaic ending.',
  },
  {
    phrase: 'these memories will always hold',
    category: 'closer',
    essayTypes: ['common_app'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the lasting impact through a present-day action or habit.',
    whyAOsNotice: 'Sentimental coda that adds no substance.',
  },
  {
    phrase: 'i have grown so much',
    category: 'closer',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Demonstrate the growth through a before/after contrast — let the reader measure it.',
    whyAOsNotice: 'Vague growth claim that could apply to any essay by any applicant.',
  },
  {
    phrase: 'i am forever grateful',
    category: 'closer',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show gratitude through action — what you do for others because of this experience.',
    whyAOsNotice: 'Saccharine closer that prioritizes niceness over insight.',
  },

  // ============================================================================
  // EMOTIONS (30 entries)
  // ============================================================================
  {
    phrase: 'changed my life forever',
    category: 'emotion',
    essayTypes: ['common_app', 'piq', 'activity'],
    frequency: 9,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Show one specific way your life changed — a new habit, perspective, or relationship.',
    whyAOsNotice: 'The single most overused claim in application essays. Nearly always an exaggeration.',
  },
  {
    phrase: 'opened my eyes',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 9,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Describe what you saw once your eyes were "opened" — the specific new understanding.',
    whyAOsNotice: 'Metaphor so dead it no longer evokes any visual. AOs auto-skip past it.',
  },
  {
    phrase: 'shaped who i am today',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 9,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Show who you are today through current actions and choices, not through causal claims.',
    whyAOsNotice: 'Every applicant claims everything shaped them. The phrase has zero discriminative value.',
  },
  {
    phrase: 'made me realize',
    category: 'emotion',
    essayTypes: ['common_app', 'piq', 'activity'],
    frequency: 8,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the realization unfolding — describe the moment of understanding, not the fact of it.',
    whyAOsNotice: 'Summary statement that replaces the interesting part (the realization itself) with a label.',
  },
  {
    phrase: 'was a turning point',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 8,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the before and after — the reader should feel the turn, not be told about it.',
    whyAOsNotice: 'Announces narrative structure rather than delivering it.',
  },
  {
    phrase: 'completely transformed',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Describe one concrete transformation — a changed behavior, decision, or perspective.',
    whyAOsNotice: 'Hyperbolic language that undermines credibility.',
  },
  {
    phrase: 'a wave of emotions',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Name the specific emotions and their physical manifestations — precision is powerful.',
    whyAOsNotice: 'Vague emotional language that avoids the hard work of specific description.',
  },
  {
    phrase: 'my heart sank',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the physical sensation of disappointment in your own words.',
    whyAOsNotice: 'Stock phrase that AOs have read thousands of times.',
  },
  {
    phrase: 'tears streamed down my face',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'If crying matters to the narrative, describe it in a way unique to that moment.',
    whyAOsNotice: 'Melodramatic cliche that feels performative rather than genuine.',
  },
  {
    phrase: 'i was overwhelmed with',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the overwhelm through your actions and physical responses.',
    whyAOsNotice: 'Telling emotion instead of showing it.',
  },
  {
    phrase: 'i felt a sense of',
    category: 'emotion',
    essayTypes: ['common_app', 'piq', 'activity'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Drop "I felt a sense of" and just describe the feeling directly.',
    whyAOsNotice: 'Distancing language — "a sense of pride" is weaker than simply showing pride.',
  },
  {
    phrase: 'deeply impacted me',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the impact through a changed action or perspective — don\'t label it.',
    whyAOsNotice: 'Impact claims are meaningless without evidence.',
  },
  {
    phrase: 'left a lasting impression',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the impression still at work in your life today.',
    whyAOsNotice: 'Passive phrasing that avoids describing the actual impression.',
  },
  {
    phrase: 'i was filled with pride',
    category: 'emotion',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show what pride looked like in that moment — did you stand taller, call someone, save a screenshot?',
    whyAOsNotice: 'Generic emotional label instead of vivid description.',
  },
  {
    phrase: 'indescribable feeling',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'In an essay, your job is to describe it. Try.',
    whyAOsNotice: 'Ironic in a writing sample — admitting you can\'t describe a feeling is not a good look.',
  },
  {
    phrase: 'a lightbulb went off',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the specific insight and what triggered it.',
    whyAOsNotice: 'Dead metaphor that no longer creates a mental image.',
  },
  {
    phrase: 'gave me chills',
    category: 'emotion',
    essayTypes: ['common_app'],
    frequency: 4,
    aoFatigueLevel: 'low',
    betterAlternative: 'Describe the physical sensation or what caused it in your own words.',
    whyAOsNotice: 'Physical sensation cliche that many essays share.',
  },
  {
    phrase: 'i couldn\'t believe my eyes',
    category: 'emotion',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe what you saw and why it was surprising — the disbelief will come through.',
    whyAOsNotice: 'Melodramatic expression that rarely matches the actual surprise level.',
  },
  {
    phrase: 'it was in that moment that i',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Describe the moment and what happened — skip the "it was in that moment" framing.',
    whyAOsNotice: 'Formulaic moment-of-revelation framing that AOs can spot instantly.',
  },
  {
    phrase: 'my perspective shifted',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show what you saw before and after — let the reader perceive the shift.',
    whyAOsNotice: 'Summary statement that replaces the interesting content with a label.',
  },
  {
    phrase: 'i gained a new appreciation',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show what you appreciate now that you didn\'t before — specificity makes it real.',
    whyAOsNotice: 'Vague appreciation claim that lacks substance.',
  },
  {
    phrase: 'sparked a fire in me',
    category: 'emotion',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the fire — the late nights, the extra projects, the questions you couldn\'t stop asking.',
    whyAOsNotice: 'Fire/spark metaphor is extremely common in passion essays.',
  },
  {
    phrase: 'ignited my passion',
    category: 'emotion',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the passion through action, not through fire metaphors.',
    whyAOsNotice: 'Part of the fire metaphor family that AOs see constantly.',
  },
  {
    phrase: 'opened doors i never knew existed',
    category: 'emotion',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Name the specific doors — the opportunity, the field, the community you discovered.',
    whyAOsNotice: 'Vague opportunity metaphor that avoids specificity.',
  },
  {
    phrase: 'i was moved to tears',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'If the moment deserves tears, the reader should feel it without being told.',
    whyAOsNotice: 'Emotional performance rather than emotional authenticity.',
  },
  {
    phrase: 'forever changed the way i see',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the new way of seeing through a concrete example.',
    whyAOsNotice: 'Permanence claims are almost always hyperbolic.',
  },
  {
    phrase: 'i found my calling',
    category: 'emotion',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show what you do and why it matters to you — "calling" is a loaded term for a 17-year-old.',
    whyAOsNotice: 'Grand claim that can feel premature and performative.',
  },
  {
    phrase: 'broke down my walls',
    category: 'emotion',
    essayTypes: ['common_app', 'piq'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the vulnerability you showed in specific terms.',
    whyAOsNotice: 'Therapy-speak metaphor that has entered common overuse.',
  },
  {
    phrase: 'gave me a sense of purpose',
    category: 'emotion',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the purpose through your actions and decisions, not through declaration.',
    whyAOsNotice: 'Vague purpose claim that lacks the specificity AOs look for.',
  },
  {
    phrase: 'i was blown away',
    category: 'emotion',
    essayTypes: ['common_app', 'why_us'],
    frequency: 4,
    aoFatigueLevel: 'low',
    betterAlternative: 'Describe the specifics of what amazed you — the blown-away feeling will come through.',
    whyAOsNotice: 'Casual hyperbole that undermines essay tone.',
  },

  // ============================================================================
  // ACHIEVEMENT (25 entries)
  // ============================================================================
  {
    phrase: 'i was honored to receive',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Skip the honor and describe what you did to earn it — or better, what it enabled you to do next.',
    whyAOsNotice: 'Resume language in essay form. Awards are listed elsewhere in the application.',
  },
  {
    phrase: 'through hard work and dedication',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 8,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Show the hard work — the 5am practices, the failed experiments, the rewrites.',
    whyAOsNotice: 'The single most generic achievement claim. Says nothing specific about the applicant.',
  },
  {
    phrase: 'against all odds',
    category: 'achievement',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Name the specific obstacles — "against all odds" is a movie tagline, not an essay.',
    whyAOsNotice: 'Melodramatic framing that rarely matches the actual difficulty described.',
  },
  {
    phrase: 'i achieved my goal of',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'The essay should be about the process and what you learned, not the achievement checkbox.',
    whyAOsNotice: 'Goal-achievement framing turns a personal essay into a progress report.',
  },
  {
    phrase: 'my proudest accomplishment',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the accomplishment and let the pride show through your voice and detail.',
    whyAOsNotice: 'Ranking achievements feels transactional rather than reflective.',
  },
  {
    phrase: 'i set out to',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the motivation emerging from a situation, not a formal goal-setting moment.',
    whyAOsNotice: 'Quest-narrative framing that is predictable (set out → obstacles → achieve).',
  },
  {
    phrase: 'went above and beyond',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe specifically what you did that others didn\'t — that is "above and beyond."',
    whyAOsNotice: 'Performance review language that feels generic and self-congratulatory.',
  },
  {
    phrase: 'i pushed myself to the limit',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show what the limit looked like — physical, emotional, intellectual. Be specific.',
    whyAOsNotice: 'Sports-commentary language that rarely delivers on its dramatic promise.',
  },
  {
    phrase: 'the countless hours i spent',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Count them — "200 hours in the lab" is more compelling than "countless hours."',
    whyAOsNotice: 'Vague time investment claim that every applicant makes.',
  },
  {
    phrase: 'i was selected as',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Focus on what you did in the role, not the selection itself.',
    whyAOsNotice: 'Passive voice that emphasizes being chosen over what you did with the opportunity.',
  },
  {
    phrase: 'it was worth it',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show why it was worth it through a specific moment of payoff.',
    whyAOsNotice: 'Flat conclusion to what should be a rich narrative.',
  },
  {
    phrase: 'i received recognition for',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Skip the recognition and write about the work itself — the honors list covers awards.',
    whyAOsNotice: 'Duplicates information from the activities/honors sections.',
  },
  {
    phrase: 'exceeded my expectations',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the surprise specifically — what happened that you didn\'t expect?',
    whyAOsNotice: 'Customer-review language that feels impersonal.',
  },
  {
    phrase: 'blood, sweat, and tears',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'high',
    betterAlternative: 'Describe one specific moment of difficulty in vivid detail.',
    whyAOsNotice: 'Churchill cliche that AOs have read thousands of times.',
  },
  {
    phrase: 'i worked tirelessly',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the tirelessness through a scene — working at 2am, skipping social events, iterating endlessly.',
    whyAOsNotice: 'Claim without evidence — everyone says they worked tirelessly.',
  },
  {
    phrase: 'rose to the challenge',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the challenge and what you specifically did — don\'t use the shorthand.',
    whyAOsNotice: 'Motivational poster language.',
  },
  {
    phrase: 'with determination and perseverance',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show determination through one key decision you made when quitting would have been easier.',
    whyAOsNotice: 'Abstract virtues listed rather than demonstrated.',
  },
  {
    phrase: 'i proved to myself that',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the proof — the new behavior, the next challenge you took on because of it.',
    whyAOsNotice: 'Self-validation narrative that can feel self-centered.',
  },
  {
    phrase: 'i was the first in my family to',
    category: 'achievement',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'low',
    betterAlternative: 'This can be powerful if it leads to reflection — but don\'t use it as a badge. Show the emotional complexity.',
    whyAOsNotice: 'Legitimate context, but overused as a lead-in without depth.',
  },
  {
    phrase: 'overcame every obstacle',
    category: 'achievement',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Name one obstacle and how you specifically navigated it.',
    whyAOsNotice: 'Totalizing claim that sounds like a superhero tagline.',
  },
  {
    phrase: 'i didn\'t let anything stop me',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show one moment where something almost did stop you and what you did about it.',
    whyAOsNotice: 'Invincibility claim that lacks the vulnerability AOs value.',
  },
  {
    phrase: 'my hard work paid off',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the payoff moment in vivid detail — the hard work should already be evident.',
    whyAOsNotice: 'Transactional framing that reduces a rich experience to an investment.',
  },
  {
    phrase: 'i was able to achieve',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Simply state what you achieved — "I was able to" adds nothing.',
    whyAOsNotice: 'Weak filler phrase that dilutes the achievement.',
  },
  {
    phrase: 'i stepped up to the plate',
    category: 'achievement',
    essayTypes: ['common_app', 'activity'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the specific action you took when leadership was needed.',
    whyAOsNotice: 'Sports cliche that feels imprecise.',
  },
  {
    phrase: 'failure is not an option',
    category: 'achievement',
    essayTypes: ['common_app'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Failure is always an option — show how you dealt with the risk of it.',
    whyAOsNotice: 'Movie-quote mentality that signals lack of nuance about failure.',
  },

  // ============================================================================
  // VULNERABILITY (20 entries)
  // ============================================================================
  {
    phrase: 'i hit rock bottom',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'high',
    betterAlternative: 'Describe the lowest point with specificity — what did rock bottom actually look like for you?',
    whyAOsNotice: 'Dramatic shorthand that avoids the hard descriptive work.',
  },
  {
    phrase: 'i felt lost and alone',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the isolation through a specific scene — eating alone, staring at a phone with no notifications.',
    whyAOsNotice: 'Generic loneliness claim that many essays share verbatim.',
  },
  {
    phrase: 'everything fell apart',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'high',
    betterAlternative: 'Name what fell apart — the specifics are what make your story yours.',
    whyAOsNotice: 'Totalizing disaster claim that is rarely literally true.',
  },
  {
    phrase: 'i struggled with',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the struggle in action — a scene, a decision, a failed attempt.',
    whyAOsNotice: 'Summary statement that labels instead of demonstrates.',
  },
  {
    phrase: 'i didn\'t know who i was',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the confusion through contradictions in your behavior or conflicting desires.',
    whyAOsNotice: 'Identity-crisis claim that most teenagers share — needs specificity to stand out.',
  },
  {
    phrase: 'i was afraid to be myself',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show a moment of hiding vs. a moment of revealing — the contrast is the story.',
    whyAOsNotice: 'Authenticity claim that is paradoxically generic.',
  },
  {
    phrase: 'i felt like giving up',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the moment of near-surrender — what the quitting thought looked like and what kept you going.',
    whyAOsNotice: 'Sets up a predictable "but I didn\'t" resolution.',
  },
  {
    phrase: 'behind my smile was',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the contrast between public and private self through a specific scene.',
    whyAOsNotice: 'Hidden-pain trope that many essays share.',
  },
  {
    phrase: 'i put on a brave face',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the performance and what it cost you — the specific lie or mask.',
    whyAOsNotice: 'Cliche that signals vulnerability without delivering it.',
  },
  {
    phrase: 'i was battling demons',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Name the specific challenge — vague "demons" can feel appropriative of serious mental health struggles.',
    whyAOsNotice: 'Dramatic metaphor that avoids specificity.',
  },
  {
    phrase: 'i had to learn to love myself',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show what self-acceptance looks like in practice — a specific choice you make now.',
    whyAOsNotice: 'Self-help language that can feel rehearsed.',
  },
  {
    phrase: 'it was the hardest thing i\'ve ever done',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the difficulty through specifics — ranking experiences undermines the narrative.',
    whyAOsNotice: 'Superlative claim that many applicants make about very different things.',
  },
  {
    phrase: 'i was at my lowest point',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe what the lowest point looked like — the specific day, feeling, or realization.',
    whyAOsNotice: 'Summary that skips the vivid detail AOs need to connect.',
  },
  {
    phrase: 'i finally found the courage to',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the moment you acted despite fear — the reader should feel the courage, not be told about it.',
    whyAOsNotice: 'Courage-narrative setup that signals a predictable resolution.',
  },
  {
    phrase: 'i bottled up my emotions',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the bottling through behavior — snapping at a friend, avoiding a topic, overworking.',
    whyAOsNotice: 'Psychology-adjacent cliche that many essays share.',
  },
  {
    phrase: 'nobody understood what i was going through',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show a specific moment of misunderstanding — a conversation where they missed the point.',
    whyAOsNotice: 'Isolation claim that is very common and needs specificity to resonate.',
  },
  {
    phrase: 'i wore a mask every day',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the mask with precision — what did you say that you didn\'t mean?',
    whyAOsNotice: 'Mask metaphor that many identity essays share.',
  },
  {
    phrase: 'my world came crashing down',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'high',
    betterAlternative: 'Describe the specific moment of crisis — the phone call, the conversation, the realization.',
    whyAOsNotice: 'Catastrophe metaphor that is dramatic but vague.',
  },
  {
    phrase: 'i had to pick up the pieces',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Name the first piece you picked up — the first small step toward recovery.',
    whyAOsNotice: 'Recovery cliche that skips the specific and interesting details.',
  },
  {
    phrase: 'i felt invisible',
    category: 'vulnerability',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show a moment of being overlooked — the specifics make invisibility real.',
    whyAOsNotice: 'Common loneliness/marginalization claim that needs evidence.',
  },

  // ============================================================================
  // MOTIVATION (25 entries)
  // ============================================================================
  {
    phrase: 'i want to make a difference',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us', 'piq'],
    frequency: 9,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Name the specific difference — what will change, for whom, and how will you measure it?',
    whyAOsNotice: 'The most generic motivation claim in college essays. Every applicant says this.',
  },
  {
    phrase: 'i am determined to',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show determination through past action — then the future claim becomes credible.',
    whyAOsNotice: 'Declaration of intent without evidence of follow-through.',
  },
  {
    phrase: 'my dream has always been',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show how the dream evolved and became more specific over time.',
    whyAOsNotice: 'Unchanging-dream claim that suggests lack of growth or reflection.',
  },
  {
    phrase: 'i want to change the world',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us'],
    frequency: 8,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Pick one corner of the world and show how you\'ve already started changing it.',
    whyAOsNotice: 'Grandiose claim that AOs have read tens of thousands of times.',
  },
  {
    phrase: 'i aspire to',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show aspiration through action already taken — aspiring alone is not distinctive.',
    whyAOsNotice: 'Passive aspiration without evidence of action.',
  },
  {
    phrase: 'i am driven by my desire to',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the drive — describe a time you pursued this desire beyond what was required.',
    whyAOsNotice: 'Self-analysis that tells rather than shows.',
  },
  {
    phrase: 'i want to give back to my community',
    category: 'motivation',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Name the community, the specific need, and what you will do — "give back" is vague.',
    whyAOsNotice: 'Generic service motivation that lacks specificity.',
  },
  {
    phrase: 'my ultimate goal is to',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the next concrete step, not the ultimate destination.',
    whyAOsNotice: 'Grand-plan language that feels disconnected from present reality.',
  },
  {
    phrase: 'i want to be a voice for',
    category: 'motivation',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show how you have already amplified others\' voices — advocacy is proven through action.',
    whyAOsNotice: 'Savior-adjacent phrasing that can feel presumptuous.',
  },
  {
    phrase: 'education is the key to',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us'],
    frequency: 6,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show how education specifically unlocked something for you — avoid the platitude.',
    whyAOsNotice: 'Graduation-speech platitude that adds no personal insight.',
  },
  {
    phrase: 'i am committed to',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the commitment through a sacrifice or trade-off you\'ve made.',
    whyAOsNotice: 'Easy claim — commitment is proven through sustained action, not declaration.',
  },
  {
    phrase: 'i hope to one day',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Replace hope with plan — what are you doing now to make "one day" happen?',
    whyAOsNotice: 'Passive hoping lacks the agency AOs look for.',
  },
  {
    phrase: 'i feel a responsibility to',
    category: 'motivation',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show responsibility through action — filing the taxes, staying late, showing up when no one else did.',
    whyAOsNotice: 'Moral-obligation framing that can feel performative.',
  },
  {
    phrase: 'i strive to make an impact',
    category: 'motivation',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe one specific impact you\'ve already made — striving alone is not a differentiator.',
    whyAOsNotice: 'Vague impact language that avoids committing to specifics.',
  },
  {
    phrase: 'i want to inspire others',
    category: 'motivation',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show a moment when someone was inspired by your action — not your intention to inspire.',
    whyAOsNotice: 'Claiming to want to inspire is very common and rarely supported.',
  },
  {
    phrase: 'my passion drives me',
    category: 'motivation',
    essayTypes: ['common_app', 'activity'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the drive in action — describe what you do at midnight because you can\'t stop.',
    whyAOsNotice: 'Self-diagnosis of motivation that should be shown, not stated.',
  },
  {
    phrase: 'i believe that everyone deserves',
    category: 'motivation',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Move from belief to action — what have you done about this belief?',
    whyAOsNotice: 'Moral statement that is hard to disagree with and therefore not distinctive.',
  },
  {
    phrase: 'i want to use my education to',
    category: 'motivation',
    essayTypes: ['why_us'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Name specific courses, professors, or resources — vague "education" isn\'t a "Why Us" answer.',
    whyAOsNotice: 'Generic in a "Why Us" context where specificity is everything.',
  },
  {
    phrase: 'i refuse to be a bystander',
    category: 'motivation',
    essayTypes: ['common_app', 'piq'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show a time you intervened — the action is more compelling than the refusal statement.',
    whyAOsNotice: 'Virtue signaling that needs evidence to land.',
  },
  {
    phrase: 'ever since that day, i knew',
    category: 'motivation',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the knowing through subsequent choices — the reader should see the pattern.',
    whyAOsNotice: 'Epiphany-from-single-event framing that oversimplifies.',
  },
  {
    phrase: 'i want to leave my mark on',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the mark specifically — what will be different because you were there?',
    whyAOsNotice: 'Legacy language that is vague and self-aggrandizing.',
  },
  {
    phrase: 'it is my mission to',
    category: 'motivation',
    essayTypes: ['common_app'],
    frequency: 4,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the mission in action — declarations of mission are cheap.',
    whyAOsNotice: 'Corporate mission-statement language in a personal essay.',
  },
  {
    phrase: 'this fueled my motivation',
    category: 'motivation',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show what you did next because of this motivation — the fuel metaphor is tired.',
    whyAOsNotice: 'Fuel/fire metaphors are extremely common in motivation essays.',
  },
  {
    phrase: 'i am passionate about making',
    category: 'motivation',
    essayTypes: ['common_app', 'why_us'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the making — describe a project, initiative, or effort already underway.',
    whyAOsNotice: 'Passion declaration combined with vague future plans.',
  },
  {
    phrase: 'i see myself as someone who',
    category: 'motivation',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show yourself being that someone through a scene or action.',
    whyAOsNotice: 'Self-perception statement that should be demonstrated, not stated.',
  },

  // ============================================================================
  // REFLECTION (25 entries)
  // ============================================================================
  {
    phrase: 'i learned that',
    category: 'reflection',
    essayTypes: ['common_app', 'piq', 'activity'],
    frequency: 9,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Show the learning through changed behavior — let the reader infer the lesson.',
    whyAOsNotice: 'The single most common reflection phrase. Appears in a vast majority of essays.',
  },
  {
    phrase: 'i discovered that',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the discovery unfolding — the moment of realization is more interesting than the fact.',
    whyAOsNotice: 'Summary that skips the most compelling part of the narrative.',
  },
  {
    phrase: 'i came to understand',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Dramatize the shift in understanding — show your old view, the catalyst, and the new view.',
    whyAOsNotice: 'Passive understanding claim that lacks narrative energy.',
  },
  {
    phrase: 'in hindsight',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Weave the retrospective insight into the narrative rather than stepping out of it.',
    whyAOsNotice: 'Meta-commentary that breaks narrative flow.',
  },
  {
    phrase: 'this made me who i am',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 8,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show who you are through present actions — the reader doesn\'t need the causal claim.',
    whyAOsNotice: 'Every essay makes this claim about different experiences. It has no discriminative value.',
  },
  {
    phrase: 'i realized the importance of',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the importance through a consequence — what went wrong when it was missing, or right when present.',
    whyAOsNotice: 'Lesson-summary that replaces specific reflection with generic wisdom.',
  },
  {
    phrase: 'looking at the bigger picture',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the bigger picture specifically — what systems, connections, or patterns do you see?',
    whyAOsNotice: 'Vague meta-awareness claim.',
  },
  {
    phrase: 'it opened my mind',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show what entered your mind once it was "open" — the specific new thought or perspective.',
    whyAOsNotice: 'Sibling of "opened my eyes" — equally dead as a metaphor.',
  },
  {
    phrase: 'i am a stronger person because of',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the strength — what can you handle now that you couldn\'t before?',
    whyAOsNotice: 'Strength claim that needs evidence to be persuasive.',
  },
  {
    phrase: 'it taught me the value of',
    category: 'reflection',
    essayTypes: ['common_app', 'piq', 'activity'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show how you now apply this value — action is more convincing than declaration.',
    whyAOsNotice: 'Lesson-extraction formula that AOs see in a majority of essays.',
  },
  {
    phrase: 'i grew as a person',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 8,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Name the specific growth — are you more empathetic? More curious? More disciplined? Show it.',
    whyAOsNotice: 'The most generic growth claim possible. Adds zero information.',
  },
  {
    phrase: 'i see things differently now',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the old and new perspective through a concrete comparison.',
    whyAOsNotice: 'Vague transformation claim.',
  },
  {
    phrase: 'it was a defining moment',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Let the reader decide if it was defining — your job is to make the moment vivid.',
    whyAOsNotice: 'Announcing significance rather than demonstrating it.',
  },
  {
    phrase: 'what i took away from this',
    category: 'reflection',
    essayTypes: ['common_app', 'piq', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Weave the takeaway into the narrative rather than extracting it as a separate lesson.',
    whyAOsNotice: 'Breaks from narrative to summarize — feels like a book report.',
  },
  {
    phrase: 'this experience has shown me that',
    category: 'reflection',
    essayTypes: ['common_app', 'piq', 'activity'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show through narrative what the experience revealed — don\'t break into explicit lesson mode.',
    whyAOsNotice: 'Lesson-delivery formula that signals an unsubtle essay.',
  },
  {
    phrase: 'i have come to realize that',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Drop the meta-framing — state the realization and show what it changed.',
    whyAOsNotice: 'Distancing phrase that delays the actual insight.',
  },
  {
    phrase: 'it broadened my horizons',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'high',
    betterAlternative: 'Name the specific new horizon — a field, a community, a way of thinking.',
    whyAOsNotice: 'Travel-brochure language that is extremely common.',
  },
  {
    phrase: 'i matured in ways i never expected',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Name the unexpected maturation — what surprised you about how you changed?',
    whyAOsNotice: 'Vague maturation claim that lacks specificity.',
  },
  {
    phrase: 'i have a deeper understanding of',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the depth — what nuance do you see now that you didn\'t before?',
    whyAOsNotice: 'Depth claim without evidence of what the depth contains.',
  },
  {
    phrase: 'in retrospect',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Weave the backward look into the forward narrative rather than flagging it.',
    whyAOsNotice: 'Academic transition that breaks personal essay flow.',
  },
  {
    phrase: 'failure taught me more than success',
    category: 'reflection',
    essayTypes: ['common_app'],
    frequency: 6,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show one specific lesson from failure and how it changed your next attempt.',
    whyAOsNotice: 'Fortune-cookie wisdom that many essays state as if it were novel.',
  },
  {
    phrase: 'not everything is black and white',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the nuance — describe the grey you discovered and why it matters.',
    whyAOsNotice: 'Moral-complexity claim that is itself simplistic.',
  },
  {
    phrase: 'it made me appreciate',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the appreciation through action — what do you do differently now?',
    whyAOsNotice: 'Passive appreciation claim that lacks behavioral evidence.',
  },
  {
    phrase: 'i learned to embrace',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the embrace — a moment when you chose to accept rather than resist.',
    whyAOsNotice: 'Acceptance narrative that can feel tidy without the messy details.',
  },
  {
    phrase: 'stepping outside my comfort zone',
    category: 'reflection',
    essayTypes: ['common_app', 'piq'],
    frequency: 8,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Describe the specific zone and the step — what felt uncomfortable and why you did it anyway.',
    whyAOsNotice: 'One of the most overused phrases in college admissions. AOs see it multiple times per day.',
  },

  // ============================================================================
  // TRANSITIONS (20 entries)
  // ============================================================================
  {
    phrase: 'little did i know',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 8,
    aoFatigueLevel: 'extreme',
    betterAlternative: 'Trust the reader to appreciate the irony without this wink-to-camera moment.',
    whyAOsNotice: 'Dramatic irony flag that AOs see constantly. Breaks the fourth wall.',
  },
  {
    phrase: 'fast forward to',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Use a scene break or a transitional detail — "Three years later" or a specific date.',
    whyAOsNotice: 'VCR-era transition that signals a time-skip cliche.',
  },
  {
    phrase: 'that\'s when everything changed',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 7,
    aoFatigueLevel: 'high',
    betterAlternative: 'Show the change happening — the reader should feel the shift, not be told about it.',
    whyAOsNotice: 'Dramatic transition that overpromises and announces rather than delivers.',
  },
  {
    phrase: 'but then something happened',
    category: 'transition',
    essayTypes: ['common_app'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Just describe what happened — the "but then" creates artificial suspense.',
    whyAOsNotice: 'Cliffhanger technique that works in TV, not in essays.',
  },
  {
    phrase: 'however, things took a turn',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the turn directly — the reader doesn\'t need a warning.',
    whyAOsNotice: 'Narrative direction-change signal that is predictable.',
  },
  {
    phrase: 'and then it hit me',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the thought itself — the hitting metaphor adds nothing.',
    whyAOsNotice: 'Insight-as-physical-impact metaphor that is extremely common.',
  },
  {
    phrase: 'the next thing i knew',
    category: 'transition',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Transition with a specific detail from the next scene rather than flagging the time jump.',
    whyAOsNotice: 'Narrative shortcut that skips interesting connective material.',
  },
  {
    phrase: 'as time went on',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Name the time — "By sophomore year" or "Six months later" is more grounding.',
    whyAOsNotice: 'Vague temporal transition that wastes words.',
  },
  {
    phrase: 'that was the moment i decided',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the decision and its first consequence — the moment will speak for itself.',
    whyAOsNotice: 'Decision-announcement that tells instead of showing.',
  },
  {
    phrase: 'what i didn\'t expect was',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Simply describe the unexpected thing — the surprise will register.',
    whyAOsNotice: 'Expectation-subversion flag that is predictable.',
  },
  {
    phrase: 'suddenly, everything clicked',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe what clicked and why — the process of understanding is more interesting.',
    whyAOsNotice: 'Instant-insight claim that oversimplifies learning.',
  },
  {
    phrase: 'from that day forward',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the change in a specific next action rather than declaring a permanent shift.',
    whyAOsNotice: 'Permanence claim that is rarely tested in the essay.',
  },
  {
    phrase: 'it was at that point',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Drop the pointer — just describe what happened at that point.',
    whyAOsNotice: 'Unnecessary framing that delays content.',
  },
  {
    phrase: 'as i reflect on',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 6,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Reflect without announcing reflection — the reader can tell you\'re reflecting.',
    whyAOsNotice: 'Meta-commentary that breaks narrative immersion.',
  },
  {
    phrase: 'years later',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'low',
    betterAlternative: 'Specify the time gap — "Two years later" or "By the time I turned sixteen."',
    whyAOsNotice: 'Vague time skip that can feel like a lazy transition.',
  },
  {
    phrase: 'little by little',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'low',
    betterAlternative: 'Show the increments — name two or three specific milestones in the gradual change.',
    whyAOsNotice: 'Vague gradual-change marker.',
  },
  {
    phrase: 'before i knew it',
    category: 'transition',
    essayTypes: ['common_app'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Describe the passage of time through a concrete detail.',
    whyAOsNotice: 'Time-compression cliche.',
  },
  {
    phrase: 'i began to see',
    category: 'transition',
    essayTypes: ['common_app', 'piq'],
    frequency: 5,
    aoFatigueLevel: 'low',
    betterAlternative: 'Show what you saw — the vision itself is more compelling than the onset of seeing.',
    whyAOsNotice: 'Sight metaphor for understanding that is very common.',
  },
  {
    phrase: 'this was just the beginning',
    category: 'transition',
    essayTypes: ['common_app', 'activity'],
    frequency: 5,
    aoFatigueLevel: 'medium',
    betterAlternative: 'Show the next step — let the reader see that there\'s more to come.',
    whyAOsNotice: 'Forward-looking tease that is structurally common.',
  },
  {
    phrase: 'and just like that',
    category: 'transition',
    essayTypes: ['common_app'],
    frequency: 4,
    aoFatigueLevel: 'low',
    betterAlternative: 'Describe the transition through detail rather than this colloquial marker.',
    whyAOsNotice: 'Casual transition that can feel flip about important moments.',
  },
];

/** Pre-built index for fast lookup by category */
export function getPhrasesByCategory(category: PhraseCategory): OverusedPhraseEntry[] {
  return OVERUSED_PHRASE_DATABASE.filter((entry) => entry.category === category);
}

/** Get all phrases sorted by frequency (most overused first) */
export function getPhrasesByFrequency(): OverusedPhraseEntry[] {
  return [...OVERUSED_PHRASE_DATABASE].sort((a, b) => b.frequency - a.frequency);
}

/** Get only extreme-fatigue phrases */
export function getExtremeFatiguePhrases(): OverusedPhraseEntry[] {
  return OVERUSED_PHRASE_DATABASE.filter((entry) => entry.aoFatigueLevel === 'extreme');
}
