/**
 * EndOfReview — Phase 10 §2.8 / §8 warm summary panel.
 *
 * Rules enforced (non-negotiable):
 *   - NO confetti, NO celebratory language, NO "You did it!" headline,
 *     NO aggregate score, NO time-on-task statistic. §2.8 explicitly
 *     rejects every one of those.
 *   - The tone is a teacher closing a lesson: specific, forward-looking,
 *     calm.
 *   - Three sections:
 *       1. Heading: "You've reviewed all feedback."
 *       2. Summary prose (2–3 sentences, from L3.75 holistic synthesis).
 *       3. Primary CTA: `Most important: ¶N s M → {type}`.
 *       + secondary row: `Return to overview`.
 *   - Fade-in on mount over 400ms.
 *   - prefers-reduced-motion: instant mount, no fade.
 */

import { memo, useMemo } from 'react';
import { motion } from 'motion/react';

import { TIER_META, TYPOGRAPHY } from '../tokens';
import type { EssayProfile } from '../types/profile';

export interface EndOfReviewProps {
  readonly profile: EssayProfile;
  /**
   * Sentence ID to route to on primary CTA. If null, we degrade to a
   * secondary-only layout (nothing to start with — fits §8's "no fake
   * CTA" rule: we do NOT invent a target).
   */
  readonly topPrioritySentenceId: string | null;
  /**
   * Host supplies the prose summary directly. Phase 10 §2.8 has this
   * generated by a final LLM call; the demo passes through a derived
   * string from `holisticSynthesis`. Multi-sentence OK; we render it
   * verbatim inside a `<p>`.
   */
  readonly summaryProse: string;
  readonly onJumpToTop: () => void;
  readonly onReturnToOverview: () => void;
  readonly reducedMotion: boolean;
}

function EndOfReviewImpl(props: EndOfReviewProps) {
  const {
    profile,
    topPrioritySentenceId,
    summaryProse,
    onJumpToTop,
    onReturnToOverview,
    reducedMotion,
  } = props;

  const topTarget = useMemo(() => {
    if (!topPrioritySentenceId) return null;
    const sentence = profile.sentences.find(
      (s) => s.id === topPrioritySentenceId,
    );
    if (!sentence) return null;
    const annotation = profile.annotations.find(
      (a) => a.sentenceId === sentence.id,
    );
    return { sentence, annotation };
  }, [profile, topPrioritySentenceId]);

  const ctaLabel = useMemo(() => {
    if (!topTarget) return null;
    const { sentence, annotation } = topTarget;
    const pref = `¶${sentence.paragraphIndex + 1} s${sentence.indexWithinParagraph + 1}`;
    const typeLabel = annotation?.type ?? TIER_META[sentence.tier].label.toLowerCase();
    return `Most important: ${pref} — ${typeLabel} →`;
  }, [topTarget]);

  const initial = reducedMotion ? { opacity: 1 } : { opacity: 0 };
  const animate = { opacity: 1 };
  const transition = reducedMotion
    ? { duration: 0 }
    : { duration: 0.4, ease: 'easeOut' as const };

  return (
    <motion.section
      initial={initial}
      animate={animate}
      transition={transition}
      aria-label="Review complete — warm summary"
      style={{
        padding: `${TYPOGRAPHY.panelPaddingTop} ${TYPOGRAPHY.panelPaddingX} ${TYPOGRAPHY.panelPaddingBottom}`,
        fontFamily: TYPOGRAPHY.families.sans,
        maxWidth: `${TYPOGRAPHY.maxProseCh}ch`,
        display: 'flex',
        flexDirection: 'column',
        gap: 20,
      }}
    >
      <header>
        <h2
          style={{
            margin: 0,
            fontFamily: TYPOGRAPHY.families.sans,
            fontSize: '20px',
            fontWeight: TYPOGRAPHY.weight.semibold,
            color: 'hsl(220 20% 20%)',
            letterSpacing: '-0.01em',
          }}
        >
          You&rsquo;ve reviewed all feedback.
        </h2>
      </header>

      <p
        style={{
          margin: 0,
          fontFamily: TYPOGRAPHY.families.serif,
          fontSize: TYPOGRAPHY.size.critique,
          lineHeight: TYPOGRAPHY.lineHeight.serifProse,
          color: 'hsl(220 20% 25%)',
        }}
      >
        {summaryProse}
      </p>

      {ctaLabel ? (
        <button
          type="button"
          onClick={onJumpToTop}
          style={{
            alignSelf: 'flex-start',
            padding: '10px 16px',
            borderRadius: 8,
            border: '1px solid hsl(145 35% 45%)',
            background: 'hsl(145 35% 45%)',
            color: 'white',
            fontFamily: TYPOGRAPHY.families.sans,
            fontSize: '14px',
            fontWeight: TYPOGRAPHY.weight.semibold,
            letterSpacing: TYPOGRAPHY.tracking.meta,
            cursor: 'pointer',
          }}
        >
          {ctaLabel}
        </button>
      ) : null}

      <div>
        <button
          type="button"
          onClick={onReturnToOverview}
          style={{
            padding: 0,
            border: 'none',
            background: 'transparent',
            color: 'hsl(220 20% 45%)',
            fontFamily: TYPOGRAPHY.families.sans,
            fontSize: TYPOGRAPHY.size.panelHeader,
            letterSpacing: TYPOGRAPHY.tracking.meta,
            textDecoration: 'underline',
            textUnderlineOffset: 3,
            cursor: 'pointer',
          }}
        >
          Return to overview
        </button>
      </div>
    </motion.section>
  );
}

export const EndOfReview = memo(EndOfReviewImpl);
