-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.academic_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  school jsonb NOT NULL DEFAULT '{"city": "", "name": "", "type": "public", "state": "", "country": "USA"}'::jsonb,
  current_grade text NOT NULL,
  gpa numeric CHECK (gpa IS NULL OR gpa >= 0::numeric AND gpa <= 5.00),
  gpa_scale USER-DEFINED NOT NULL DEFAULT '4.0'::gpa_scale,
  weighted_gpa numeric CHECK (weighted_gpa IS NULL OR weighted_gpa >= 0::numeric),
  class_rank integer CHECK (class_rank IS NULL OR class_rank > 0),
  class_size integer,
  coursework jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(coursework) = 'array'::text),
  planned_courses jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(planned_courses) = 'array'::text),
  standardized_tests jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(standardized_tests) = 'array'::text),
  strong_subjects ARRAY NOT NULL DEFAULT '{}'::text[],
  struggling_subjects ARRAY NOT NULL DEFAULT '{}'::text[],
  academic_interests ARRAY NOT NULL DEFAULT '{}'::text[],
  academic_honors ARRAY NOT NULL DEFAULT '{}'::text[],
  summer_programs ARRAY NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT academic_records_pkey PRIMARY KEY (id),
  CONSTRAINT academic_records_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.achievements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  title text NOT NULL,
  organization text NOT NULL,
  type USER-DEFINED NOT NULL,
  date_received date NOT NULL,
  scope USER-DEFINED NOT NULL,
  impact USER-DEFINED NOT NULL DEFAULT 'medium'::achievement_impact,
  description text NOT NULL,
  criteria text,
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  verification_url text,
  document_url text,
  context jsonb NOT NULL DEFAULT '{"effort": "", "growth": "", "backstory": "", "significance": ""}'::jsonb,
  skills_demonstrated ARRAY NOT NULL DEFAULT '{}'::text[],
  character_traits ARRAY NOT NULL DEFAULT '{}'::text[],
  enhanced_description text,
  relevance_scores jsonb NOT NULL DEFAULT '{}'::jsonb,
  suggested_narratives ARRAY NOT NULL DEFAULT '{}'::text[],
  is_underrecognized boolean NOT NULL DEFAULT false,
  requires_context boolean NOT NULL DEFAULT false,
  search_vector tsvector,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT achievements_pkey PRIMARY KEY (id),
  CONSTRAINT achievements_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.ai_analysis_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  analysis_type text NOT NULL,
  model_version text NOT NULL,
  analysis_result jsonb NOT NULL,
  confidence_score numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  CONSTRAINT ai_analysis_cache_pkey PRIMARY KEY (id),
  CONSTRAINT ai_analysis_cache_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.assessment_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid,
  session_type text NOT NULL DEFAULT 'initial'::text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  questions_answered integer NOT NULL DEFAULT 0,
  total_questions integer,
  completion_rate numeric NOT NULL DEFAULT 0,
  responses jsonb NOT NULL DEFAULT '{}'::jsonb,
  insights jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '24:00:00'::interval),
  CONSTRAINT assessment_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT assessment_sessions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.enrichment_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  session_type text NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  items_completed ARRAY NOT NULL DEFAULT '{}'::text[],
  completion_rate numeric NOT NULL DEFAULT 0,
  points_earned integer NOT NULL DEFAULT 0,
  achievements_unlocked ARRAY NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT enrichment_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT enrichment_sessions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.experiences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  title text NOT NULL,
  organization text NOT NULL,
  type USER-DEFINED NOT NULL,
  start_date date NOT NULL,
  end_date date,
  is_ongoing boolean NOT NULL DEFAULT false,
  time_commitment USER-DEFINED NOT NULL,
  total_hours integer,
  description text NOT NULL,
  responsibilities ARRAY NOT NULL DEFAULT '{}'::text[],
  achievements ARRAY NOT NULL DEFAULT '{}'::text[],
  challenges ARRAY NOT NULL DEFAULT '{}'::text[],
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  skills_demonstrated jsonb NOT NULL DEFAULT '[]'::jsonb,
  lessons_learned ARRAY NOT NULL DEFAULT '{}'::text[],
  tools_used ARRAY NOT NULL DEFAULT '{}'::text[],
  transferable_skills ARRAY NOT NULL DEFAULT '{}'::text[],
  leadership_examples ARRAY NOT NULL DEFAULT '{}'::text[],
  problem_solving_examples ARRAY NOT NULL DEFAULT '{}'::text[],
  verification_url text,
  supervisor_name text,
  can_contact boolean NOT NULL DEFAULT false,
  ai_extracted_themes ARRAY NOT NULL DEFAULT '{}'::text[],
  narrative_summary text,
  college_relevance_score numeric CHECK (college_relevance_score IS NULL OR college_relevance_score >= 0::numeric AND college_relevance_score <= 1::numeric),
  search_vector tsvector,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT experiences_pkey PRIMARY KEY (id),
  CONSTRAINT experiences_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profile_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['profile_created'::text, 'profile_updated'::text, 'profile_archived'::text, 'experience_added'::text, 'experience_updated'::text, 'experience_deleted'::text, 'achievement_added'::text, 'achievement_updated'::text, 'achievement_deleted'::text, 'academic_record_added'::text, 'academic_record_updated'::text, 'assessment_started'::text, 'assessment_completed'::text, 'enrichment_completed'::text, 'analysis_generated'::text])),
  event_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  user_id uuid,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profile_events_pkey PRIMARY KEY (id),
  CONSTRAINT profile_events_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profile_skills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  skill text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['technical'::text, 'soft'::text, 'domain'::text, 'language'::text])),
  confidence numeric NOT NULL CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['experience'::text, 'achievement'::text, 'academic'::text, 'ai_extracted'::text])),
  source_id uuid,
  evidence ARRAY NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profile_skills_pkey PRIMARY KEY (id),
  CONSTRAINT profile_skills_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  user_context USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'initial'::profile_status,
  goals jsonb NOT NULL DEFAULT '{"primaryGoal": "exploring_options", "desiredOutcomes": [], "timelineUrgency": "flexible"}'::jsonb,
  constraints jsonb NOT NULL DEFAULT '{"needsFinancialAid": false}'::jsonb,
  demographics jsonb NOT NULL DEFAULT '{}'::jsonb,
  completion_score numeric NOT NULL DEFAULT 0.00 CHECK (completion_score >= 0::numeric AND completion_score <= 1::numeric),
  completion_details jsonb NOT NULL DEFAULT '{"overall": 0, "sections": {"basic": 0, "goals": 0, "academic": 0, "enrichment": 0, "experience": 0}}'::jsonb,
  extracted_skills jsonb NOT NULL DEFAULT '{}'::jsonb,
  hidden_strengths ARRAY NOT NULL DEFAULT '{}'::text[],
  narrative_summary text,
  last_enrichment_date timestamp with time zone,
  enrichment_priorities jsonb NOT NULL DEFAULT '[]'::jsonb,
  search_vector tsvector,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  archived_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);