-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.academic_journey (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  current_school jsonb DEFAULT '{}'::jsonb,
  current_grade text,
  expected_grad_date date,
  gpa numeric,
  gpa_scale text,
  gpa_type text,
  class_rank text,
  class_size integer,
  other_schools jsonb DEFAULT '{}'::jsonb,
  course_history jsonb DEFAULT '[]'::jsonb,
  college_courses jsonb DEFAULT '[]'::jsonb,
  standardized_tests jsonb DEFAULT '{}'::jsonb,
  ap_exams jsonb DEFAULT '[]'::jsonb,
  ib_exams jsonb DEFAULT '[]'::jsonb,
  english_proficiency jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  will_graduate_from_school boolean NOT NULL DEFAULT false,
  is_boarding_school boolean NOT NULL DEFAULT false,
  studied_abroad boolean NOT NULL DEFAULT false,
  homeschooled boolean NOT NULL DEFAULT false,
  took_math_early boolean NOT NULL DEFAULT false,
  took_language_early boolean NOT NULL DEFAULT false,
  report_test_scores boolean NOT NULL DEFAULT false,
  taking_ap_exams boolean NOT NULL DEFAULT false,
  in_ib_programme boolean NOT NULL DEFAULT false,
  need_english_proficiency boolean NOT NULL DEFAULT false,
  rank_reporting_method text CHECK (rank_reporting_method IS NULL OR (rank_reporting_method = ANY (ARRAY['exact'::text, 'decile'::text, 'quartile'::text, 'quintile'::text, 'none'::text]))),
  CONSTRAINT academic_journey_pkey PRIMARY KEY (id),
  CONSTRAINT academic_journey_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.credit_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  amount integer NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['subscription_grant'::text, 'addon_purchase'::text, 'usage'::text, 'bonus'::text])),
  description text,
  stripe_payment_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT credit_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT credit_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  ua text,
  os text,
  browser text,
  ip_hash text,
  country text,
  last_seen timestamp with time zone NOT NULL DEFAULT now(),
  revoked_at timestamp with time zone,
  CONSTRAINT devices_pkey PRIMARY KEY (id),
  CONSTRAINT devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.experiences_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  work_experiences jsonb DEFAULT '[]'::jsonb,
  volunteer_service jsonb DEFAULT '[]'::jsonb,
  extracurriculars jsonb DEFAULT '[]'::jsonb,
  personal_projects jsonb DEFAULT '[]'::jsonb,
  academic_honors jsonb DEFAULT '[]'::jsonb,
  formal_recognition jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  leadership_roles jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT experiences_activities_pkey PRIMARY KEY (id),
  CONSTRAINT experiences_activities_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.family_responsibilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  responsibilities jsonb NOT NULL DEFAULT '[]'::jsonb,
  circumstances jsonb NOT NULL DEFAULT '[]'::jsonb,
  hours_per_week smallint NOT NULL DEFAULT 0 CHECK (hours_per_week >= 0 AND hours_per_week <= 168),
  other_responsibilities text DEFAULT ''::text,
  challenging_circumstances boolean NOT NULL DEFAULT false,
  other_circumstances text DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT family_responsibilities_pkey PRIMARY KEY (id),
  CONSTRAINT family_responsibilities_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.goals_aspirations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  intended_major text,
  career_interests ARRAY NOT NULL DEFAULT '{}'::text[],
  highest_degree text CHECK (highest_degree IS NULL OR (highest_degree = ANY (ARRAY['bachelors'::text, 'masters'::text, 'phd'::text, 'md'::text, 'jd'::text, 'other_professional'::text, 'undecided'::text]))),
  college_environment ARRAY NOT NULL DEFAULT '{}'::text[],
  college_plans jsonb,
  applying_to_uc text CHECK (applying_to_uc IS NULL OR (applying_to_uc = ANY (ARRAY['yes'::text, 'no'::text, 'maybe'::text]))),
  using_common_app text CHECK (using_common_app IS NULL OR (using_common_app = ANY (ARRAY['yes'::text, 'no'::text, 'maybe'::text]))),
  start_date text CHECK (start_date IS NULL OR (start_date = ANY (ARRAY['fall_2025'::text, 'spring_2026'::text, 'fall_2026'::text, 'gap_year'::text, 'undecided'::text]))),
  geographic_preferences ARRAY NOT NULL DEFAULT '{}'::text[],
  need_based_aid text CHECK (need_based_aid IS NULL OR (need_based_aid = ANY (ARRAY['yes'::text, 'no'::text, 'unsure'::text]))),
  merit_scholarships text CHECK (merit_scholarships IS NULL OR (merit_scholarships = ANY (ARRAY['yes'::text, 'no'::text, 'unsure'::text]))),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT goals_aspirations_pkey PRIMARY KEY (id),
  CONSTRAINT goals_aspirations_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.personal_growth (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  meaningful_experiences jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(meaningful_experiences) = 'object'::text),
  additional_context jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(additional_context) = 'object'::text),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  search_vector tsvector,
  CONSTRAINT personal_growth_pkey PRIMARY KEY (id),
  CONSTRAINT personal_growth_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.personal_information (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  first_name text,
  last_name text,
  preferred_name text,
  date_of_birth date,
  primary_email text,
  primary_phone text,
  secondary_phone text,
  pronouns text,
  gender_identity text,
  permanent_address jsonb,
  alternate_address jsonb,
  place_of_birth jsonb,
  hispanic_latino text,
  hispanic_background text,
  race_ethnicity ARRAY,
  citizenship_status text,
  primary_language text,
  other_languages jsonb,
  years_in_us integer,
  former_names ARRAY,
  living_situation text,
  household_size text,
  household_income text,
  parent_guardians jsonb,
  siblings jsonb,
  first_gen boolean,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT personal_information_pkey PRIMARY KEY (id),
  CONSTRAINT personal_information_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.portfolio_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  input_signature text NOT NULL,
  overall numeric NOT NULL,
  dimensions jsonb NOT NULL,
  detailed jsonb NOT NULL,
  cached_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portfolio_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT portfolio_analytics_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.portfolio_analytics_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  prev_overall numeric,
  new_overall numeric NOT NULL,
  prev_dimensions jsonb,
  new_dimensions jsonb NOT NULL,
  changed_fields jsonb,
  reason_summary text,
  model_used text,
  cost_cents integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portfolio_analytics_history_pkey PRIMARY KEY (id),
  CONSTRAINT portfolio_analytics_history_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  user_context USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'initial'::profile_status,
  goals jsonb NOT NULL DEFAULT '{"primaryGoal": "exploring_options", "desiredOutcomes": [], "timelineUrgency": "flexible"}'::jsonb,
  constraints jsonb NOT NULL DEFAULT '{"needsFinancialAid": false}'::jsonb,
  demographics jsonb NOT NULL DEFAULT '{}'::jsonb,
  completion_score numeric NOT NULL DEFAULT 0.00 CHECK (completion_score >= 0::numeric AND completion_score <= 1::numeric),
  completion_details jsonb NOT NULL DEFAULT '{"overall": 0, "sections": {"basic": 0, "goals": 0, "academic": 0, "enrichment": 0, "experience": 0}}'::jsonb,
  extracted_skills jsonb NOT NULL DEFAULT '{}'::jsonb,
  hidden_strengths ARRAY NOT NULL DEFAULT '{}'::text[],
  narrative_summary text,
  last_enrichment_date timestamp with time zone,
  enrichment_priorities jsonb NOT NULL DEFAULT '[]'::jsonb,
  search_vector tsvector,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  archived_at timestamp with time zone,
  deleted_at timestamp with time zone,
  has_completed_assessment boolean NOT NULL DEFAULT false,
  credits integer NOT NULL DEFAULT 0,
  stripe_customer_id text,
  subscription_status text DEFAULT 'none'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'canceled'::text, 'past_due'::text, 'none'::text])),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  stripe_subscription_id text NOT NULL UNIQUE,
  status text NOT NULL,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.support_network (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  counselor jsonb NOT NULL DEFAULT '{}'::jsonb,
  community_support_legacy jsonb,
  portfolio_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  documents jsonb NOT NULL DEFAULT '[]'::jsonb,
  teachers jsonb NOT NULL DEFAULT '[]'::jsonb,
  has_community_support boolean NOT NULL DEFAULT false,
  community_organizations jsonb NOT NULL DEFAULT '[]'::jsonb,
  has_portfolio_items boolean NOT NULL DEFAULT false,
  wants_to_upload_documents boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT support_network_pkey PRIMARY KEY (id),
  CONSTRAINT support_network_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);