-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.academic_journey (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  current_school jsonb DEFAULT '{}'::jsonb,
  current_grade text,
  expected_grad_date date,
  gpa numeric,
  gpa_scale text,
  gpa_type text,
  class_rank text,
  class_size integer,
  other_schools jsonb DEFAULT '{}'::jsonb,
  course_history jsonb DEFAULT '[]'::jsonb,
  college_courses jsonb DEFAULT '[]'::jsonb,
  standardized_tests jsonb DEFAULT '{}'::jsonb,
  ap_exams jsonb DEFAULT '[]'::jsonb,
  ib_exams jsonb DEFAULT '[]'::jsonb,
  english_proficiency jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  will_graduate_from_school boolean NOT NULL DEFAULT false,
  is_boarding_school boolean NOT NULL DEFAULT false,
  studied_abroad boolean NOT NULL DEFAULT false,
  homeschooled boolean NOT NULL DEFAULT false,
  took_math_early boolean NOT NULL DEFAULT false,
  took_language_early boolean NOT NULL DEFAULT false,
  report_test_scores boolean NOT NULL DEFAULT false,
  taking_ap_exams boolean NOT NULL DEFAULT false,
  in_ib_programme boolean NOT NULL DEFAULT false,
  need_english_proficiency boolean NOT NULL DEFAULT false,
  rank_reporting_method text CHECK (rank_reporting_method IS NULL OR (rank_reporting_method = ANY (ARRAY['exact'::text, 'decile'::text, 'quartile'::text, 'quintile'::text, 'none'::text]))),
  CONSTRAINT academic_journey_pkey PRIMARY KEY (id),
  CONSTRAINT academic_journey_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.experiences_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  work_experiences jsonb DEFAULT '[]'::jsonb,
  volunteer_service jsonb DEFAULT '[]'::jsonb,
  extracurriculars jsonb DEFAULT '[]'::jsonb,
  personal_projects jsonb DEFAULT '[]'::jsonb,
  academic_honors jsonb DEFAULT '[]'::jsonb,
  formal_recognition jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  leadership_roles jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT experiences_activities_pkey PRIMARY KEY (id),
  CONSTRAINT experiences_activities_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.family_responsibilities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  responsibilities jsonb,
  life_circumstances jsonb,
  CONSTRAINT family_responsibilities_pkey PRIMARY KEY (id),
  CONSTRAINT family_responsibilities_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.goals_aspirations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  intended_major text,
  career_interests ARRAY,
  highest_degree text,
  preferred_environment ARRAY,
  college_plans jsonb,
  CONSTRAINT goals_aspirations_pkey PRIMARY KEY (id),
  CONSTRAINT goals_aspirations_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.personal_growth (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  meaningful_experiences jsonb,
  additional_context jsonb,
  CONSTRAINT personal_growth_pkey PRIMARY KEY (id),
  CONSTRAINT personal_growth_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.personal_information (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  first_name text,
  last_name text,
  preferred_name text,
  date_of_birth date,
  primary_email text,
  primary_phone text,
  secondary_phone text,
  pronouns text,
  gender_identity text,
  permanent_address jsonb,
  alternate_address jsonb,
  place_of_birth jsonb,
  hispanic_latino text,
  hispanic_background text,
  race_ethnicity ARRAY,
  citizenship_status text,
  primary_language text,
  other_languages jsonb,
  years_in_us integer,
  former_names ARRAY,
  living_situation text,
  household_size text,
  household_income text,
  parent_guardians jsonb,
  siblings jsonb,
  first_gen boolean,
  CONSTRAINT personal_information_pkey PRIMARY KEY (id),
  CONSTRAINT personal_information_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  user_context USER-DEFINED NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'initial'::profile_status,
  goals jsonb NOT NULL DEFAULT '{"primaryGoal": "exploring_options", "desiredOutcomes": [], "timelineUrgency": "flexible"}'::jsonb,
  constraints jsonb NOT NULL DEFAULT '{"needsFinancialAid": false}'::jsonb,
  demographics jsonb NOT NULL DEFAULT '{}'::jsonb,
  completion_score numeric NOT NULL DEFAULT 0.00 CHECK (completion_score >= 0::numeric AND completion_score <= 1::numeric),
  completion_details jsonb NOT NULL DEFAULT '{"overall": 0, "sections": {"basic": 0, "goals": 0, "academic": 0, "enrichment": 0, "experience": 0}}'::jsonb,
  extracted_skills jsonb NOT NULL DEFAULT '{}'::jsonb,
  hidden_strengths ARRAY NOT NULL DEFAULT '{}'::text[],
  narrative_summary text,
  last_enrichment_date timestamp with time zone,
  enrichment_priorities jsonb NOT NULL DEFAULT '[]'::jsonb,
  search_vector tsvector,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  archived_at timestamp with time zone,
  deleted_at timestamp with time zone,
  has_completed_assessment boolean NOT NULL DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.support_network (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  counselor jsonb,
  teachers ARRAY,
  community_support jsonb,
  portfolio_items jsonb,
  documents jsonb,
  CONSTRAINT support_network_pkey PRIMARY KEY (id),
  CONSTRAINT support_network_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);